from pathlib import Path
import re

def one(text, old, new, label):
    count=text.count(old)
    assert count==1, f"{label}: expected 1, got {count}"
    return text.replace(old,new,1)

# Dashboard: one synchronized date range for every card, with the original area chart.
p=Path('components/DashboardClient.tsx');t=p.read_text()
t=one(t,'type DashboardRange="today"|"7d"|"30d"|"month";','type DashboardRange="today"|"7d"|"30d"|"month"|"custom";','dashboard range type')
t=one(t,'  month:{button:"Este mes",title:"Mes actual",short:"este mes",hint:"Desde el día 1"},\n};','  month:{button:"Este mes",title:"Mes actual",short:"este mes",hint:"Desde el día 1"},\n  custom:{button:"Fechas",title:"Rango personalizado",short:"rango elegido",hint:"Elige desde / hasta"},\n};','dashboard range copy')
t=one(t,'const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*86400000);','const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*86400000);\nconst localDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;\nconst dateFromInput=(value:string,fallback:Date)=>{const match=/^(\\d{4})-(\\d{2})-(\\d{2})$/.exec(value);return match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):startOfDay(fallback)};','dashboard date helpers')
pattern=r'function getPeriodBounds\(range:DashboardRange\)\{.*?\n\}'
replacement='''function getPeriodBounds(range:DashboardRange,customFrom?:string,customTo?:string){
  const now=new Date(),today=startOfDay(now),periodEnd=new Date(now.getTime()+1);
  if(range==="today")return{periodStart:today,periodEnd,previousStart:addDays(today,-1),previousEnd:today};
  if(range==="7d"){const periodStart=addDays(today,-6);return{periodStart,periodEnd,previousStart:addDays(periodStart,-7),previousEnd:periodStart}}
  if(range==="30d"){const periodStart=addDays(today,-29);return{periodStart,periodEnd,previousStart:addDays(periodStart,-30),previousEnd:periodStart}}
  if(range==="custom"){
    const first=dateFromInput(customFrom||"",addDays(today,-6)),last=dateFromInput(customTo||"",today),periodStart=first<=last?first:last,lastDay=first<=last?last:first,customEnd=addDays(lastDay,1),days=Math.max(1,Math.round((customEnd.getTime()-periodStart.getTime())/86400000));
    return{periodStart,periodEnd:customEnd,previousStart:addDays(periodStart,-days),previousEnd:periodStart};
  }
  const periodStart=new Date(today.getFullYear(),today.getMonth(),1),previousStart=new Date(today.getFullYear(),today.getMonth()-1,1),previousEnd=periodStart;
  return{periodStart,periodEnd,previousStart,previousEnd};
}'''
t,n=re.subn(pattern,replacement,t,count=1,flags=re.S);assert n==1,'dashboard bounds'
t=one(t,'  const[range,setRange]=useState<DashboardRange>("7d");\n  const[paymentHelpOpen,setPaymentHelpOpen]=useState(false);','  const[range,setRange]=useState<DashboardRange>("7d");\n  const[customFrom,setCustomFrom]=useState(()=>localDate(addDays(new Date(),-6)));\n  const[customTo,setCustomTo]=useState(()=>localDate(new Date()));\n  const[paymentHelpOpen,setPaymentHelpOpen]=useState(false);','dashboard state')
t=one(t,'sales=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===ctx.branchId&&saleVisibleAfterHistoryReset(s,settings)),bounds=getPeriodBounds(range),now=new Date(),today=startOfDay(now);','sales=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===ctx.branchId&&saleVisibleAfterHistoryReset(s,settings)),bounds=getPeriodBounds(range,customFrom,customTo),now=new Date(),today=startOfDay(now);','dashboard bounds call')
needle='''    if(range==="month"){
      const elapsed=Math.max(1,Math.ceil((today.getTime()-bounds.periodStart.getTime())/86400000)+1),points=Math.min(7,elapsed),bucket=Math.max(1,Math.ceil(elapsed/points));
      chart=Array.from({length:points},(_,index)=>{const start=addDays(bounds.periodStart,index*bucket),end=addDays(start,bucket),total=sales.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=start&&stamp<end&&stamp<bounds.periodEnd}).reduce((sum,s)=>sum+s.total,0);return{key:start.toISOString(),label:new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(start).replace(".",""),total}});
    }
    const best=chart.reduce((winner,item)=>item.total>winner.total?item:winner,chart[0]||{key:"none",label:"—",total:0});
    return{sales,inPeriod,total,previousTotal,trend,avgTicket,paymentTotals,top,chart,best};
  },[db,ctx,range]);'''
replacement='''    if(range==="month"){
      const elapsed=Math.max(1,Math.ceil((today.getTime()-bounds.periodStart.getTime())/86400000)+1),points=Math.min(7,elapsed),bucket=Math.max(1,Math.ceil(elapsed/points));
      chart=Array.from({length:points},(_,index)=>{const start=addDays(bounds.periodStart,index*bucket),end=addDays(start,bucket),total=sales.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=start&&stamp<end&&stamp<bounds.periodEnd}).reduce((sum,s)=>sum+s.total,0);return{key:start.toISOString(),label:new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(start).replace(".",""),total}});
    }
    if(range==="custom"){
      const elapsed=Math.max(1,Math.ceil((bounds.periodEnd.getTime()-bounds.periodStart.getTime())/86400000)),points=Math.min(10,elapsed),bucket=Math.max(1,Math.ceil(elapsed/points));
      chart=Array.from({length:points},(_,index)=>{const start=addDays(bounds.periodStart,index*bucket),end=new Date(Math.min(addDays(start,bucket).getTime(),bounds.periodEnd.getTime())),total=sales.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=start&&stamp<end}).reduce((sum,s)=>sum+s.total,0);return{key:start.toISOString(),label:new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(start).replace(".",""),total}}).filter(point=>new Date(point.key)<bounds.periodEnd);
    }
    const chartWithSales=chart.map((point,index)=>{let start:Date,end:Date;if(range==="today"){const hour=Number(point.key.replace("h",""))||0;start=new Date(today);start.setHours(hour,0,0,0);end=new Date(today);end.setHours(hour+4,0,0,0)}else{start=new Date(point.key);end=index+1<chart.length?new Date(chart[index+1].key):bounds.periodEnd}const pointSales=inPeriod.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=start&&stamp<end});return{...point,sales:pointSales}});
    const best=chartWithSales.reduce((winner,item)=>item.total>winner.total?item:winner,chartWithSales[0]||{key:"none",label:"—",total:0,sales:[]});
    return{sales,inPeriod,total,previousTotal,trend,avgTicket,paymentTotals,top,chart:chartWithSales,best};
  },[db,ctx,range,customFrom,customTo]);'''
t=one(t,needle,replacement,'dashboard chart sync')
dominant='  const dominant=[...payments].sort((a,b)=>b.amount-a.amount)[0];'
t=one(t,dominant,dominant+'\n  const periodLabel=range==="custom"?`${new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(dateFromInput(customFrom,new Date()))} – ${new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(dateFromInput(customTo,new Date()))}`:rangeCopy[range].title;\n  const periodShort=range==="custom"?"rango elegido":rangeCopy[range].short;','dashboard labels')
t=one(t,'<span>{rangeCopy[range].title}</span><strong>{money(dashboard.total)}</strong>','<span>{periodLabel}</span><strong>{money(dashboard.total)}</strong>','dashboard summary label')
t=one(t,'<div className="dashboard-period-copy"><span>VER RESULTADOS DE</span><strong>{rangeCopy[range].title}</strong></div>','<div className="dashboard-period-copy"><span>VER RESULTADOS DE</span><strong>{periodLabel}</strong></div>','dashboard toolbar label')
switch='<div className="dashboard-range-switch dashboard-range-switch-v3">{(Object.keys(rangeCopy) as DashboardRange[]).map(key=><button key={key} aria-pressed={range===key} className={range===key?"active":""} onClick={()=>setRange(key)}><b>{rangeCopy[key].button}</b><small>{rangeCopy[key].hint}</small></button>)}</div>'
custom=switch+'{range==="custom"&&<div className="dashboard-custom-range"><label>Desde<input type="date" value={customFrom} max={customTo} onChange={e=>setCustomFrom(e.target.value||customFrom)}/></label><label>Hasta<input type="date" value={customTo} min={customFrom} max={localDate(new Date())} onChange={e=>setCustomTo(e.target.value||customTo)}/></label><small>Todo el tablero usa estas mismas fechas.</small></div>}'
t=one(t,switch,custom,'dashboard custom controls')
t=t.replace('{rangeCopy[range].short}','{periodShort}')
t=one(t,'<DashboardSalesExplorer sales={dashboard.sales}/>','<DashboardSalesExplorer chart={dashboard.chart} total={dashboard.total} trend={dashboard.trend} periodLabel={periodLabel}/>','dashboard area explorer props')
t=t.replace('<small>{rangeCopy[range].title}</small>','<small>{periodLabel}</small>')
p.write_text(t)

# POS: explicit category ordering and one scrollable checkout body with fixed action footer.
p=Path('components/PosClientPro.tsx');t=p.read_text()
t=one(t,'  const[internalConsumption,setInternalConsumption]=useState(false);\n  const[dragCategory,setDragCategory]=useState("");','  const[internalConsumption,setInternalConsumption]=useState(false);\n  const[categoryOrderMode,setCategoryOrderMode]=useState(false);\n  const[dragCategory,setDragCategory]=useState("");','pos order mode state')
move='const moveCategory=(source:string,target:string)=>{if(!source||!target||source===target||source==="Todos"||target==="Todos")return;const order=[...orderedCategories],from=order.indexOf(source),to=order.indexOf(target);if(from<0||to<0)return;order.splice(from,1);order.splice(to,0,source);const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),current=getTenantSettings(next,workspace.tenantId),updated={...current,categoryOrder:order};next.settings=next.settings.filter(item=>item.tenantId!==workspace.tenantId);next.settings.push(updated);saveLocalDatabase(next);setDb(loadLocalDatabase());setDragCategory("");setDragOverCategory("");window.dispatchEvent(new CustomEvent(KIUBO_DATA_REFRESHED,{detail:{source:"category-order"}}))};'
t=one(t,move,move+'\n  const shiftCategory=(item:string,direction:-1|1)=>{const index=orderedCategories.indexOf(item),target=orderedCategories[index+direction];if(index<0||!target)return;moveCategory(item,target)};','pos category shift')
oldcat='<div className="category-strip">{categories.map(item=><button key={item} draggable={item!=="Todos"} className={`${category===item?"selected":""} ${dragCategory===item?"category-dragging":""} ${dragOverCategory===item?"category-drop-target":""}`} onClick={()=>setCategory(item)} onDragStart={event=>{if(item!=="Todos"){event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",item);setDragCategory(item)}}} onDragEnter={()=>{if(item!=="Todos"&&dragCategory&&dragCategory!==item)setDragOverCategory(item)}} onDragOver={event=>{if(item!=="Todos"){event.preventDefault();event.dataTransfer.dropEffect="move";setDragOverCategory(item)}}} onDrop={event=>{event.preventDefault();const source=event.dataTransfer.getData("text/plain")||dragCategory;moveCategory(source,item)}} onDragEnd={()=>{setDragCategory("");setDragOverCategory("")}}>{item}</button>)}<span className="category-order-hint">Arrastra para ordenar</span></div>'
newcat='<div className="category-toolbar"><div className="category-strip">{categories.map(item=><button key={item} draggable={!categoryOrderMode&&item!=="Todos"} className={`${category===item?"selected":""} ${dragCategory===item?"category-dragging":""} ${dragOverCategory===item?"category-drop-target":""}`} onClick={()=>setCategory(item)} onDragStart={event=>{if(!categoryOrderMode&&item!=="Todos"){event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",item);setDragCategory(item)}}} onDragEnter={()=>{if(!categoryOrderMode&&item!=="Todos"&&dragCategory&&dragCategory!==item)setDragOverCategory(item)}} onDragOver={event=>{if(!categoryOrderMode&&item!=="Todos"){event.preventDefault();event.dataTransfer.dropEffect="move";setDragOverCategory(item)}}} onDrop={event=>{event.preventDefault();const source=event.dataTransfer.getData("text/plain")||dragCategory;moveCategory(source,item)}} onDragEnd={()=>{setDragCategory("");setDragOverCategory("")}}>{item}</button>)}</div>{orderedCategories.length>1&&<button type="button" className={`category-order-toggle ${categoryOrderMode?"active":""}`} onClick={()=>setCategoryOrderMode(value=>!value)}>{categoryOrderMode?"✓ Listo":"↕ Ordenar"}</button>}</div>{categoryOrderMode&&<div className="category-order-editor" aria-label="Ordenar categorías">{orderedCategories.map((item,index)=><div className="category-order-item" key={item}><button type="button" className="category-order-label" onClick={()=>setCategory(item)}>{index+1}. {item}</button><span><button type="button" aria-label={`Mover ${item} a la izquierda`} disabled={index===0} onClick={()=>shiftCategory(item,-1)}>←</button><button type="button" aria-label={`Mover ${item} a la derecha`} disabled={index===orderedCategories.length-1} onClick={()=>shiftCategory(item,1)}>→</button></span></div>)}</div>}'
t=one(t,oldcat,newcat,'pos category toolbar')
t=one(t,'</div>\n      <div className="checkout-customer-block">','</div>\n      <div className="pos-checkout-scroll"><div className="checkout-customer-block">','pos scroll open')
t=one(t,'\n      <div className="pos-checkout-footer">','\n      </div><div className="pos-checkout-footer">','pos scroll close')
p.write_text(t)

# Inventory: editing a controlled item now includes stock, cost, unit and alert threshold in one workflow.
p=Path('components/InventoryClient.tsx');t=p.read_text()
pattern=r'  const updateIngredient=\(e:FormEvent<HTMLFormElement>,productId:string\)=>\{.*?\};\n  const addRecipeComponent='
replacement='''  const updateIngredient=(e:FormEvent<HTMLFormElement>,productId:string)=>{
    e.preventDefault();const f=new FormData(e.currentTarget),name=clean(String(f.get("name")||"")),unit=clean(String(f.get("unit")||"u"))||"u",cost=Number(f.get("cost")||0),threshold=Number(f.get("threshold")||0),stock=Number(f.get("stock")||0),stockReason=clean(String(f.get("stockReason")||""));
    if(!name||!Number.isFinite(cost)||cost<0||!Number.isFinite(threshold)||threshold<0||!Number.isFinite(stock)||stock<0){setMessage("Revisa los datos del ingrediente");return}
    if(isYuki&&(!Number.isInteger(threshold)||!Number.isInteger(stock))){setMessage("En YUKI el stock y el mínimo deben ser unidades completas");return}
    const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),product=next.tenantProducts.find(p=>p.id===productId&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId&&inventoryOnly(p));if(!product){setMessage("Ingrediente no encontrado");return}
    const duplicate=next.tenantProducts.find(p=>p.id!==productId&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId&&inventoryOnly(p)&&p.name.toLocaleLowerCase("es")===name.toLocaleLowerCase("es"));if(duplicate){setMessage(`${name} ya existe como ingrediente`);return}
    const stockChanged=Math.abs(stock-product.stock)>.000001;if(stockChanged&&!stockReason){setMessage("Escribe el motivo si vas a cambiar el stock");return}
    const productBefore={...product},previousStock=product.stock;product.name=name;product.cost=cost;const editable=asInventoryProduct(product);editable.stockUnit=unit;editable.lowStockThreshold=threshold;
    if(stockChanged){const delta=Number((stock-previousStock).toFixed(4)),now=new Date().toISOString(),movementId=makeId("stock");product.stock=Number(stock.toFixed(4));const productAfter={...product},movement:StockMovementRecord={id:movementId,tenantId:workspace.tenantId,branchId:workspace.branchId,productId:product.id,type:delta>0?"adjustment_in":"adjustment_out",quantity:delta,previousStock,newStock:product.stock,reference:stockReason,clientOperationId:movementId,createdAt:now};next.stockMovements.unshift(movement);enqueueInventoryAdjustment(next,{productId:product.id,delta,reason:stockReason,movementId,createdAt:now,productBefore,productAfter,movement});saveLocalDatabase(next,{trackChanges:false});setDb(loadLocalDatabase());setMessage(`${name} actualizado · stock ${formatStock(product.stock,unit)}`);window.dispatchEvent(new CustomEvent(KIUBO_DATA_REFRESHED,{detail:{source:"inventory-edit"}}))}else persist(next,`${name} actualizado`);
    setEditIngredientId("");
  };
  const addRecipeComponent='''
t,n=re.subn(pattern,replacement,t,count=1,flags=re.S);assert n==1,'inventory update function'
old='<form className={styles.editForm} onSubmit={e=>updateIngredient(e,product.id)}><div className={styles.formRow}><input name="name" defaultValue={product.name} placeholder="Nombre" required/><input name="unit" defaultValue={stockUnit(product)} placeholder="Unidad" required/></div><div className={styles.formRow}><input name="cost" type="number" min="0" step="0.01" defaultValue={product.cost} placeholder="Costo"/><input name="threshold" type="number" min="0" step={quantityStep} defaultValue={lowStockThreshold(product)} placeholder="Mínimo"/></div><div className={styles.editActions}><a href="#inventory-adjustment">Cambiar stock</a><button type="submit">Guardar cambios</button></div></form>'
new='<form className={styles.editForm} onSubmit={e=>updateIngredient(e,product.id)}><div className="inventory-edit-heading"><span>Editar control completo</span><small>Sin ir a Productos</small></div><div className={styles.formRow}><input name="name" defaultValue={product.name} placeholder="Nombre" required/><input name="unit" defaultValue={stockUnit(product)} placeholder="Unidad" required/></div><div className={styles.formRow}><input name="cost" type="number" min="0" step="0.01" defaultValue={product.cost} placeholder="Costo"/><input name="threshold" type="number" min="0" step={quantityStep} defaultValue={lowStockThreshold(product)} placeholder="Mínimo"/></div><div className={styles.formRow}><label className="inventory-stock-field">Stock actual<input name="stock" type="number" min="0" step={quantityStep} defaultValue={product.stock} required/></label><label className="inventory-stock-field">Motivo si cambia<input name="stockReason" placeholder="Ej. conteo físico"/></label></div><small className="inventory-stock-help">Si cambias el stock aquí, KIUBO registra el ajuste en el historial automáticamente.</small><div className={styles.editActions}><span className="inventory-edit-actions-copy">La receta del producto vendido se configura en el paso 2 de esta misma pantalla.</span><button type="submit">Guardar todo</button></div></form>'
t=one(t,old,new,'inventory edit form')
p.write_text(t)

# Protected history reset: never accept an inherited/default code that the owner did not explicitly configure.
p=Path('components/OperationalSalesInsights.tsx');t=p.read_text()
t=one(t,'import { KIUBO_DATA_REFRESHED } from "./RealtimeSyncRuntime";','import { KIUBO_DATA_REFRESHED } from "./RealtimeSyncRuntime";\nimport { adminAuthorizationConfigured } from "@/lib/admin-authorization";','history auth import')
t=one(t,'  const canReset=Boolean(data.ctx.user?.platformAdmin||data.ctx.user?.role==="owner"||data.ctx.user?.role==="admin");','  const canReset=Boolean(data.ctx.user?.platformAdmin||data.ctx.user?.role==="owner"||data.ctx.user?.role==="admin");\n  const resetConfigured=canReset&&adminAuthorizationConfigured(data.ctx.tenantId,data.ctx.user?.id);','history auth state')
old='if(resetBusy||!canReset)return;const code=resetCode.trim();if(!code){setResetMessage("Escribe el código de administrador.");return}\n    const current=loadLocalDatabase(),ctx=getWorkspaceContext(current),authorized=current.users.some(user=>user.active&&user.tenantId===ctx.tenantId&&(user.role==="owner"||user.role==="admin"||user.platformAdmin)&&user.pin===code);\n    if(!authorized){setResetMessage("Código incorrecto.");return}'
new='if(resetBusy||!canReset)return;if(!resetConfigured){setResetMessage("Primero configura tu propio código de autorización.");return}const code=resetCode.trim();if(!code){setResetMessage("Escribe tu código de autorización.");return}\n    const current=loadLocalDatabase(),ctx=getWorkspaceContext(current),currentUser=current.users.find(user=>user.id===ctx.user?.id&&user.tenantId===ctx.tenantId&&user.active),authorized=Boolean(currentUser&&(currentUser.role==="owner"||currentUser.role==="admin"||currentUser.platformAdmin)&&currentUser.pin===code);\n    if(!authorized){setResetMessage("Código incorrecto. Usa el que configuraste en Administración.");return}'
t=one(t,old,new,'history reset validation')
oldui='<p>Inicia un historial nuevo para esta sucursal. Las ventas anteriores quedan archivadas de forma segura y no cambian inventario, productos, clientes ni caja. Requiere código de propietario/administrador.</p><div className={styles.dangerForm}><input type="password" inputMode="numeric" value={resetCode} onChange={e=>setResetCode(e.target.value)} placeholder="Código" autoComplete="off"/><button type="button" disabled={resetBusy||!data.branchSales.length} onClick={()=>void resetSales()}>{resetBusy?"Verificando…":"Reiniciar"}</button></div>{resetMessage&&<div className={styles.status}>{resetMessage}</div>}'
newui='<p>Inicia un historial nuevo para esta sucursal. Las ventas anteriores quedan archivadas de forma segura y no cambian inventario, productos, clientes ni caja.</p>{!resetConfigured?<div className="history-code-unconfigured"><span>No existe un código creado por ti en este equipo.</span><a href="/operations#authorization-code">Configurar código</a></div>:<div className={styles.dangerForm}><input type="password" inputMode="numeric" value={resetCode} onChange={e=>setResetCode(e.target.value)} placeholder="Tu código" autoComplete="off"/><button type="button" disabled={resetBusy||!data.branchSales.length} onClick={()=>void resetSales()}>{resetBusy?"Verificando…":"Reiniciar"}</button></div>}{resetMessage&&<div className={styles.status}>{resetMessage}</div>}'
t=one(t,oldui,newui,'history reset ui')
p.write_text(t)

# Give the authorization section an anchor and load v15 last.
p=Path('components/AdminPinManager.tsx');t=p.read_text();t=one(t,'return <section className="panel admin-pin-panel">','return <section id="authorization-code" className="panel admin-pin-panel">','pin anchor');p.write_text(t)
p=Path('app/layout.tsx');t=p.read_text();t=one(t,'import "./experience-v14.css";','import "./experience-v14.css";\nimport "./experience-v15.css";','v15 css import');p.write_text(t)
