import Link from "next/link";
import { PublicHeader } from "@/components/PublicHeader";
import { PublicLivePreview } from "@/components/PublicLivePreview";

const modules=[
  {icon:"▣",title:"POS",text:"Vende rápido, cobra como prefieras y descuenta stock al instante."},
  {icon:"▦",title:"Inventario",text:"Stock, kardex, compras y proveedores conectados a cada sucursal."},
  {icon:"◎",title:"Caja",text:"Aperturas, cierres, ingresos y egresos con una lectura clara del turno."},
  {icon:"◉",title:"Clientes",text:"Historial, fiados y cuentas por cobrar sin libretas ni registros duplicados."},
  {icon:"↗",title:"Reportes",text:"Ventas, utilidad bruta, compras, caja y comparativos sin armar fórmulas."},
  {icon:"◇",title:"Factura",text:"Foundation preparada para SRI; se habilita comercialmente cuando el flujo esté certificado."}
];

export default function HomePage(){return <main className="marketing-shell premium-marketing"><PublicHeader/>
  <section className="public-hero premium-hero"><div className="public-hero-copy"><div className="hero-status"><i/> KIUBO · Sistema operativo para pequeños negocios</div><span className="public-kicker">MENOS CAOS. MÁS CONTROL.</span><h1>Tu negocio,<br/><em>más claro.</em></h1><p>KIUBO conecta ventas, inventario, caja, clientes y gestión en una experiencia moderna que tu equipo puede entender desde el primer día.</p><div className="public-hero-actions"><Link className="button primary hero-primary" href="/demo">Quiero verlo en mi negocio <span>→</span></Link><Link className="button secondary" href="/precios">Explorar planes</Link></div><div className="public-trust-row premium-trust"><span>✓ 14 días de prueba</span><span>✓ Sin tarjeta</span><span>✓ PC, tablet y móvil</span><span>✓ Preparado para offline</span></div></div><PublicLivePreview/></section>

  <section className="public-section public-proof premium-proof"><span>Creado para que vender sea rápido y entender el negocio sea simple.</span><strong>Todo tu negocio, en orden.</strong></section>

  <section className="public-section" id="funciones"><div className="public-section-head"><span className="public-kicker">TU DÍA, EN UNA SOLA PLATAFORMA</span><h2>Lo importante aparece donde lo necesitas.</h2><p>No queremos llenarte de pantallas. Queremos que cada acción tenga sentido: vender, saber qué falta, controlar caja y tomar mejores decisiones.</p></div><div className="public-feature-grid premium-feature-grid">{modules.map(item=><article key={item.title}><div className="feature-icon">{item.icon}</div><span>{item.title}</span><p>{item.text}</p><b>Explorar módulo <i>→</i></b></article>)}</div></section>

  <section className="public-section experience-section"><div className="public-section-head"><span className="public-kicker">UNA PLATAFORMA, TRES EXPERIENCIAS</span><h2>Cada persona ve lo que realmente necesita.</h2></div><div className="experience-grid"><article><div className="experience-label coral">CAJERO</div><div className="experience-screen"><span>Venta actual</span><strong>$24.80</strong><div><i/> Efectivo</div><div><i/> Transferencia</div><button>Cobrar</button></div><h3>Vender sin distraerse</h3><p>El cajero entra directo a lo operativo y no se pierde entre configuraciones.</p></article><article className="featured-experience"><div className="experience-label blue">DUEÑO</div><div className="experience-screen owner-screen"><span>Hoy</span><strong>$428.60</strong><div className="mini-bars"><i/><i/><i/><i/><i/></div><small>Ventas · Stock · Caja · Clientes</small></div><h3>Entender el negocio</h3><p>El propietario puede revisar qué está pasando sin abrir cinco archivos distintos.</p></article><article><div className="experience-label navy">KIUBO CONTROL</div><div className="experience-screen control-screen"><span>Negocios</span><strong>12</strong><div><i/> Trials activos <b>3</b></div><div><i/> Onboarding <b>2</b></div><button>Ver pipeline</button></div><h3>Administrar la plataforma</h3><p>Nuestro equipo controla clientes, trials, módulos y seguimiento desde una zona separada.</p></article></div></section>

  <section className="public-section public-value premium-value"><div><span className="public-kicker">CRECE SIN CAMBIAR DE SISTEMA</span><h2>Empieza simple. Activa más cuando lo necesites.</h2><p>Start cubre la operación esencial. Pro agrega control comercial más avanzado. Custom adapta branding, sucursales y necesidades especiales sin crear otro software desde cero.</p><div className="value-chips"><span>Start</span><span>Pro</span><span>Custom</span><span>Factura como add-on</span></div></div><div className="public-value-card premium-value-card"><small>PREVIEW COMERCIAL</small><strong>Desde $7.90/mes*</strong><span>El precio definitivo se cerrará antes del lanzamiento público.</span><Link href="/precios">Comparar qué incluye cada plan →</Link></div></section>

  <section className="public-section public-steps premium-steps"><div className="public-section-head"><span className="public-kicker">DE INTERESADO A OPERANDO</span><h2>La entrega también debe sentirse fácil.</h2></div><div className="public-step-grid"><article><b>01</b><div className="step-icon">⌕</div><h3>Nos cuentas cómo trabajas</h3><p>Por llamada, videollamada o presencial. La demo se enfoca en tus problemas reales.</p></article><article><b>02</b><div className="step-icon">⚙</div><h3>Configuramos tu negocio</h3><p>Sucursal, productos, usuarios, caja y reglas básicas quedan preparados contigo.</p></article><article><b>03</b><div className="step-icon">✓</div><h3>Recibes tu acceso</h3><p>Abres KIUBO desde tu PC, inicias sesión y tu equipo empieza a trabajar.</p></article></div></section>

  <section className="public-cta premium-cta"><div><span className="public-kicker">KIUBO</span><h2>Que tu sistema ayude.<br/>No que estorbe.</h2><p>Conoce el producto antes de pagar y decide con tu operación real.</p></div><div className="cta-actions"><Link className="button primary" href="/demo">Solicitar demo</Link><Link className="button secondary" href="/como-funciona">Ver cómo funciona</Link></div></section>
</main>}
