"use client";
import { FormEvent,useEffect,useState } from "react";
import { TenantBrandingRecord,getTenantBranding,getWorkspaceContext,loadLocalDatabase,saveLocalDatabase } from "@/lib/local-store";
import { KiuboWordmark } from "./KiuboWordmark";

const defaults={primaryColor:"#ff5b55",secondaryColor:"#0d2b4d",accentColor:"#ff8a3d"};
export function BrandingClient(){
  const[branding,setBranding]=useState<TenantBrandingRecord|null>(null),[message,setMessage]=useState("Cambios listos para revisar");
  useEffect(()=>{const db=loadLocalDatabase(),ctx=getWorkspaceContext(db);setBranding(getTenantBranding(db,ctx.tenantId))},[]);
  if(!branding)return <div className="loading-card">Preparando marca…</div>;
  const db=loadLocalDatabase(),ctx=getWorkspaceContext(db);
  const update=<K extends keyof TenantBrandingRecord>(key:K,value:TenantBrandingRecord[K])=>setBranding(current=>current?{...current,[key]:value}:current);
  const save=(e:FormEvent)=>{e.preventDefault();const current=loadLocalDatabase(),index=current.branding.findIndex(b=>b.tenantId===ctx.tenantId),next={...branding,tenantId:ctx.tenantId,updatedAt:new Date().toISOString()};if(index>=0)current.branding[index]=next;else current.branding.push(next);saveLocalDatabase(current);setBranding(next);setMessage("Identidad guardada y lista para usar")};
  const reset=()=>{setBranding({...branding,...defaults,logoUrl:"",businessName:ctx.tenant?.name??"Negocio",receiptTagline:"Gracias por tu compra"});setMessage("Vista restablecida; guarda para aplicar")};
  const style={"--preview-primary":branding.primaryColor,"--preview-secondary":branding.secondaryColor,"--preview-accent":branding.accentColor} as React.CSSProperties;
  return <div className="brand-studio">
    <div className="workspace-banner"><div><span>NEGOCIO</span><strong>{ctx.tenant?.name}</strong></div><div><span>USO</span><strong>Sistema + ticket</strong></div><div><span>ESTADO</span><strong>{message}</strong></div></div>
    <header className="brand-studio-head"><div><span className="eyebrow">MARCA Y TICKET</span><h1>Una sola identidad, en todo KIUBO.</h1><p>Configura lo que el equipo ve en el sistema y lo que el cliente recibe al final de la venta.</p></div><div className="brand-studio-badge"><span>Gestionado con</span><KiuboWordmark/></div></header>
    <section className="brand-studio-grid">
      <form className="brand-editor" onSubmit={save}><div className="brand-editor-title"><div><span>IDENTIDAD</span><h2>{branding.businessName||"Tu negocio"}</h2></div><span className="brand-saved-dot">●</span></div><label>Nombre comercial<input value={branding.businessName} onChange={e=>update("businessName",e.target.value)} required/></label><label>Logo del negocio <small>URL de imagen</small><input value={branding.logoUrl} onChange={e=>update("logoUrl",e.target.value)} placeholder="https://.../logo.png"/></label><div className="brand-color-row"><label><span>Principal</span><div><input type="color" value={branding.primaryColor} onChange={e=>update("primaryColor",e.target.value)}/><b>{branding.primaryColor}</b></div></label><label><span>Oscuro</span><div><input type="color" value={branding.secondaryColor} onChange={e=>update("secondaryColor",e.target.value)}/><b>{branding.secondaryColor}</b></div></label><label><span>Acento</span><div><input type="color" value={branding.accentColor} onChange={e=>update("accentColor",e.target.value)}/><b>{branding.accentColor}</b></div></label></div><label>Mensaje al cliente<input value={branding.receiptTagline} onChange={e=>update("receiptTagline",e.target.value)} placeholder="Gracias por tu compra"/></label><div className="brand-usage"><span>Se refleja en</span><div><b>Barra lateral</b><b>Ticket</b><b>Impresión</b></div></div><div className="branding-actions"><button className="button primary" type="submit">Guardar identidad</button><button className="button secondary" type="button" onClick={reset}>Volver a base KIUBO</button></div></form>
      <div className="brand-preview-stack" style={style}><article className="brand-system-preview"><span className="brand-preview-label">EN EL SISTEMA</span><div className="brand-preview-sidebar"><div className="brand-preview-identity">{branding.logoUrl&&<img src={branding.logoUrl} alt=""/>}<div><strong>{branding.businessName||"Tu negocio"}</strong><small>Gestionado con <KiuboWordmark/></small></div></div><div className="brand-preview-nav"><span className="active">⌂ Inicio</span><span>$ Ventas / POS</span><span>≡ Pedidos</span><span>↗ Reportes</span></div></div></article><article className="brand-ticket-preview"><span className="brand-preview-label">EN EL TICKET</span><div className="mini-ticket">{branding.logoUrl&&<img src={branding.logoUrl} alt=""/>}<strong>{branding.businessName||"Tu negocio"}</strong><small>COMPROBANTE DE VENTA</small><div/><p><span>Combo 4</span><b>$14.00</b></p><p><span>Envase</span><b>$0.50</b></p><div className="ticket-total"><span>TOTAL</span><strong>$14.50</strong></div><em>{branding.receiptTagline||"Gracias por tu compra"}</em><small>Generado por <KiuboWordmark/></small></div></article></div>
    </section>
  </div>
}
