"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { KiuboLocalDatabase,TenantRecord,TenantStatus,getWorkspaceContext,loadLocalDatabase,makeId,saveLocalDatabase,switchWorkspace } from "@/lib/local-store";
import { CommercialPlan,hasFeature } from "@/lib/entitlements";
import { loadLeads,onboardingProgress,type LeadRecord } from "@/lib/sales-crm";
import { addCloudBranch,hydrateCloudControl,isCloudControlMode,provisionCloudTenant,setCloudTenantFeature,setCloudTenantPlan,setCloudTenantStatus } from "@/lib/cloud-control";

const statusLabel:Record<TenantStatus,string>={active:"Activo",trial:"Trial",grace:"Gracia",suspended:"Suspendido"};
const STANDARD_TRIAL_DAYS=14;
const plans:CommercialPlan[]=["Start","Pro","Custom"];
const shortDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"America/Guayaquil"}).format(date)};
const price:Record<CommercialPlan,number>={Start:7.9,Pro:12.9,Custom:19.9};

export function ControlClient(){
  const cloud=isCloudControlMode();
  const[db,setDb]=useState<KiuboLocalDatabase|null>(null),[leads,setLeads]=useState<LeadRecord[]>([]),[showForm,setShowForm]=useState(false),[message,setMessage]=useState(cloud?"Conectando KIUBO Control con la nube…":"Administración maestra lista"),[busy,setBusy]=useState(false);
  const refresh=async()=>{const next=cloud?await hydrateCloudControl():loadLocalDatabase();setDb(next);return next};
  useEffect(()=>{let active=true;void(async()=>{try{const next=cloud?await hydrateCloudControl():loadLocalDatabase();if(active){setDb(next);setMessage(cloud?"KIUBO Control conectado a la nube":"Administración maestra lista")}}catch(error){if(active)setMessage(error instanceof Error?error.message:"No se pudo cargar KIUBO Control")}if(active)setLeads(loadLeads())})();return()=>{active=false}},[cloud]);
  const overview=useMemo(()=>{const tenants=(db?.tenants??[]).filter(t=>t.plan!=="Internal"),active=tenants.filter(t=>t.status==="active"),trial=tenants.filter(t=>t.status==="trial"),mrr=active.reduce((n,t)=>n+price[t.plan as CommercialPlan],0),licenses=(db?.users??[]).filter(u=>!u.platformAdmin&&u.active).length;return{tenants,active,trial,mrr,licenses}},[db]);
  if(!db)return <div className="loading-card">Preparando KIUBO Control…</div>;
  const ctx=getWorkspaceContext(db);if(!ctx.user?.platformAdmin)return <div className="license-block"><div className="hero-mini">K</div><span className="eyebrow">ACCESO RESTRINGIDO</span><h2>KIUBO Control es solo para administración maestra.</h2></div>;
  const persist=(next:KiuboLocalDatabase)=>{saveLocalDatabase(next);setDb(loadLocalDatabase())},commercialTenants=overview.tenants;

  const createTenant=async(e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form),name=String(f.get("name")||"").trim(),ownerName=String(f.get("ownerName")||"").trim(),ownerEmail=String(f.get("ownerEmail")||"").trim().toLowerCase(),plan=String(f.get("plan")||"Start") as CommercialPlan;
    if(!name||!ownerName||!ownerEmail){setMessage("Completa negocio, propietario y correo");return}
    setBusy(true);
    try{
      if(cloud){await provisionCloudTenant({businessName:name,ownerName,ownerEmail,plan});await refresh();setMessage(`${name} creado en KIUBO Cloud. Se envió invitación a ${ownerEmail}.`)}
      else{const pin=String(f.get("pin")||"").trim();if(!/^[0-9]{4}$/.test(pin)){setMessage("El PIN demo debe tener 4 dígitos");return}if(db.users.some(u=>u.email.toLowerCase()===ownerEmail)){setMessage("Ese correo ya existe en KIUBO");return}const tenantId=makeId("tenant"),branchId=makeId("branch"),now=new Date().toISOString(),expires=new Date(Date.now()+STANDARD_TRIAL_DAYS*86400000).toISOString().slice(0,10);db.tenants.unshift({id:tenantId,name,plan,status:"trial",users:1,branches:1,expiresAt:expires,catalog:plan!=="Start",invoice:false,createdAt:now});db.branches.push({id:branchId,tenantId,name:"Matriz",code:"001",active:true,createdAt:now});db.settings.push({tenantId,tradeName:name,legalName:"",ruc:"",establishment:"001",emissionPoint:"001",currency:"USD",accent:"#ff5b55",receiptFooter:"Gracias por tu compra",requireCashSession:false,allowCredit:plan!=="Start",address:"",phone:"",businessType:"general",serviceModes:["counter"],tableCount:0,showProductImages:true,splashEnabled:true,receiptWidth:"80mm"});db.users.push({id:makeId("user"),tenantId,name:ownerName,email:ownerEmail,role:"owner",active:true,pin,platformAdmin:false,createdAt:now});persist(db);setMessage(`${name} creado con Trial estándar de ${STANDARD_TRIAL_DAYS} días`)}
      form.reset();setShowForm(false);
    }catch(error){setMessage(error instanceof Error?error.message:"No se pudo crear el negocio")}finally{setBusy(false)}
  };

  const setPlan=async(tenant:TenantRecord,plan:CommercialPlan)=>{if(busy)return;setBusy(true);try{if(cloud){await setCloudTenantPlan(tenant.id,plan);await refresh()}else{db.tenants=db.tenants.map(t=>t.id===tenant.id?{...t,plan,catalog:plan!=="Start"}:t);db.settings=db.settings.map(s=>s.tenantId===tenant.id?{...s,allowCredit:plan!=="Start"}:s);persist(db)}setMessage(`${tenant.name} ahora usa ${plan}. No se borró ningún dato.`)}catch(error){setMessage(error instanceof Error?error.message:"No se pudo cambiar el plan")}finally{setBusy(false)}};

  const addBranch=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form),tenantId=String(f.get("tenantId")||""),name=String(f.get("name")||"").trim(),code=String(f.get("code")||"").trim().padStart(3,"0"),tenant=db.tenants.find(t=>t.id===tenantId);if(!tenantId||!name||!code||!tenant)return;if(!hasFeature(tenant,"multiBranch")){setMessage("Múltiples sucursales requieren Custom");return}if(db.branches.some(b=>b.tenantId===tenantId&&b.code===code)){setMessage("Ese código de sucursal ya existe");return}setBusy(true);try{if(cloud){await addCloudBranch(tenantId,name,code);await refresh()}else{db.branches.push({id:makeId("branch"),tenantId,name,code,active:true,createdAt:new Date().toISOString()});db.tenants=db.tenants.map(t=>t.id===tenantId?{...t,branches:db.branches.filter(b=>b.tenantId===tenantId).length}:t);persist(db)}form.reset();setMessage(`Sucursal ${code} creada`)}catch(error){setMessage(error instanceof Error?error.message:"No se pudo crear la sucursal")}finally{setBusy(false)}};

  const toggleStatus=async(tenant:TenantRecord)=>{if(busy)return;const status:TenantStatus=tenant.status==="suspended"?"active":"suspended";setBusy(true);try{if(cloud){await setCloudTenantStatus(tenant.id,status);await refresh()}else{db.tenants=db.tenants.map(t=>t.id===tenant.id?{...t,status}:t);persist(db)}setMessage(`${tenant.name}: ${statusLabel[status]}`)}catch(error){setMessage(error instanceof Error?error.message:"No se pudo actualizar la licencia")}finally{setBusy(false)}};

  const toggleModule=async(tenant:TenantRecord,key:"catalog"|"invoice")=>{if(busy)return;if(key==="catalog"&&tenant.plan==="Start"){setMessage("Catalog inteligente requiere Pro o Custom");return}const enabled=!tenant[key];setBusy(true);try{if(cloud){await setCloudTenantFeature(tenant.id,key,enabled);await refresh()}else{db.tenants=db.tenants.map(t=>t.id===tenant.id?{...t,[key]:enabled}:t);persist(db)}setMessage(`${key==="catalog"?"Catalog+":"Factura"} ${enabled?"activado":"desactivado"} para ${tenant.name}`)}catch(error){setMessage(error instanceof Error?error.message:"No se pudo actualizar el módulo")}finally{setBusy(false)}};

  const openWorkspace=(tenantId:string)=>{const branch=db.branches.find(b=>b.tenantId===tenantId&&b.active);switchWorkspace(tenantId,branch?.id);const preview=window.open("/app?preview=client","_blank");if(preview)preview.opener=null;setMessage("Vista cliente abierta en una pestaña nueva")};
  const stageCounts={new:leads.filter(l=>l.stage==="new").length,contacted:leads.filter(l=>l.stage==="contacted").length,demo:leads.filter(l=>l.stage==="demo").length,trial:leads.filter(l=>l.stage==="trial").length,won:leads.filter(l=>l.stage==="won").length};
  const onboard=leads.filter(l=>l.stage==="trial"||l.stage==="won").sort((a,b)=>onboardingProgress(a)-onboardingProgress(b)).slice(0,5),planCounts={Start:commercialTenants.filter(t=>t.plan==="Start").length,Pro:commercialTenants.filter(t=>t.plan==="Pro").length,Custom:commercialTenants.filter(t=>t.plan==="Custom").length},totalPlans=Math.max(1,commercialTenants.length);

  return <div className="ref-control-dashboard"><header className="ref-control-top"><div><h1>KIUBO Control</h1><span>{cloud?"Panel cloud de administración":"Panel de control general"}</span></div><div className="ref-control-actions"><div className="ref-control-search">⌕ Buscar cuentas, usuarios, licencias…</div><button>♧</button><div className="ref-control-user"><i>K</i><span><b>Admin KIUBO</b><small>Super Admin</small></span></div></div></header><div className="pos-message">{message}</div><div className="ref-control-cta"><button className="button ref-blue-button" disabled={busy} onClick={()=>setShowForm(v=>!v)}>+ Nuevo negocio</button></div>{showForm&&<form className="create-tenant create-tenant-expanded" onSubmit={createTenant}><div><span className="eyebrow">ALTA COMERCIAL</span><h3>Crear negocio + matriz + propietario</h3><p>{cloud?"El propietario recibirá una invitación y definirá su propia contraseña.":`Trial estándar: ${STANDARD_TRIAL_DAYS} días.`}</p></div><input name="name" placeholder="Nombre del negocio" required autoFocus/><select name="plan" defaultValue="Pro">{plans.map(plan=><option key={plan}>{plan}</option>)}</select><input name="ownerName" placeholder="Nombre del propietario" required/><input name="ownerEmail" type="email" placeholder="Correo de acceso" required/>{!cloud&&<input name="pin" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="PIN 4 dígitos" required/>}<button className="button ref-blue-button" type="submit" disabled={busy}>{busy?"Procesando…":cloud?"Crear e invitar propietario":"Crear trial"}</button></form>}
    <section className="ref-control-kpis"><article><i className="coral">◎</i><span>Prospectos</span><strong>{leads.filter(l=>l.stage!=="won"&&l.stage!=="lost").length}</strong><small>Pipeline comercial</small></article><article><i className="purple">□</i><span>Demos agendadas</span><strong>{stageCounts.demo}</strong><small>Etapa demo</small></article><article><i className="orange">△</i><span>Trials activos</span><strong>{overview.trial.length}</strong><small>Negocios probando</small></article><article><i className="green">◎</i><span>Clientes activos</span><strong>{overview.active.length}</strong><small>Operación habilitada</small></article><article><i className="blue">$</i><span>MRR estimado</span><strong>${overview.mrr.toFixed(2)}</strong><small>Según precios preview</small></article><article><i className="navy">◇</i><span>Licencias activas</span><strong>{overview.licenses}</strong><small>Usuarios comerciales</small></article></section>
    <section className="ref-control-grid"><article className="ref-white-card ref-pipeline-card"><div className="ref-card-title"><div><span>Pipeline comercial</span><small>De prospecto a cliente</small></div></div><div className="ref-funnel"><div className="f1"><span>Prospectos</span><b>{stageCounts.new}</b></div><div className="f2"><span>Contactados</span><b>{stageCounts.contacted}</b></div><div className="f3"><span>Demos</span><b>{stageCounts.demo}</b></div><div className="f4"><span>Trials</span><b>{stageCounts.trial}</b></div><div className="f5"><span>Clientes</span><b>{stageCounts.won}</b></div></div></article><article className="ref-white-card"><div className="ref-card-title"><div><span>Onboarding en curso</span><small>Avance por negocio</small></div></div><div className="ref-onboarding-list">{onboard.length?onboard.map(l=><div key={l.id}><span><b>{l.business||l.name}</b><small>{l.plan}</small></span><div><i style={{width:`${onboardingProgress(l)}%`}}/></div><strong>{onboardingProgress(l)}%</strong></div>):<div className="ref-empty-state"><b>Sin onboarding pendientes</b><span>Los trials aparecerán aquí.</span></div>}</div></article><article className="ref-white-card"><div className="ref-card-title"><div><span>Clientes por plan</span><small>Distribución actual</small></div></div><div className="ref-plan-donut" style={{background:`conic-gradient(#1469ff 0 ${(planCounts.Start/totalPlans)*100}%,#ff9418 ${(planCounts.Start/totalPlans)*100}% ${((planCounts.Start+planCounts.Pro)/totalPlans)*100}%,#24b76a ${((planCounts.Start+planCounts.Pro)/totalPlans)*100}% 100%)`}}><div><strong>{commercialTenants.length}</strong><span>negocios</span></div></div><div className="ref-plan-legend"><span><i className="blue"/>Start <b>{planCounts.Start}</b></span><span><i className="orange"/>Pro <b>{planCounts.Pro}</b></span><span><i className="green"/>Custom <b>{planCounts.Custom}</b></span></div></article></section>
    <section className="ref-white-card ref-control-businesses"><div className="ref-card-title"><div><span>Negocios</span><small>{cloud?"Clientes y licencias en KIUBO Cloud":"Clientes, pilotos y licencias"}</small></div><span className="pill">Aislamiento por tenant</span></div><div className="tenant-list">{commercialTenants.map(tenant=>{const userCount=db.users.filter(u=>u.tenantId===tenant.id&&u.active&&!u.platformAdmin).length,branchCount=db.branches.filter(b=>b.tenantId===tenant.id&&b.active).length;return <div className="tenant-row tenant-row-actions" key={tenant.id}><div className="tenant-avatar">{tenant.name.slice(0,2).toUpperCase()}</div><div className="tenant-main"><strong>{tenant.name}</strong><span>{userCount} usuarios · {branchCount} sucursal(es)</span><select className="plan-select" disabled={busy} value={tenant.plan} onChange={e=>void setPlan(tenant,e.target.value as CommercialPlan)}>{plans.map(plan=><option key={plan}>{plan}</option>)}</select></div><div className="tenant-flags"><button disabled={busy} className={tenant.catalog?"flag on":"flag"} onClick={()=>void toggleModule(tenant,"catalog")}>Catalog+</button><button disabled={busy} className={tenant.invoice?"flag on":"flag"} onClick={()=>void toggleModule(tenant,"invoice")}>Factura</button></div><div className="tenant-status"><span className={`status status-${tenant.status}`}>{statusLabel[tenant.status]}</span><small>Vence {shortDate(tenant.expiresAt)}</small></div><div className="tenant-actions"><button className="mini-action resume" onClick={()=>openWorkspace(tenant.id)}>Ver como cliente</button><button disabled={busy} className={tenant.status==="suspended"?"mini-action resume":"mini-action danger"} onClick={()=>void toggleStatus(tenant)}>{tenant.status==="suspended"?"Reactivar":"Suspender"}</button></div></div>})}{!commercialTenants.length&&<div className="ref-empty-state"><b>Aún no hay negocios</b><span>Usa “Nuevo negocio” para crear el primer trial.</span></div>}</div></section>
    <section className="grid-two workspace-admin-grid"><form className="panel inventory-form" onSubmit={addBranch}><span className="eyebrow">SUCURSALES CUSTOM</span><h3>Crear nueva sucursal</h3><label>Negocio<select name="tenantId" required defaultValue=""><option value="" disabled>Selecciona Custom</option>{commercialTenants.filter(t=>t.plan==="Custom").map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="inventory-inline"><label>Código<input name="code" inputMode="numeric" placeholder="002" required/></label><label>Nombre<input name="name" placeholder="Norte, Centro…" required/></label></div><button className="button secondary" type="submit" disabled={busy}>Crear sucursal</button></form><article className="panel"><span className="eyebrow">MODELO COMERCIAL</span><h3>Un producto, varios niveles</h3><p>Start conserva lo esencial. Pro desbloquea compras, fiados y Catalog inteligente. Custom agrega marca y varias sucursales. Factura se habilita aparte.</p><div className="module-chip-row"><span>14 días estándar</span><span>90 días piloto especial</span><span>Cambio de plan sin borrar datos</span></div></article></section>
  </div>
}