"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { getDataProvider } from "@/lib/data-provider";
import { getOpenCashSession,getWorkspaceContext,loadLocalDatabase } from "@/lib/local-store";
import { PLAN_CATALOG,hasFeature,type CommercialPlan,type ProductFeature } from "@/lib/entitlements";

const money=(value:number)=>`$${value.toFixed(2)}`;
export function DashboardClient(){
  const[db,setDb]=useState<ReturnType<typeof loadLocalDatabase>|null>(null);
  useEffect(()=>setDb(loadLocalDatabase()),[]);
  const chart=useMemo(()=>{if(!db)return[];const ctx=getWorkspaceContext(db);return Array.from({length:7},(_,index)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-(6-index));const key=date.toISOString().slice(0,10),total=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===ctx.branchId&&s.createdAt.slice(0,10)===key).reduce((n,s)=>n+s.total,0);return{key,label:new Intl.DateTimeFormat("es-EC",{weekday:"short"}).format(date).replace(".",""),total}})},[db]);
  if(!db)return <div className="loading-card">Preparando inicio…</div>;
  const ctx=getWorkspaceContext(db),tenant=ctx.tenant,provider=getDataProvider();
  if(!tenant||tenant.plan==="Internal")return <div className="loading-card">Selecciona un negocio comercial.</div>;
  const plan=PLAN_CATALOG[tenant.plan as CommercialPlan],today=new Date().toISOString().slice(0,10),salesToday=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===ctx.branchId&&s.createdAt.slice(0,10)===today),todayTotal=salesToday.reduce((n,s)=>n+s.total,0),products=db.tenantProducts.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId&&p.active),customers=db.customers.filter(c=>c.tenantId===ctx.tenantId),low=products.filter(p=>p.stock<=5),receivable=db.credits.filter(c=>c.tenantId===ctx.tenantId&&c.branchId===ctx.branchId&&c.status==="open").reduce((n,c)=>n+c.balance,0),cash=getOpenCashSession(db,ctx.tenantId,ctx.branchId),max=Math.max(1,...chart.map(x=>x.total)),avgTicket=salesToday.length?todayTotal/salesToday.length:0;
  const itemCount=new Map<string,{name:string;qty:number}>();for(const sale of salesToday)for(const item of sale.items){const current=itemCount.get(item.productId)??{name:item.name,qty:0};current.qty+=item.qty;itemCount.set(item.productId,current)}const topProduct=[...itemCount.values()].sort((a,b)=>b.qty-a.qty)[0];
  const hour=new Date().getHours(),greeting=hour<12?"Buenos días":hour<19?"Buenas tardes":"Buenas noches";
  const actions:{href:string;label:string;detail:string;feature:ProductFeature;icon:string}[]=[
    {href:"/pos",label:"Nueva venta",detail:"Abre el POS y cobra",feature:"pos",icon:"$"},
    {href:"/catalog",label:"Productos",detail:"Precios, stock y catálogo",feature:"products",icon:"▦"},
    {href:"/customers",label:"Nuevo cliente",detail:"Datos y cuentas por cobrar",feature:"customers",icon:"◎"},
    {href:"/purchases",label:"Registrar compra",detail:"Proveedor y mercadería",feature:"purchases",icon:"↓"},
    {href:"/reports",label:"Ver reportes",detail:"Ventas y rendimiento",feature:"reports",icon:"↗"}
  ];
  const insight=topProduct?`${topProduct.name} lidera hoy con ${topProduct.qty} unidad${topProduct.qty===1?"":"es"} vendida${topProduct.qty===1?"":"s"}.`:salesToday.length?`El ticket promedio de hoy es ${money(avgTicket)}.`:"Todavía no hay ventas hoy. El POS está listo para comenzar.";
  return <><section className="dashboard-hero"><div><span className="eyebrow light">{tenant.name.toUpperCase()} · {tenant.plan}</span><h1>{greeting}, {ctx.user?.name.split(" ")[0]||"equipo"} 👋</h1><p>{ctx.branch?.code} · {ctx.branch?.name} · {tenant.status==="trial"?`Trial hasta ${tenant.expiresAt}`:"Operación activa"}</p><div className="dashboard-status-line"><span>● {cash?"Caja abierta":"Caja cerrada"}</span><span>{provider.mode==="local"?"○ Preview local":"● Cloud conectado"}</span><span>{low.length?`${low.length} alertas de stock`:"✓ Inventario sin alertas"}</span></div><div className="dashboard-hero-actions"><Link className="button primary" href="/pos">Nueva venta</Link><Link className="button secondary" href="/onboarding">Revisar configuración</Link></div></div><div className="dashboard-plan"><span>PLAN ACTUAL</span><strong>{tenant.plan}</strong><small>{plan.tagline}</small><Link href="/upgrade">Ver módulos →</Link></div></section>
  <section className="metric-grid dashboard-metrics"><article className="metric-card"><div className="metric-icon">$</div><span>Ventas de hoy</span><strong>{money(todayTotal)}</strong><small>{salesToday.length} transacciones · ticket {money(avgTicket)}</small></article><article className="metric-card"><div className="metric-icon">▦</div><span>Productos activos</span><strong>{products.length}</strong><small>{low.length} con stock bajo</small></article><article className="metric-card"><div className="metric-icon">◎</div><span>Clientes</span><strong>{customers.length}</strong><small>{receivable?`${money(receivable)} por cobrar`:"Sin saldo pendiente"}</small></article><article className="metric-card"><div className="metric-icon">◫</div><span>Caja</span><strong>{cash?"Abierta":"Cerrada"}</strong><small>{cash?`Desde ${new Date(cash.openedAt).toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit"})}`:"Abre caja para operar"}</small></article></section>
  <div className="dashboard-insight"><span className="dashboard-insight-icon">✦</span><div><span>INSIGHT DEL DÍA</span><strong>{insight}</strong></div><Link href={salesToday.length?"/reports":"/pos"}>{salesToday.length?"Ver detalle →":"Hacer primera venta →"}</Link></div>
  <section className="dashboard-grid"><article className="panel dashboard-chart-panel"><div className="panel-head"><div><span className="eyebrow">ÚLTIMOS 7 DÍAS</span><h3>Ventas de la sucursal</h3></div><Link href="/reports" className="text-link">Ver reportes</Link></div><div className="dashboard-bars">{chart.map(day=><div key={day.key} className="dashboard-bar-column"><div className="dashboard-bar-track"><i style={{height:`${Math.max(5,(day.total/max)*100)}%`}}/></div><b>{day.label}</b><span>{day.total?money(day.total):"—"}</span></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">ALERTAS</span><h3>Lo que necesita atención</h3></div><span className="pill">{low.length||"OK"}</span></div><div className="dashboard-alerts">{low.slice(0,5).map(p=><div key={p.id}><strong>{p.name}</strong><span>{p.stock} unidades · revisar reposición</span></div>)}{!low.length&&<div><strong>Inventario saludable</strong><span>No hay productos con 5 unidades o menos.</span></div>}{provider.mode==="local"&&<div className="cloud-warning"><strong>Nube todavía no conectada</strong><span>Este preview guarda la información en este dispositivo. El backend real sigue siendo el siguiente gate técnico.</span></div>}</div></article></section>
  <section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">ACCIONES RÁPIDAS</span><h3>¿Qué quieres hacer?</h3></div></div><div className="quick-action-grid">{actions.filter(a=>hasFeature(tenant,a.feature)).map(a=><Link href={a.href} key={a.href}><span className="quick-action-icon">{a.icon}</span><strong>{a.label}</strong><span>{a.detail}</span></Link>)}</div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">TU PLAN</span><h3>{tenant.plan}</h3></div><span className="pill">{plan.price}/mes*</span></div><p>{plan.audience}</p><div className="plan-feature-list">{plan.features.slice(0,6).map(item=><span key={item}>✓ {item}</span>)}{tenant.invoice&&<span>✓ Factura electrónica activada</span>}</div><Link className="text-link" href="/upgrade">Administrar plan y módulos →</Link><small className="dashboard-footnote">* Precio de preview comercial, pendiente de cierre antes del lanzamiento público.</small></article></section></>
}
