"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { getOpenCashSession,getWorkspaceContext,loadLocalDatabase } from "@/lib/local-store";
import { PLAN_CATALOG,type CommercialPlan } from "@/lib/entitlements";
import { KIUBO_DATA_REFRESHED } from "./RealtimeSyncRuntime";

const money=(value:number)=>`$${value.toFixed(2)}`;
const paymentLabel={cash:"Efectivo",transfer:"Transferencia",mixed:"Mixto",credit:"Fiado"} as const;
type DashboardRange="today"|"7d"|"30d";
const rangeCopy:Record<DashboardRange,{button:string;title:string;short:string;days:number}>={today:{button:"Hoy",title:"Ventas de hoy",short:"hoy",days:1},"7d":{button:"7 días",title:"Últimos 7 días",short:"7 días",days:7},"30d":{button:"30 días",title:"Últimos 30 días",short:"30 días",days:30}};
const startOfDay=(date=new Date())=>{const value=new Date(date);value.setHours(0,0,0,0);return value};

export function DashboardClient(){
  const[db,setDb]=useState<ReturnType<typeof loadLocalDatabase>|null>(null);
  const[range,setRange]=useState<DashboardRange>("today");
  useEffect(()=>{const refresh=()=>setDb(loadLocalDatabase());refresh();window.addEventListener(KIUBO_DATA_REFRESHED,refresh);return()=>window.removeEventListener(KIUBO_DATA_REFRESHED,refresh)},[]);
  const ctx=useMemo(()=>db?getWorkspaceContext(db):null,[db]);

  const dashboard=useMemo(()=>{
    if(!db||!ctx)return null;
    const sales=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===ctx.branchId),now=new Date(),today=startOfDay(now),days=rangeCopy[range].days;
    const periodStart=range==="today"?today:new Date(today.getTime()-(days-1)*86400000),periodEnd=new Date(now.getTime()+1),previousEnd=new Date(periodStart),previousStart=new Date(periodStart.getTime()-days*86400000);
    const inPeriod=sales.filter(s=>{const stamp=new Date(s.createdAt).getTime();return stamp>=periodStart.getTime()&&stamp<periodEnd.getTime()}),previous=sales.filter(s=>{const stamp=new Date(s.createdAt).getTime();return stamp>=previousStart.getTime()&&stamp<previousEnd.getTime()});
    const total=inPeriod.reduce((sum,s)=>sum+s.total,0),previousTotal=previous.reduce((sum,s)=>sum+s.total,0),trend=previousTotal>0?((total-previousTotal)/previousTotal)*100:total>0?100:0;
    const paymentTotals={cash:0,transfer:0,credit:0,mixed:0};for(const sale of inPeriod)paymentTotals[sale.payment]+=sale.total;
    const sold=new Map<string,{name:string,qty:number}>();for(const sale of inPeriod)for(const item of sale.items){if(item.name==="Envase")continue;const current=sold.get(item.productId)||{name:item.name,qty:0};current.qty+=item.qty;sold.set(item.productId,current)}
    const top=[...sold.values()].sort((a,b)=>b.qty-a.qty).slice(0,5);
    const chart=range==="today"?Array.from({length:6},(_,index)=>{const start=index*4,end=start+4,total=sales.filter(s=>{const date=new Date(s.createdAt);return date>=today&&date<=now&&date.getHours()>=start&&date.getHours()<end}).reduce((sum,s)=>sum+s.total,0);return{key:`h${start}`,label:`${String(start).padStart(2,"0")}:00`,total}}):range==="7d"?Array.from({length:7},(_,index)=>{const date=new Date(today);date.setDate(date.getDate()-(6-index));const next=new Date(date);next.setDate(next.getDate()+1);const total=sales.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=date&&stamp<next}).reduce((sum,s)=>sum+s.total,0);return{key:date.toISOString(),label:new Intl.DateTimeFormat("es-EC",{weekday:"short"}).format(date).replace(".",""),total}}):Array.from({length:10},(_,index)=>{const start=new Date(today);start.setDate(start.getDate()-(29-index*3));const end=new Date(start);end.setDate(end.getDate()+3);const total=sales.filter(s=>{const stamp=new Date(s.createdAt);return stamp>=start&&stamp<end}).reduce((sum,s)=>sum+s.total,0);return{key:start.toISOString(),label:new Intl.DateTimeFormat("es-EC",{day:"2-digit",month:"short"}).format(start).replace(".",""),total}});
    return{sales,inPeriod,total,trend,paymentTotals,top,chart};
  },[db,ctx,range]);

  if(!db||!ctx||!dashboard)return <div className="loading-card">Preparando inicio…</div>;
  const tenant=ctx.tenant;if(!tenant||tenant.plan==="Internal")return <div className="loading-card">Selecciona un negocio comercial.</div>;
  const products=db.tenantProducts.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId&&p.active&&p.barcode!=="YUKI-ENVASE"),customers=db.customers.filter(c=>c.tenantId===ctx.tenantId),low=products.filter(p=>p.trackStock!==false&&p.stock<=5),cash=getOpenCashSession(db,ctx.tenantId,ctx.branchId),max=Math.max(1,...dashboard.chart.map(x=>x.total));
  const recent=[...dashboard.sales].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5),today=startOfDay(),salesToday=dashboard.sales.filter(s=>new Date(s.createdAt)>=today),cashSales=salesToday.filter(s=>s.payment==="cash").reduce((n,s)=>n+s.total,0),transferSales=salesToday.filter(s=>s.payment==="transfer").reduce((n,s)=>n+s.total,0),todayTotal=salesToday.reduce((n,s)=>n+s.total,0),plan=PLAN_CATALOG[tenant.plan as CommercialPlan];
  const paymentGrand=Math.max(0.01,Object.values(dashboard.paymentTotals).reduce((sum,value)=>sum+value,0)),cashPct=dashboard.paymentTotals.cash/paymentGrand*100,transferPct=dashboard.paymentTotals.transfer/paymentGrand*100,creditPct=dashboard.paymentTotals.credit/paymentGrand*100,mixedPct=dashboard.paymentTotals.mixed/paymentGrand*100;
  const donut=`conic-gradient(#123f31 0 ${cashPct}%, #3c82f6 ${cashPct}% ${cashPct+transferPct}%, #f4a000 ${cashPct+transferPct}% ${cashPct+transferPct+creditPct}%, #ff5b55 ${cashPct+transferPct+creditPct}% ${cashPct+transferPct+creditPct+mixedPct}%, #eef3f0 0)`;

  return <div className="ref-business-dashboard dashboard-v2">
    <header className="ref-app-topbar"><div className="ref-app-search">⌕ <span>Buscar en KIUBO</span><kbd>Ctrl K</kbd></div><div className="ref-topbar-actions"><div className="dashboard-range-switch" aria-label="Período del tablero">{(Object.keys(rangeCopy) as DashboardRange[]).map(key=><button key={key} className={range===key?"active":""} onClick={()=>setRange(key)}>{rangeCopy[key].button}</button>)}</div><div className="ref-user-chip"><span>{(ctx.user?.name||"K").slice(0,1).toUpperCase()}</span><div><strong>{ctx.user?.name||"Usuario"}</strong><small>{ctx.user?.role||""}</small></div></div></div></header>
    <section className="ref-dashboard-title dashboard-title-v2"><div><span className="dashboard-live-dot">● EN VIVO</span><h1>¡Buenos días, {ctx.user?.name.split(" ")[0]||"equipo"}! 👋</h1><p>{tenant.name} · {ctx.branch?.name||"Matriz"}</p></div><div className="dashboard-period-summary"><span>{rangeCopy[range].title}</span><strong>{money(dashboard.total)}</strong><small className={dashboard.trend>=0?"up":"down"}>{dashboard.trend>=0?"↗":"↘"} {Math.abs(dashboard.trend).toFixed(0)}% vs. período anterior</small></div></section>
    <section className="ref-kpi-grid dashboard-kpis-v2"><article><i className="blue">$</i><div><span>{rangeCopy[range].title}</span><strong>{money(dashboard.total)}</strong><small>{dashboard.inPeriod.length} transacciones</small></div></article><article><i className="green">▣</i><div><span>Productos activos</span><strong>{products.length}</strong><small>{low.length} con stock bajo</small></div></article><article><i className="purple">◎</i><div><span>Clientes</span><strong>{customers.length}</strong><small>Registrados en el negocio</small></div></article><article><i className="orange">▤</i><div><span>Caja</span><strong>{cash?"Abierta":"Cerrada"}</strong><small>{cash?`Desde ${new Date(cash.openedAt).toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit"})}`:"Lista para abrir"}</small></div></article></section>
    <section className="dashboard-insight-grid"><article className="ref-white-card ref-week-chart dashboard-chart-card"><div className="ref-card-title"><div><span>Movimiento de ventas</span><small>{rangeCopy[range].title}</small></div><Link href="/reports">Abrir reporte ↗</Link></div><div className="ref-svg-chart"><svg viewBox="0 0 700 210" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="dashFillV2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#123f31" stopOpacity=".20"/><stop offset="1" stopColor="#123f31" stopOpacity="0"/></linearGradient></defs><polyline points={dashboard.chart.map((d,i)=>`${i*(700/Math.max(1,dashboard.chart.length-1))},${190-(d.total/max)*150}`).join(" ")} fill="none" stroke="#123f31" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/><polygon points={`0,210 ${dashboard.chart.map((d,i)=>`${i*(700/Math.max(1,dashboard.chart.length-1))},${190-(d.total/max)*150}`).join(" ")} 700,210`} fill="url(#dashFillV2)"/></svg><div className="ref-chart-labels dashboard-chart-labels">{dashboard.chart.map(d=><span key={d.key}>{d.label}</span>)}</div></div></article>
      <article className="ref-white-card dashboard-donut-card"><div className="ref-card-title"><div><span>Cómo te pagaron</span><small>{rangeCopy[range].title}</small></div><span className="dashboard-info" title="Distribución de ventas por medio de pago">i</span></div><div className="dashboard-donut-wrap"><div className="dashboard-donut" style={{background:donut}}><div><small>Total</small><strong>{money(dashboard.total)}</strong></div></div><div className="dashboard-payment-legend"><div><i className="cash"/><span>Efectivo</span><strong>{money(dashboard.paymentTotals.cash)}</strong></div><div><i className="transfer"/><span>Transferencia</span><strong>{money(dashboard.paymentTotals.transfer)}</strong></div><div><i className="credit"/><span>Fiado</span><strong>{money(dashboard.paymentTotals.credit)}</strong></div>{dashboard.paymentTotals.mixed>0&&<div><i className="mixed"/><span>Mixto</span><strong>{money(dashboard.paymentTotals.mixed)}</strong></div>}</div></div></article>
      <article className="ref-white-card ref-best-products dashboard-top-products"><div className="ref-card-title"><div><span>Más vendidos</span><small>{rangeCopy[range].short}</small></div><Link href="/reports">Ver todos</Link></div>{dashboard.top.length?dashboard.top.map((item,index)=><div className="ref-product-rank" key={`${item.name}-${index}`}><b>{item.name}</b><div><i style={{width:`${Math.max(20,100-index*16)}%`}}/></div><strong>{item.qty}</strong></div>):<div className="ref-empty-state"><b>Sin ventas todavía</b><span>Los favoritos aparecerán aquí.</span></div>}</article></section>
    <section className="ref-dashboard-secondary dashboard-secondary-v2"><article className="ref-white-card"><div className="ref-card-title"><div><span className="danger-text">Stock bajo</span><small>Atención de inventario</small></div><Link href="/inventory">Ver inventario</Link></div><div className="ref-stock-list">{low.slice(0,4).map(p=><div key={p.id}><span>{p.name}</span><b>{p.stock} unidades</b></div>)}{!low.length&&<div><span>Inventario saludable</span><b className="ok-text">Sin alertas</b></div>}</div></article><article className="ref-white-card"><div className="ref-card-title"><div><span>Caja actual</span><small>{cash?"Turno abierto":"Sin turno"}</small></div><span className={`ref-status-dot ${cash?"open":""}`}>{cash?"Abierta":"Cerrada"}</span></div><div className="ref-cash-summary"><div><span>Fondo inicial</span><strong>{money(cash?.openingAmount||0)}</strong></div><div><span>Ventas en efectivo</span><strong>{money(cashSales)}</strong></div><div><span>Transferencias</span><strong>{money(transferSales)}</strong></div><div className="total"><span>Total vendido hoy</span><strong>{money(todayTotal)}</strong></div></div><Link href="/cash" className="button ref-outline-button">Ir a caja</Link></article><article className="ref-white-card ref-quick-card"><div className="ref-card-title"><div><span>Acciones rápidas</span><small>Un toque y listo</small></div></div><div className="ref-quick-actions"><Link href="/pos"><i className="blue">▣</i><span>Nueva venta</span></Link><Link href="/orders"><i className="green">≡</i><span>Pedidos</span></Link><Link href="/customers"><i className="purple">◎</i><span>Clientes</span></Link><Link href="/reports"><i className="orange">↗</i><span>Reportes</span></Link></div></article></section>
    <section className="ref-dashboard-bottom"><article className="ref-white-card"><div className="ref-card-title"><div><span>Ventas recientes</span><small>Últimos movimientos</small></div><Link href="/reports">Ver todas</Link></div><div className="ref-sales-table"><div className="head"><span>Folio</span><span>Hora</span><span>Método</span><span>Total</span></div>{recent.length?recent.map(s=><div key={s.id}><span>{s.id.slice(-8).toUpperCase()}</span><span>{new Date(s.createdAt).toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit"})}</span><span>{paymentLabel[s.payment]}</span><strong>{money(s.total)}</strong></div>):<div className="ref-empty-row">Todavía no hay ventas registradas.</div>}</div></article><article className="ref-white-card ref-plan-summary dashboard-plan-mini"><span className="public-kicker">TU PLAN</span><h3>KIUBO {tenant.plan}</h3><p>{plan.tagline}</p><div className="dashboard-plan-feature-count"><strong>{plan.features.length}</strong><span>capacidades incluidas</span></div><Link href="/upgrade">Ver plan y módulos →</Link></article></section>
  </div>
}
