"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { KiuboLocalDatabase,StockMovementRecord,getWorkspaceContext,loadLocalDatabase,makeId,saveLocalDatabase } from "@/lib/local-store";
import { enqueueInventoryAdjustment } from "@/lib/inventory-transaction";

const movementLabel={sale:"Venta",purchase:"Compra",adjustment_in:"Ajuste +",adjustment_out:"Ajuste -"} as const;

export function InventoryClient(){
  const[db,setDb]=useState<KiuboLocalDatabase|null>(null),[message,setMessage]=useState("Inventario listo");
  useEffect(()=>setDb(loadLocalDatabase()),[]);
  if(!db)return <div className="loading-card">Preparando inventario…</div>;
  const ctx=getWorkspaceContext(db),products=db.tenantProducts.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId&&p.active),suppliers=db.suppliers.filter(s=>s.tenantId===ctx.tenantId),purchases=db.purchases.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId),movements=db.stockMovements.filter(m=>m.tenantId===ctx.tenantId&&m.branchId===ctx.branchId),metrics={units:products.reduce((n,p)=>n+p.stock,0),value:products.reduce((n,p)=>n+p.stock*p.cost,0),low:products.filter(p=>p.stock<=5).length,suppliers:suppliers.length};
  const persist=(next:KiuboLocalDatabase)=>{saveLocalDatabase(next);setDb(loadLocalDatabase())};
  const addSupplier=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get("name")||"").trim();if(!name)return;const next=loadLocalDatabase(),workspace=getWorkspaceContext(next);next.suppliers.unshift({id:makeId("supplier"),tenantId:workspace.tenantId,identification:String(f.get("identification")||"").trim(),name,email:String(f.get("email")||"").trim(),phone:String(f.get("phone")||"").trim(),address:String(f.get("address")||"").trim(),createdAt:new Date().toISOString()});persist(next);e.currentTarget.reset();setMessage("Proveedor guardado para el negocio")};
  const adjust=(e:FormEvent<HTMLFormElement>)=>{
    e.preventDefault();const f=new FormData(e.currentTarget),productId=String(f.get("productId")||""),kind=String(f.get("kind")||"in") as "in"|"out",reason=String(f.get("reason")||"").trim(),qty=Number(f.get("qty")||0);
    if(!Number.isInteger(qty)||qty<=0){setMessage("La cantidad del ajuste debe ser un número entero mayor que cero");return}
    if(!reason){setMessage("Escribe el motivo del ajuste");return}
    const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),product=next.tenantProducts.find(p=>p.id===productId&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId&&p.active);
    if(!product){setMessage("Producto no disponible en esta sucursal");return}
    if(kind==="out"&&qty>product.stock){setMessage(`No puedes retirar ${qty}; el stock actual es ${product.stock}`);return}
    const now=new Date().toISOString(),delta=kind==="in"?qty:-qty,productBefore={...product},newStock=product.stock+delta;
    product.stock=newStock;const productAfter={...product},movementId=makeId("stock");
    const movement:StockMovementRecord={id:movementId,tenantId:workspace.tenantId,branchId:workspace.branchId,productId:product.id,type:delta>0?"adjustment_in":"adjustment_out",quantity:delta,previousStock:productBefore.stock,newStock,reference:reason,clientOperationId:movementId,createdAt:now};
    next.stockMovements.unshift(movement);enqueueInventoryAdjustment(next,{productId:product.id,delta,reason,movementId,createdAt:now,productBefore,productAfter,movement});
    saveLocalDatabase(next,{trackChanges:false});setDb(loadLocalDatabase());e.currentTarget.reset();setMessage(`Stock ajustado · ${product.name} ${delta>0?"+":""}${delta}`)
  };
  return <>
    <div className="workspace-banner"><div><span>NEGOCIO</span><strong>{ctx.tenant?.name}</strong></div><div><span>SUCURSAL</span><strong>{ctx.branch?.code} · {ctx.branch?.name}</strong></div><div><span>ESTADO</span><strong>{message}</strong></div></div>
    <header className="topbar"><div><span className="eyebrow">KIUBO INVENTARIO</span><h1>Stock y movimientos</h1></div><Link className="button secondary" href="/purchases">Ir a Compras</Link></header>
    <section className="metric-grid"><article className="metric-card"><span>Unidades</span><strong>{metrics.units}</strong><small>Stock de sucursal</small></article><article className="metric-card"><span>Valor a costo</span><strong>${metrics.value.toFixed(2)}</strong><small>Inventario estimado</small></article><article className="metric-card"><span>Stock bajo</span><strong>{metrics.low}</strong><small>5 unidades o menos</small></article><article className="metric-card"><span>Proveedores</span><strong>{metrics.suppliers}</strong><small>Compartidos por negocio</small></article></section>
    <section className="inventory-grid">
      <article className="panel"><div className="panel-head"><div><span className="eyebrow">PRODUCTOS</span><h3>Inventario actual</h3></div><span className="pill">{products.length}</span></div><div className="inventory-list">{products.length?products.map(p=>{const margin=p.price?((p.price-p.cost)/p.price)*100:0;return <div className="inventory-row" key={p.id}><div><strong>{p.name}</strong><span>{p.barcode} · costo ${p.cost.toFixed(2)} · venta ${p.price.toFixed(2)}</span></div><b className={p.stock<=5?"stock-low":""}>{p.stock}</b><small>{margin.toFixed(0)}% margen bruto</small></div>}):<p className="empty-cart">Esta sucursal aún no tiene productos.</p>}</div></article>
      <article className="panel"><span className="eyebrow">AJUSTE CONTROLADO</span><h3>Corregir stock de sucursal</h3><p>Úsalo para conteo físico, daño, merma o una corrección justificada. Las compras se registran en el módulo Compras para conservar costo, proveedor y cuentas por pagar.</p><form className="inventory-form" onSubmit={adjust}><label>Producto<select name="productId" required defaultValue=""><option value="" disabled>Selecciona</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · stock {p.stock}</option>)}</select></label><div className="inventory-inline"><label>Tipo<select name="kind"><option value="in">Entrada</option><option value="out">Salida</option></select></label><label>Cantidad<input name="qty" type="number" min="1" step="1" required/></label></div><label>Motivo<input name="reason" placeholder="Conteo físico, daño, merma, corrección…" maxLength={240} required/></label><button className="button primary" type="submit">Aplicar ajuste</button></form><p className="cart-note">El ajuste se guarda localmente y KIUBO Cloud lo confirma con bloqueo de inventario para evitar que dos dispositivos sobrescriban el mismo stock.</p></article>
    </section>
    <section className="inventory-grid">
      <article className="panel"><div className="panel-head"><div><span className="eyebrow">PROVEEDORES</span><h3>Directorio del negocio</h3></div><span className="pill">{suppliers.length}</span></div><form className="inventory-form supplier-form" onSubmit={addSupplier}><input name="name" placeholder="Nombre / razón social" maxLength={160} required/><input name="identification" placeholder="RUC / identificación" maxLength={32}/><input name="phone" placeholder="Teléfono" maxLength={40}/><input name="email" type="email" placeholder="Correo" maxLength={254}/><input name="address" placeholder="Dirección" maxLength={240}/><button className="button secondary" type="submit">Guardar proveedor</button></form><div className="supplier-list">{suppliers.map(s=><div className="supplier-row" key={s.id}><strong>{s.name}</strong><span>{s.identification||"Sin RUC"} · {s.phone||"Sin teléfono"}</span></div>)}</div></article>
      <article className="panel"><div className="panel-head"><div><span className="eyebrow">COMPRAS</span><h3>Recepción de mercadería</h3></div><span className="pill">{purchases.length}</span></div><p>La entrada por compra ya tiene un solo flujo oficial: proveedor + documento + stock + costo promedio + kardex + saldo por pagar.</p><Link className="button primary" href="/purchases">Registrar compra</Link><div className="movement-list" style={{marginTop:14}}>{purchases.length===0?<p className="empty-cart">Todavía no hay compras en esta sucursal.</p>:purchases.slice(0,8).map(p=>{const supplier=suppliers.find(s=>s.id===p.supplierId);return <div className="movement-row" key={p.id}><div><strong>{supplier?.name??"Proveedor"}</strong><span>{p.items.map(i=>`${i.qty}× ${i.name}`).join(" · ")}</span></div><b>${p.total.toFixed(2)}</b><small>{new Date(p.createdAt).toLocaleDateString("es-EC")}</small></div>})}</div></article>
    </section>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">KARDEX</span><h3>Movimientos recientes</h3></div><span className="pill">{movements.length}</span></div><div className="movement-list">{movements.length===0?<p className="empty-cart">Todavía no hay movimientos en esta sucursal.</p>:movements.slice(0,40).map(m=>{const product=products.find(p=>p.id===m.productId);return <div className="movement-row" key={m.id}><div><strong>{product?.name??"Producto"}</strong><span>{movementLabel[m.type]} · {new Date(m.createdAt).toLocaleString("es-EC")} · {m.reference}</span></div><b className={m.quantity>=0?"movement-in":"movement-out"}>{m.quantity>=0?"+":""}{m.quantity}</b><small>{m.previousStock} → {m.newStock}</small></div>})}</div></section>
  </>
}
