"use client";

import { useEffect,useState } from "react";
import { FoodOrderRecord,getTenantBranding,getWorkspaceContext,loadLocalDatabase } from "@/lib/local-store";

const modeLabel:Record<FoodOrderRecord["serviceMode"],string>={counter:"MOSTRADOR",table:"LOCAL",takeaway:"PARA LLEVAR",delivery:"DOMICILIO"};
export function OrderPrintClient(){
  const[data,setData]=useState<{order:FoodOrderRecord;business:string;logo:string}|null>(null);
  useEffect(()=>{
    const id=new URLSearchParams(window.location.search).get("order")||"",db=loadLocalDatabase(),ctx=getWorkspaceContext(db),order=db.orders.find(item=>item.id===id&&item.tenantId===ctx.tenantId&&item.branchId===ctx.branchId);if(!order)return;
    const branding=getTenantBranding(db,ctx.tenantId);setData({order,business:branding.businessName||ctx.tenant?.name||"Negocio",logo:branding.logoUrl||""});
  },[]);
  if(!data)return <main style={{padding:32}}>No encontramos ese pedido en este dispositivo.</main>;
  const {order}=data;
  return <main className="command-page"><style>{`@page{size:80mm auto;margin:4mm}@media print{body{background:#fff!important}.no-print{display:none!important}.command-page{padding:0!important}.command{box-shadow:none!important;border:0!important}}body{margin:0;background:#f4f4f2;font-family:Arial,sans-serif}.command-page{min-height:100vh;display:grid;place-items:start center;padding:24px}.command{width:72mm;background:#fff;color:#111;padding:5mm;box-sizing:border-box;box-shadow:0 8px 30px rgba(0,0,0,.08)}.brand{display:grid;justify-items:center;gap:4px;text-align:center}.brand img{max-width:46mm;max-height:20mm;object-fit:contain}.brand strong{font-size:18px}.order-no{text-align:center;font-size:26px;font-weight:900;margin:12px 0 5px}.mode{text-align:center;border-top:2px solid #111;border-bottom:2px solid #111;padding:7px 0;font-size:16px;font-weight:900}.meta{display:grid;gap:3px;margin:10px 0;font-size:12px}.items{border-top:1px dashed #222;border-bottom:1px dashed #222;padding:8px 0;display:grid;gap:9px}.item{font-size:15px;font-weight:800}.item small{display:block;font-size:11px;font-weight:500;margin-top:2px}.notes{margin-top:9px;padding:8px;border:1px solid #111;font-size:12px;font-weight:700}.actions{width:72mm;display:flex;gap:8px;margin-top:12px}.actions button{flex:1;padding:10px;border:0;border-radius:8px;background:#123f31;color:white;font-weight:800;cursor:pointer}`}</style><section className="command"><div className="brand">{data.logo&&<img src={data.logo} alt=""/>}<strong>{data.business}</strong></div><div className="order-no">PEDIDO #{String(order.number).padStart(4,"0")}</div><div className="mode">{modeLabel[order.serviceMode]}{order.tableLabel?` · ${order.tableLabel}`:""}</div><div className="meta">{order.customerName&&<span><b>Cliente:</b> {order.customerName}</span>}{order.phone&&<span><b>Tel:</b> {order.phone}</span>}{order.address&&<span><b>Dirección:</b> {order.address}</span>}<span><b>Hora:</b> {new Date(order.createdAt).toLocaleTimeString("es-EC",{hour:"2-digit",minute:"2-digit"})}</span></div><div className="items">{order.items.map((item,index)=><div className="item" key={`${item.productId}-${index}`}>{item.qty} × {item.name}{item.notes&&<small>{item.notes}</small>}</div>)}</div>{order.notes&&<div className="notes">NOTA: {order.notes}</div>}<p style={{textAlign:"center",fontSize:9,marginTop:12}}>Gestionado con KIUBO</p></section><div className="actions no-print"><button onClick={()=>window.print()}>Imprimir comanda</button><button onClick={()=>window.close()}>Cerrar</button></div></main>;
}
