"use client";

import { FormEvent,useEffect,useState } from "react";
import {
  type CreditRecord,type CustomerRecord,type FoodOrderRecord,type SaleRecord,type ServiceMode,type StockMovementRecord,type TenantProduct,
  getOpenCashSession,getTenantSettings,getWorkspaceContext,loadLocalDatabase,makeId,nextOrderNumber,saveLocalDatabase,
} from "@/lib/local-store";
import { enqueueSaleTransaction } from "@/lib/sales-transaction";
import { queueFoodOrder } from "@/lib/order-sync";
import { KIUBO_DATA_REFRESHED } from "./RealtimeSyncRuntime";
import { YUKI_PACKAGING_BARCODE } from "./YukiPilotCatalogBootstrap";

type CartLine=TenantProduct&{qty:number;cartKey:string;optionLabel?:string};
type Payment=SaleRecord["payment"];
type PosDraft={cart:Array<{productId:string;qty:number;optionLabel?:string}>;query:string;payment:Payment;customerId:string;category:string;serviceMode:ServiceMode;tableLabel:string;customerName:string;phone:string;address:string;orderNotes:string;activeOrderId:string};
type SaleSuccess={amount:number;method:string;context:string};

const paymentLabel:Record<Payment,string>={cash:"Efectivo",transfer:"Transferencia",mixed:"Mixto",credit:"Fiado"};
const paymentOptions:Payment[]=["cash","transfer","credit"];
const CHECKOUT_KEY="kiubo.food.checkout.order.v1";
const POS_DRAFT_PREFIX="kiubo.pos.draft.v3";
const serviceLabel:Record<ServiceMode,string>={counter:"Mostrador",table:"Local / mesa",takeaway:"Para llevar",delivery:"Domicilio"};
const posDraftKey=(tenantId:string,branchId:string)=>`${POS_DRAFT_PREFIX}:${tenantId}:${branchId}`;
const cartKeyFor=(productId:string,optionLabel?:string)=>`${productId}::${optionLabel||"base"}`;
const money=(value:number)=>new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(value||0);

export function PosClientPro(){
  const[db,setDb]=useState<ReturnType<typeof loadLocalDatabase>|null>(null);
  const[cart,setCart]=useState<CartLine[]>([]);
  const[query,setQuery]=useState("");
  const[payment,setPayment]=useState<Payment>("cash");
  const[customerId,setCustomerId]=useState("");
  const[message,setMessage]=useState("Listo para vender");
  const[category,setCategory]=useState("Todos");
  const[serviceMode,setServiceMode]=useState<ServiceMode>("counter");
  const[tableLabel,setTableLabel]=useState("");
  const[customerName,setCustomerName]=useState("");
  const[phone,setPhone]=useState("");
  const[address,setAddress]=useState("");
  const[orderNotes,setOrderNotes]=useState("");
  const[activeOrderId,setActiveOrderId]=useState("");
  const[lastSaleId,setLastSaleId]=useState("");
  const[draftReady,setDraftReady]=useState(false);
  const[pendingCombo,setPendingCombo]=useState<TenantProduct|null>(null);
  const[pendingComboFirstFlavor,setPendingComboFirstFlavor]=useState("");
  const[clearArmed,setClearArmed]=useState(false);
  const[creditQuery,setCreditQuery]=useState("");
  const[creditCreateOpen,setCreditCreateOpen]=useState(false);
  const[saleSuccess,setSaleSuccess]=useState<SaleSuccess|null>(null);
  const refresh=()=>setDb(loadLocalDatabase());

  useEffect(()=>{refresh();window.addEventListener(KIUBO_DATA_REFRESHED,refresh);return()=>window.removeEventListener(KIUBO_DATA_REFRESHED,refresh)},[]);
  useEffect(()=>{if(!clearArmed)return;const timer=window.setTimeout(()=>setClearArmed(false),2600);return()=>window.clearTimeout(timer)},[clearArmed]);
  useEffect(()=>{if(!saleSuccess)return;const timer=window.setTimeout(()=>setSaleSuccess(null),1700);return()=>window.clearTimeout(timer)},[saleSuccess]);

  useEffect(()=>{
    if(!db||draftReady)return;
    const workspace=getWorkspaceContext(db);if(!workspace.branchId)return;
    if(window.sessionStorage.getItem(CHECKOUT_KEY))return;
    const key=posDraftKey(workspace.tenantId,workspace.branchId),raw=window.localStorage.getItem(key);
    if(raw){try{
      const draft=JSON.parse(raw) as Partial<PosDraft>,lines:CartLine[]=[];
      for(const saved of draft.cart||[]){const product=db.tenantProducts.find(item=>item.id===saved.productId&&item.tenantId===workspace.tenantId&&item.branchId===workspace.branchId&&item.active),qty=Math.max(1,Math.floor(Number(saved.qty)||1));if(product)lines.push({...product,qty:product.trackStock===false?qty:Math.min(qty,Math.max(1,product.stock)),cartKey:cartKeyFor(product.id,saved.optionLabel),optionLabel:saved.optionLabel})}
      setCart(lines);setQuery(typeof draft.query==="string"?draft.query:"");if(draft.payment&&paymentOptions.includes(draft.payment))setPayment(draft.payment);setCustomerId(typeof draft.customerId==="string"?draft.customerId:"");setCategory(typeof draft.category==="string"&&draft.category?draft.category:"Todos");if(draft.serviceMode)setServiceMode(draft.serviceMode);setTableLabel(typeof draft.tableLabel==="string"?draft.tableLabel:"");setCustomerName(typeof draft.customerName==="string"?draft.customerName:"");setPhone(typeof draft.phone==="string"?draft.phone:"");setAddress(typeof draft.address==="string"?draft.address:"");setOrderNotes(typeof draft.orderNotes==="string"?draft.orderNotes:"");setActiveOrderId(typeof draft.activeOrderId==="string"?draft.activeOrderId:"");if(lines.length)setMessage(`Venta recuperada · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`);
    }catch{window.localStorage.removeItem(key)}}
    setDraftReady(true);
  },[db,draftReady]);

  useEffect(()=>{
    if(!db)return;const orderId=window.sessionStorage.getItem(CHECKOUT_KEY);if(!orderId)return;window.sessionStorage.removeItem(CHECKOUT_KEY);
    const ctx=getWorkspaceContext(db),order=db.orders.find(item=>item.id===orderId&&item.tenantId===ctx.tenantId&&item.branchId===ctx.branchId);if(!order){setDraftReady(true);return}
    const lines:CartLine[]=[];for(const item of order.items){if(item.productId==="yuki-service-packaging")continue;const product=db.tenantProducts.find(p=>p.id===item.productId&&p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId&&p.active);if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes})}
    setCart(lines);setActiveOrderId(order.id);setServiceMode(order.serviceMode);setTableLabel(order.tableLabel||"");setCustomerId(order.customerId||"");setCustomerName(order.customerName||"");setPhone(order.phone||"");setAddress(order.address||"");setOrderNotes(order.notes||"");setMessage(`Pedido #${String(order.number).padStart(4,"0")} cargado para cobrar`);setDraftReady(true);
  },[db?.orders.length]);

  useEffect(()=>{
    if(!db||!draftReady)return;const workspace=getWorkspaceContext(db);if(!workspace.branchId)return;const key=posDraftKey(workspace.tenantId,workspace.branchId);
    const empty=cart.length===0&&!query.trim()&&payment==="cash"&&!customerId&&category==="Todos"&&serviceMode==="counter"&&!tableLabel.trim()&&!customerName.trim()&&!phone.trim()&&!address.trim()&&!orderNotes.trim()&&!activeOrderId;
    if(empty){window.localStorage.removeItem(key);return}
    const draft:PosDraft={cart:cart.map(line=>({productId:line.id,qty:line.qty,optionLabel:line.optionLabel})),query,payment,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId};window.localStorage.setItem(key,JSON.stringify(draft));
  },[db,draftReady,cart,query,payment,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId]);

  if(!db)return <div className="loading-card">Preparando POS…</div>;

  const ctx=getWorkspaceContext(db),tenant=ctx.tenant,branch=ctx.branch,settings=getTenantSettings(db,ctx.tenantId),foodService=settings.businessType==="food_service";
  const allProducts=db.tenantProducts.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===ctx.branchId&&p.active),packagingProduct=allProducts.find(product=>product.barcode===YUKI_PACKAGING_BARCODE),products=allProducts.filter(product=>product.barcode!==YUKI_PACKAGING_BARCODE);
  const customers:CustomerRecord[]=db.customers.filter(c=>c.tenantId===ctx.tenantId),categories=["Todos",...Array.from(new Set(products.map(product=>product.category||"General"))).sort((a,b)=>a.localeCompare(b,"es"))],filtered=products.filter(p=>(category==="Todos"||(p.category||"General")===category)&&`${p.name} ${p.barcode} ${p.price}`.toLowerCase().includes(query.toLowerCase()));
  const enabledModes:ServiceMode[]=foodService?(settings.serviceModes.length?settings.serviceModes:["table","takeaway","delivery"]):[],activeServiceMode:ServiceMode=foodService?(enabledModes.includes(serviceMode)?serviceMode:(enabledModes[0]||"counter")):serviceMode;
  const subtotal=cart.reduce((sum,line)=>sum+line.price*line.qty,0),packagingFee=foodService&&packagingProduct&&(activeServiceMode==="takeaway"||activeServiceMode==="delivery")?packagingProduct.price:0,total=subtotal+packagingFee,blocked=tenant?.status==="suspended",cartCount=cart.reduce((sum,line)=>sum+line.qty,0);
  const yogurtOptions=products.filter(product=>(product.category||"").toLowerCase()==="yogurts").map(product=>product.name.replace(/^yogurt\s+/i,"").trim()).filter(Boolean),openTableOrders=db.orders.filter(order=>order.tenantId===ctx.tenantId&&order.branchId===ctx.branchId&&order.serviceMode==="table"&&order.paymentStatus==="unpaid"&&order.status!=="cancelled"&&order.status!=="delivered"),tableNumbers=Array.from({length:Math.max(0,settings.tableCount||0)},(_,index)=>String(index+1));
  const normalizedCreditQuery=creditQuery.trim().toLowerCase(),customerBalance=(id:string)=>db.credits.filter(c=>c.tenantId===ctx.tenantId&&c.customerId===id&&c.status==="open").reduce((sum,c)=>sum+c.balance,0),creditMatches=normalizedCreditQuery?customers.filter(c=>`${c.name} ${c.identification} ${c.phone}`.toLowerCase().includes(normalizedCreditQuery)).slice(0,7):[],selectedCreditCustomer=customers.find(c=>c.id===customerId),previousBalance=selectedCreditCustomer?customerBalance(selectedCreditCustomer.id):0,estimatedBalance=previousBalance+total;
  const pendingComboYogurtCount=pendingCombo&&(pendingCombo.barcode==="YUKI-COMBO4"||/^combo\s*4$/i.test(pendingCombo.name.trim()))?2:1;

  const resetCustomer=()=>{setCustomerId("");setCustomerName("");setPhone("");setAddress("");setOrderNotes("");setCreditQuery("");setCreditCreateOpen(false)};
  const addDirect=(product:TenantProduct,optionLabel?:string)=>{if(product.trackStock!==false&&product.stock<=0){setMessage(`${product.name} sin stock`);return}const cartKey=cartKeyFor(product.id,optionLabel);setClearArmed(false);setCart(current=>{const found=current.find(line=>line.cartKey===cartKey);if(found){if(product.trackStock!==false&&found.qty>=product.stock){setMessage(`Stock máximo: ${product.stock}`);return current}return current.map(line=>line.cartKey===cartKey?{...line,qty:line.qty+1}:line)}return[...current,{...product,qty:1,cartKey,optionLabel}]});setMessage(`${product.name}${optionLabel?` · ${optionLabel}`:""} agregado`)};
  const add=(product:TenantProduct)=>{if(foodService&&(product.category||"").toLowerCase()==="combos"&&yogurtOptions.length){setPendingComboFirstFlavor("");setPendingCombo(product);return}addDirect(product)};
  const changeQty=(cartKey:string,delta:number)=>{setClearArmed(false);setCart(current=>current.map(line=>line.cartKey===cartKey?{...line,qty:line.trackStock===false?line.qty+delta:Math.min(line.stock,line.qty+delta)}:line).filter(line=>line.qty>0))};
  const removeLine=(cartKey:string)=>{setClearArmed(false);setCart(current=>current.filter(line=>line.cartKey!==cartKey));setMessage("Producto retirado del pedido")};
  const validateOrderDetails=()=>{if(!foodService)return true;if(activeServiceMode==="table"&&!tableLabel.trim()){setMessage("Selecciona una mesa para continuar");return false}if(activeServiceMode==="delivery"&&(!customerName.trim()||!phone.trim()||!address.trim())){setMessage("Para domicilio necesitamos nombre, teléfono y dirección");return false}return true};
  const orderItems=()=>[...cart.map(line=>({productId:line.id,name:line.optionLabel?`${line.name} · ${line.optionLabel}`:line.name,qty:line.qty,unitPrice:line.price,notes:line.optionLabel})),...(packagingFee&&packagingProduct?[{productId:packagingProduct.id,name:"Envase",qty:1,unitPrice:packagingFee}]:[])];
  const buildOrder=(next:ReturnType<typeof loadLocalDatabase>,workspace:ReturnType<typeof getWorkspaceContext>,paymentStatus:"unpaid"|"paid",saleId?:string):FoodOrderRecord=>{const existing=activeOrderId?next.orders.find(order=>order.id===activeOrderId):undefined,now=new Date().toISOString();return{id:existing?.id||makeId("order"),tenantId:workspace.tenantId,branchId:workspace.branchId,number:existing?.number||nextOrderNumber(next,workspace.tenantId,workspace.branchId),serviceMode:activeServiceMode,tableLabel:tableLabel.trim()||undefined,customerId:customerId||undefined,customerName:customerName.trim()||customers.find(c=>c.id===customerId)?.name||undefined,phone:phone.trim()||undefined,address:address.trim()||undefined,notes:orderNotes.trim()||undefined,items:orderItems(),total:Number(total.toFixed(2)),status:existing?.status||"new",paymentStatus,saleId:saleId||existing?.saleId,createdBy:existing?.createdBy||workspace.user?.id,createdAt:existing?.createdAt||now,updatedAt:now}};
  const persistOrder=(next:ReturnType<typeof loadLocalDatabase>,order:FoodOrderRecord,queue=true)=>{const index=next.orders.findIndex(item=>item.id===order.id);if(index>=0)next.orders[index]=order;else next.orders.unshift(order);if(queue)queueFoodOrder(next,order)};
  const saveOrder=(silent=false)=>{if(!foodService||!cart.length){if(!silent)setMessage(cart.length?"Este perfil no usa pedidos":"Agrega productos al pedido");return null}if(!validateOrderDetails())return null;const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),order=buildOrder(next,workspace,"unpaid");persistOrder(next,order,true);saveLocalDatabase(next,{trackChanges:false});setDb(next);setActiveOrderId(order.id);if(!silent)setMessage(activeServiceMode==="table"?`Mesa ${tableLabel} guardada · puedes atender otra mesa`:`Pedido #${String(order.number).padStart(4,"0")} puesto en espera`);return order};
  const loadTableOrder=(label:string,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source),order=source.orders.find(item=>item.tenantId===workspace.tenantId&&item.branchId===workspace.branchId&&item.serviceMode==="table"&&item.tableLabel===label&&item.paymentStatus==="unpaid"&&item.status!=="cancelled"&&item.status!=="delivered");setServiceMode("table");setTableLabel(label);setQuery("");setCategory("Todos");setPayment("cash");setLastSaleId("");setClearArmed(false);if(!order){setCart([]);setActiveOrderId("");resetCustomer();setDb(source);setMessage(`Mesa ${label} · libre, lista para nuevo pedido`);return}const lines:CartLine[]=[];for(const item of order.items){if(item.productId===packagingProduct?.id)continue;const product=source.tenantProducts.find(p=>p.id===item.productId&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId&&p.active);if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes})}setCart(lines);setActiveOrderId(order.id);setCustomerId(order.customerId||"");setCustomerName(order.customerName||"");setPhone(order.phone||"");setAddress(order.address||"");setOrderNotes(order.notes||"");setDb(source);setMessage(`Mesa ${label} recuperada · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`)};
  const selectTable=(label:string)=>{if(activeServiceMode==="table"&&tableLabel&&tableLabel!==label&&cart.length){const saved=saveOrder(true);if(!saved)return;loadTableOrder(label,loadLocalDatabase());return}if(activeServiceMode!=="table"&&cart.length){setMessage("Cobra o pon en espera el pedido actual antes de cambiar a una mesa");return}loadTableOrder(label)};
  const changeServiceMode=(mode:ServiceMode)=>{if(mode===activeServiceMode)return;if(activeServiceMode==="table"&&tableLabel&&cart.length){const saved=saveOrder(true);if(!saved)return}setServiceMode(mode);setTableLabel("");setCart([]);setActiveOrderId("");setPayment("cash");resetCustomer();setClearArmed(false);setMessage(`${serviceLabel[mode]} · nuevo pedido`)};

  const clearCurrent=()=>{if(!cart.length)return;if(!clearArmed){setClearArmed(true);setMessage("¿Seguro? Toca «Limpiar pedido» otra vez para vaciarlo.");return}setClearArmed(false);setCart([]);setActiveOrderId("");resetCustomer();setLastSaleId("");setMessage(activeServiceMode==="table"&&tableLabel?`Mesa ${tableLabel} · pedido limpio`:"Pedido limpio · listo para vender")};
  const createCreditCustomer=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),identification=String(form.get("identification")||"").trim(),name=String(form.get("name")||"").trim(),phoneValue=String(form.get("phone")||"").trim();if(!identification||!name){setMessage("Para crear el cliente necesitamos cédula/RUC y nombre");return}const next=loadLocalDatabase();const existing=next.customers.find(c=>c.tenantId===ctx.tenantId&&c.identification===identification);if(existing){setCustomerId(existing.id);setCreditQuery(existing.name);setCreditCreateOpen(false);setMessage(`${existing.name} ya existía y quedó seleccionado`);return}const customer:CustomerRecord={id:makeId("customer"),tenantId:ctx.tenantId,identification,name,email:"",phone:phoneValue,address:"",createdAt:new Date().toISOString()};next.customers.unshift(customer);saveLocalDatabase(next);setDb(next);setCustomerId(customer.id);setCreditQuery(customer.name);setCreditCreateOpen(false);setMessage(`${customer.name} creado y seleccionado para fiado`)};

  const checkout=()=>{
    if(!cart.length){setMessage("Agrega al menos un producto");return}if(payment==="mixed"){setMessage("El pago mixto se habilitará cuando KIUBO pueda guardar el reparto exacto");return}if(!validateOrderDetails())return;
    const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),currentSettings=getTenantSettings(next,workspace.tenantId);if(workspace.tenant?.status==="suspended"){setMessage("La licencia está suspendida");return}if(!workspace.branchId){setMessage("Selecciona una sucursal");return}if(payment==="credit"&&!currentSettings.allowCredit){setMessage("El fiado está desactivado");return}if(payment==="credit"&&!customerId){setMessage("Busca y selecciona un cliente para registrar el fiado");return}if(payment==="cash"&&currentSettings.requireCashSession&&!getOpenCashSession(next,workspace.tenantId,workspace.branchId)){setMessage("Debes abrir caja en esta sucursal antes de cobrar");return}
    const grouped=new Map<string,{product:TenantProduct;qty:number;options:Map<string,number>}>();for(const line of cart){const current=next.tenantProducts.find(p=>p.id===line.id&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId);if(!current||(current.trackStock!==false&&current.stock<line.qty)){setMessage(`Revisa stock de ${line.name}`);refresh();return}const group=grouped.get(line.id)||{product:current,qty:0,options:new Map<string,number>()};group.qty+=line.qty;if(line.optionLabel)group.options.set(line.optionLabel,(group.options.get(line.optionLabel)||0)+line.qty);grouped.set(line.id,group)}if(packagingFee&&packagingProduct){const current=next.tenantProducts.find(p=>p.id===packagingProduct.id);if(current)grouped.set(current.id,{product:current,qty:1,options:new Map()})}
    const now=new Date().toISOString(),saleItems=[...grouped.values()].map(group=>{const optionText=[...group.options.entries()].map(([label,qty])=>`${label}${qty>1?` ×${qty}`:""}`).join(" / ");return{productId:group.product.id,name:optionText?`${group.product.name} · ${optionText}`:group.product.name,qty:group.qty,unitPrice:group.product.price,unitCost:group.product.cost}}),sale:SaleRecord={id:makeId("sale"),tenantId:workspace.tenantId,branchId:workspace.branchId,customerId:customerId||undefined,total:Number(total.toFixed(2)),payment,items:saleItems,createdAt:now};sale.clientOperationId=sale.id;
    let orderBefore:FoodOrderRecord|undefined,order:FoodOrderRecord|undefined;if(foodService){const existing=activeOrderId?next.orders.find(item=>item.id===activeOrderId):undefined;if(existing)orderBefore={...existing,items:existing.items.map(item=>({...item}))};order=buildOrder(next,workspace,"paid",sale.id);sale.orderId=order.id;persistOrder(next,order,false)}next.sales.unshift(sale);
    let credit:CreditRecord|undefined;if(payment==="credit"&&customerId){credit={id:makeId("credit"),tenantId:workspace.tenantId,branchId:workspace.branchId,customerId,saleId:sale.id,description:`Venta ${sale.id.slice(-8)}`,originalAmount:sale.total,balance:sale.total,status:"open",createdAt:now};next.credits.unshift(credit)}
    const stockMovements:StockMovementRecord[]=[],productSnapshots:TenantProduct[]=[];for(const item of saleItems){const current=next.tenantProducts.find(p=>p.id===item.productId)!;const previous=current.stock,newStock=previous-item.qty,movement:StockMovementRecord={id:makeId("stock"),tenantId:workspace.tenantId,branchId:workspace.branchId,productId:current.id,type:"sale",quantity:-item.qty,previousStock:previous,newStock,reference:sale.id,createdAt:now};movement.clientOperationId=movement.id;stockMovements.push(movement);next.stockMovements.unshift(movement);current.stock=newStock;productSnapshots.push({...current})}
    enqueueSaleTransaction(next,{sale,productSnapshots,stockMovements,credit,orderBefore,orderAfter:order});saveLocalDatabase(next,{trackChanges:false});window.localStorage.removeItem(posDraftKey(workspace.tenantId,workspace.branchId));
    const saleContext=tableLabel?`Mesa ${tableLabel}`:activeServiceMode==="delivery"?"Domicilio":activeServiceMode==="takeaway"?"Para llevar":"Venta";setDb(next);setCart([]);setQuery("");setPayment("cash");resetCustomer();setActiveOrderId("");setLastSaleId(sale.id);setClearArmed(false);setSaleSuccess({amount:sale.total,method:paymentLabel[payment],context:saleContext});setMessage(`Venta guardada · ${paymentLabel[payment]} · ${money(sale.total)}${tableLabel?` · Mesa ${tableLabel}`:""}`);
  };

  if(blocked)return <div className="license-block"><div className="hero-mini">K</div><span className="eyebrow">LICENCIA SUSPENDIDA</span><h2>{tenant?.name??"Este negocio"} está en modo consulta.</h2><p>No se borra información ni se permiten nuevas ventas hasta reactivar la licencia desde KIUBO Control.</p></div>;

  return <>
    <div className="workspace-banner pos-workspace-banner"><div><span>NEGOCIO</span><strong>{tenant?.name??"Negocio"}</strong></div><div><span>SUCURSAL</span><strong>{branch?.code} · {branch?.name}</strong></div><div><span>ESTADO</span><strong>{message}</strong></div></div>
    <div className="pos-grid restaurant-pos-grid"><section className="pos-products">{foodService&&<><div className="service-mode-bar">{enabledModes.map(mode=><button key={mode} className={activeServiceMode===mode?"selected":""} onClick={()=>changeServiceMode(mode)}>{serviceLabel[mode]}</button>)}</div>{activeServiceMode==="table"&&<div className="table-selector"><div className="table-selector-head"><span>MESAS</span><small>Selecciona una mesa. Al cambiar, el pedido actual queda en espera automáticamente.</small></div><div className="table-selector-grid">{tableNumbers.map(label=>{const open=openTableOrders.find(order=>order.tableLabel===label),active=tableLabel===label;return <button key={label} className={`${open?"occupied":"free"} ${active?"active":""}`} onClick={()=>selectTable(label)}><strong>Mesa {label}</strong><span>{open?`${open.items.reduce((sum,item)=>sum+item.qty,0)} prod. · ${money(open.total)}`:"Libre"}</span></button>})}</div></div>}<div className="category-strip">{categories.map(item=><button key={item} className={category===item?"selected":""} onClick={()=>setCategory(item)}>{item}</button>)}</div></>}
      <div className="pos-search-row"><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto…"/><button className={`pos-clear-order ${clearArmed?"armed":""}`} onClick={clearCurrent} disabled={!cart.length}>{clearArmed?"¿Seguro? Toca otra vez":"✕ Limpiar pedido"}</button></div>
      <div className="product-results">{filtered.length?filtered.map(product=><button className="pos-product" key={product.id} onClick={()=>add(product)}><div className="product-icon">{product.imageUrl?<img src={product.imageUrl} alt="" loading="lazy"/>:product.name.charAt(0)}</div><div><strong>{product.name}</strong><span>{product.trackStock===false?(product.category||"Elaborado"):`${product.category||product.barcode} · Stock ${product.stock}`}</span><b>{money(product.price)}</b></div></button>):<p className="empty-cart">No encontramos productos en esta categoría.</p>}</div></section>
      <aside className="cart-panel restaurant-checkout pro-checkout"><div className="cart-head pro-cart-head"><div><span className="eyebrow">{activeServiceMode==="table"&&tableLabel?`MESA ${tableLabel}`:foodService?activeOrderId?"PEDIDO CARGADO":"PEDIDO / VENTA":"VENTA ACTUAL"}</span><h2>{cartCount} {cartCount===1?"producto":"productos"}</h2></div>{activeServiceMode==="table"&&tableLabel&&<span className="checkout-table-state">{openTableOrders.some(order=>order.tableLabel===tableLabel)?"Pedido abierto":"Mesa activa"}</span>}</div>
      <div className="checkout-customer-block">{payment!=="credit"&&<select className="pos-customer-select" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Cliente opcional</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.identification}</option>)}</select>}
      {payment==="credit"&&<section className="credit-checkout"><div className="credit-title"><div><span>FIADO</span><strong>{selectedCreditCustomer?selectedCreditCustomer.name:"Selecciona un cliente"}</strong></div>{selectedCreditCustomer&&<button onClick={()=>{setCustomerId("");setCreditQuery("")}}>Cambiar</button>}</div>{!selectedCreditCustomer&&<><input className="search-input credit-search" value={creditQuery} onChange={e=>setCreditQuery(e.target.value)} placeholder="Nombre, cédula/RUC o teléfono…"/>{normalizedCreditQuery&&<div className="credit-results">{creditMatches.map(c=><button key={c.id} onClick={()=>{setCustomerId(c.id);setCreditQuery(c.name);setCreditCreateOpen(false)}}><span><strong>{c.name}</strong><small>{c.identification}{c.phone?` · ${c.phone}`:""}</small></span><b>{customerBalance(c.id)>0?`Debe ${money(customerBalance(c.id))}`:"Sin saldo"}</b></button>)}{creditMatches.length===0&&<div className="credit-no-results">No encontramos coincidencias.</div>}</div>}<button className="credit-add-customer" onClick={()=>setCreditCreateOpen(value=>!value)}>＋ Agregar cliente aquí</button>{creditCreateOpen&&<form className="credit-create" onSubmit={createCreditCustomer}><input name="identification" placeholder="Cédula / RUC" required/><input name="name" placeholder="Nombre del cliente" required/><input name="phone" placeholder="Teléfono (opcional)"/><button type="submit">Crear y seleccionar</button></form>}</>}{selectedCreditCustomer&&<div className="credit-balance-card"><div><span>Saldo actual</span><strong>{money(previousBalance)}</strong></div><div><span>Esta venta</span><strong>+ {money(total)}</strong></div><div className="credit-estimated"><span>Nuevo saldo estimado</span><strong>{money(estimatedBalance)}</strong></div><small>Se guardará como un nuevo fiado y el saldo anterior se mantiene en el historial.</small></div>}</section>}
      {foodService&&<div className="checkout-fields">{activeServiceMode!=="table"&&<input className="search-input" value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Nombre del cliente (opcional)"/>}{activeServiceMode==="delivery"&&<><input className="search-input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Teléfono"/><input className="search-input" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Dirección de entrega"/></>}<div className="order-note-wrap"><span aria-hidden="true">✎</span><input className="search-input" value={orderNotes} onChange={e=>setOrderNotes(e.target.value)} placeholder="Agregar nota al pedido…"/></div></div>}</div>
      <div className="cart-lines pro-cart-lines">{cart.length===0?<div className="pro-empty-cart"><span>＋</span><strong>Pedido vacío</strong><small>Selecciona productos para comenzar.</small></div>:cart.map(line=><div className="cart-line interactive pro-cart-line" key={line.cartKey}><div className="cart-line-thumb">{line.imageUrl?<img src={line.imageUrl} alt=""/>:<span>{line.name.charAt(0)}</span>}</div><div className="cart-line-copy"><strong>{line.name}</strong>{line.optionLabel&&<em>{line.optionLabel}</em>}<span>{money(line.price)} c/u</span></div><div className="qty pro-qty"><button onClick={()=>changeQty(line.cartKey,-1)} aria-label={`Quitar uno de ${line.name}`}>−</button><b>{line.qty}</b><button onClick={()=>changeQty(line.cartKey,1)} aria-label={`Agregar uno de ${line.name}`}>＋</button></div><strong className="cart-line-total">{money(line.price*line.qty)}</strong><button className="cart-line-remove" onClick={()=>removeLine(line.cartKey)} aria-label={`Eliminar ${line.name} del pedido`}>×</button></div>)}</div>
      <div className="checkout-summary pro-checkout-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div>{packagingFee>0&&<div className="packaging-row"><span>Envase</span><b>+ {money(packagingFee)}</b></div>}<div className="cart-total"><span>TOTAL</span><strong>{money(total)}</strong></div></div>
      <div className="payment-grid pro-payment-grid">{paymentOptions.map(method=><button key={method} className={payment===method?"selected":""} onClick={()=>{setPayment(method);if(method!=="credit"){setCreditQuery("");setCreditCreateOpen(false)}}}>{paymentLabel[method]}</button>)}</div>
      <button className={`button primary checkout ${payment==="credit"?"credit-charge":""}`} onClick={checkout} disabled={!cart.length}>{payment==="credit"?`Fiar ${money(total)}`:`Cobrar ${money(total)}`}</button>{foodService&&<button className="button secondary checkout hold-order" aria-label="Guardar pedido sin cobrar" onClick={()=>saveOrder(false)} disabled={!cart.length}>{activeServiceMode==="table"&&tableLabel?`Poner Mesa ${tableLabel} en espera`:"Guardar pedido en espera"}</button>}{lastSaleId&&<a className="button secondary checkout customer-ticket-link" target="_blank" rel="noreferrer" href={`/receipt?sale=${encodeURIComponent(lastSaleId)}`}>Ticket para el cliente</a>}<p className="cart-note">Comanda para cocina y ticket del cliente se imprimen por separado.</p></aside></div>
    {pendingCombo&&<div className="combo-choice-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget){setPendingCombo(null);setPendingComboFirstFlavor("")}}}><section className="combo-choice" role="dialog" aria-modal="true" aria-label="Elegir sabor"><button className="combo-choice-close" onClick={()=>{setPendingCombo(null);setPendingComboFirstFlavor("")}}>×</button><span className="eyebrow">PERSONALIZAR COMBO</span><h3>{pendingCombo.name}</h3><p>{pendingComboYogurtCount===2?(pendingComboFirstFlavor?`Yogur 1: ${pendingComboFirstFlavor}. Ahora elige el sabor del Yogur 2.`:"Este combo incluye 2 yogures. Elige primero el sabor del Yogur 1."):"Elige el sabor para que caja y preparación sepan exactamente qué pidió el cliente."}</p><div className="combo-options">{yogurtOptions.map(option=><button key={option} onClick={()=>{if(pendingComboYogurtCount===2&&!pendingComboFirstFlavor){setPendingComboFirstFlavor(option);return}const label=pendingComboYogurtCount===2?`Yogur 1: ${pendingComboFirstFlavor||"Sin especificar"} · Yogur 2: ${option}`:`Yogur ${option}`;addDirect(pendingCombo,label);setPendingCombo(null);setPendingComboFirstFlavor("")}}>{pendingComboYogurtCount===2&&pendingComboFirstFlavor?`Yogur 2 · ${option}`:option}</button>)}<button className="neutral" onClick={()=>{if(pendingComboYogurtCount===2&&!pendingComboFirstFlavor){setPendingComboFirstFlavor("Sin especificar");return}const label=pendingComboYogurtCount===2?`Yogur 1: ${pendingComboFirstFlavor||"Sin especificar"} · Yogur 2: Sin especificar`:"Sin especificar";addDirect(pendingCombo,label);setPendingCombo(null);setPendingComboFirstFlavor("")}}>Sin especificar</button>{pendingComboYogurtCount===2&&pendingComboFirstFlavor&&<button className="neutral" onClick={()=>setPendingComboFirstFlavor("")}>← Cambiar Yogur 1</button>}</div></section></div>}
    {saleSuccess&&<div className="pos-sale-success" role="status" aria-live="assertive"><div className="pos-sale-success-check">✓</div><div><strong>{saleSuccess.method==="Fiado"?"Fiado registrado":"Venta cobrada"}</strong><span>{money(saleSuccess.amount)} · {saleSuccess.method} · {saleSuccess.context}</span></div></div>}
  </>;
}
