"use client";

import { useEffect,useState } from "react";
import { FoodOrderRecord,SaleRecord,getTenantBranding,getTenantSettings,getWorkspaceContext,loadLocalDatabase } from "@/lib/local-store";

const money=(value:number)=>new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(value||0);
const paymentLabel:Record<SaleRecord["payment"],string>={cash:"Efectivo",transfer:"Transferencia",mixed:"Mixto",credit:"Fiado / crédito"};
const modeLabel:Record<FoodOrderRecord["serviceMode"],string>={counter:"Mostrador",table:"Local",takeaway:"Para llevar",delivery:"Domicilio"};

export function ReceiptClient(){
  const[data,setData]=useState<null|{sale:SaleRecord;order?:FoodOrderRecord;business:string;logo:string;address:string;phone:string;footer:string;width:"58mm"|"80mm"}>(null);
  useEffect(()=>{
    const saleId=new URLSearchParams(window.location.search).get("sale")||"",db=loadLocalDatabase(),ctx=getWorkspaceContext(db),sale=db.sales.find(item=>item.id===saleId&&item.tenantId===ctx.tenantId&&item.branchId===ctx.branchId);if(!sale)return;
    const settings=getTenantSettings(db,ctx.tenantId),branding=getTenantBranding(db,ctx.tenantId),order=sale.orderId?db.orders.find(item=>item.id===sale.orderId):undefined;
    setData({sale,order,business:branding.businessName||settings.tradeName||ctx.tenant?.name||"Negocio",logo:branding.logoUrl||"",address:settings.address,phone:settings.phone,footer:branding.receiptTagline||settings.receiptFooter,width:settings.receiptWidth});
  },[]);
  if(!data)return <main style={{padding:32}}>No encontramos esa venta en este dispositivo.</main>;
  const {sale,order}=data,pageWidth=data.width==="58mm"?"54mm":"72mm";
  return <main className="receipt-page"><style>{`@page{size:${data.width} auto;margin:2mm}@media print{body{background:#fff!important}.no-print{display:none!important}.receipt-page{padding:0!important}.receipt{box-shadow:none!important;border:0!important}}body{margin:0;background:#f4f4f2;font-family:Arial,sans-serif}.receipt-page{min-height:100vh;display:grid;place-items:start center;padding:24px}.receipt{width:${pageWidth};background:#fff;color:#111;padding:4mm;box-sizing:border-box;box-shadow:0 8px 30px rgba(0,0,0,.08)}.brand{display:grid;justify-items:center;text-align:center;gap:3px}.brand img{max-width:44mm;max-height:18mm;object-fit:contain}.brand strong{font-size:17px}.brand span{font-size:9px}.rule{border-top:1px dashed #333;margin:9px 0}.meta{display:grid;gap:3px;font-size:10px}.items{display:grid;gap:6px}.item{display:grid;grid-template-columns:1fr auto;gap:8px;font-size:11px}.item b{display:block}.totals{display:grid;gap:5px;font-size:11px}.totals strong{font-size:17px}.row{display:flex;justify-content:space-between;gap:10px}.footer{text-align:center;font-size:10px;line-height:1.5}.powered{font-size:8px;opacity:.65;text-transform:uppercase;letter-spacing:.08em}.actions{width:${pageWidth};display:flex;gap:8px;margin-top:12px}.actions button{flex:1;padding:10px;border:0;border-radius:8px;background:#123f31;color:white;font-weight:800;cursor:pointer}`}</style><section className="receipt"><div className="brand">{data.logo&&<img src={data.logo} alt=""/>}<strong>{data.business}</strong>{data.address&&<span>{data.address}</span>}{data.phone&&<span>{data.phone}</span>}</div><div className="rule"/><div className="meta"><span><b>RECIBO / PEDIDO</b> · {sale.id.slice(-8).toUpperCase()}</span><span>{new Date(sale.createdAt).toLocaleString("es-EC")}</span>{order&&<span>{modeLabel[order.serviceMode]}{order.tableLabel?` · ${order.tableLabel}`:""}{order.customerName?` · ${order.customerName}`:""}</span>}</div><div className="rule"/><div className="items">{sale.items.map((item,index)=><div className="item" key={`${item.productId}-${index}`}><span><b>{item.qty} × {item.name}</b>{money(item.unitPrice)} c/u</span><strong>{money(item.qty*item.unitPrice)}</strong></div>)}</div><div className="rule"/><div className="totals"><div className="row"><span>TOTAL</span><strong>{money(sale.total)}</strong></div><div className="row"><span>Forma de pago</span><span>{paymentLabel[sale.payment]}</span></div></div><div className="rule"/><div className="footer"><strong>{data.footer||"Gracias por tu compra"}</strong><div className="powered">Gestionado con KIUBO</div><small>Este recibo no es un comprobante tributario electrónico.</small></div></section><div className="actions no-print"><button onClick={()=>window.print()}>Imprimir recibo</button><button onClick={()=>window.close()}>Cerrar</button></div></main>;
}
