"use client";

import { useEffect,useState } from "react";
import { SaleRecord,getTenantSettings,getWorkspaceContext,loadLocalDatabase,saveLocalDatabase } from "@/lib/local-store";
import { historyRecordVisibleAfterReset,saleVisibleAfterHistoryReset } from "@/lib/sale-adjustments";
import { salePaymentSummary } from "@/lib/order-payments";
import { reconcileCashSession } from "@/lib/cash-reconciliation";
import { reverseSaleLocally,saleLifecycle,type SaleWithLifecycle } from "@/lib/sale-reversal";
import { KIUBO_DATA_REFRESHED } from "./RealtimeSyncRuntime";
import styles from "./ReportsClientPro.module.css";

const label:Record<SaleRecord["payment"],string>={cash:"Efectivo",transfer:"Transferencia",mixed:"Mixto",credit:"Fiado"};
const money=(value:number)=>new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(value||0);
const localDate=(date=new Date())=>{const copy=new Date(date.getTime()-date.getTimezoneOffset()*60000);return copy.toISOString().slice(0,10)};
const dateOnly=(iso:string)=>iso.slice(0,10);

export function ReportsClientPro(){
  const[db,setDb]=useState<ReturnType<typeof loadLocalDatabase>|null>(null);
  const[from,setFrom]=useState("");const[to,setTo]=useState("");const[scope,setScope]=useState<"branch"|"tenant">("branch");
  const[voidSaleId,setVoidSaleId]=useState("");const[voidReason,setVoidReason]=useState("");const[actionMessage,setActionMessage]=useState("");
  const refresh=()=>setDb(loadLocalDatabase());
  useEffect(()=>{refresh();window.addEventListener(KIUBO_DATA_REFRESHED,refresh);return()=>window.removeEventListener(KIUBO_DATA_REFRESHED,refresh)},[]);
  if(!db)return <div className="loading-card">Preparando reportes…</div>;

  const ctx=getWorkspaceContext(db),settings=getTenantSettings(db,ctx.tenantId),canConsolidate=Boolean(ctx.user?.platformAdmin||ctx.user?.role==="owner"||ctx.user?.role==="admin"),canReverse=canConsolidate,effectiveScope=canConsolidate?scope:"branch";
  const inPeriod=(iso:string)=>{const day=dateOnly(iso);return(!from||day>=from)&&(!to||day<=to)},branchAllowed=(branchId:string)=>effectiveScope==="tenant"||branchId===ctx.branchId;
  const saleHistory=db.sales.filter(s=>s.tenantId===ctx.tenantId&&branchAllowed(s.branchId)&&saleVisibleAfterHistoryReset(s,settings)&&inPeriod(s.createdAt)),sales=saleHistory.filter(s=>saleLifecycle(s)==="completed");
  const purchases=db.purchases.filter(p=>p.tenantId===ctx.tenantId&&branchAllowed(p.branchId)&&p.status!=="cancelled"&&inPeriod(p.createdAt)),supplierPayments=db.supplierPayments.filter(p=>p.tenantId===ctx.tenantId&&branchAllowed(p.branchId)&&inPeriod(p.createdAt)),cashSessions=db.cashSessions.filter(s=>s.tenantId===ctx.tenantId&&branchAllowed(s.branchId)&&historyRecordVisibleAfterReset(s,settings)&&inPeriod(s.openedAt)),cashMovements=db.cashMovements.filter(m=>m.tenantId===ctx.tenantId&&branchAllowed(m.branchId)&&historyRecordVisibleAfterReset(m,settings)&&inPeriod(m.createdAt)),credits=db.credits.filter(c=>c.tenantId===ctx.tenantId&&branchAllowed(c.branchId)&&c.status==="open");
  const revenue=sales.reduce((sum,s)=>sum+s.total,0),avg=sales.length?revenue/sales.length:0;
  const soldItemRows=sales.flatMap(s=>s.items),missingCostLines=soldItemRows.filter(i=>Number(i.unitCost??db.tenantProducts.find(p=>p.id===i.productId)?.cost??0)<=0).length,cost=soldItemRows.reduce((sum,i)=>sum+i.qty*Number(i.unitCost??db.tenantProducts.find(p=>p.id===i.productId)?.cost??0),0),gross=revenue-cost,grossReliable=missingCostLines===0;
  const purchased=purchases.reduce((n,p)=>n+p.total,0),payable=purchases.reduce((n,p)=>n+Math.max(0,p.total-(p.paidAmount??0)),0),receivable=credits.reduce((n,c)=>n+c.balance,0),supplierPaid=supplierPayments.reduce((n,p)=>n+p.amount,0),cashNet=cashMovements.reduce((n,m)=>n+(m.type==="in"?m.amount:-m.amount),0),closedCash=cashSessions.filter(s=>s.status==="closed").length;
  const paymentTotals=(Object.keys(label) as SaleRecord["payment"][]).map(method=>({method,total:sales.filter(s=>s.payment===method).reduce((n,s)=>n+s.total,0)}));
  const topProducts=(()=>{const map=new Map<string,{name:string;qty:number;revenue:number}>();for(const sale of sales)for(const item of sale.items){const row=map.get(item.productId)||{name:item.name.replace(/ · .*/,""),qty:0,revenue:0};row.qty+=item.qty;row.revenue+=item.qty*item.unitPrice;map.set(item.productId,row)}return[...map.values()].sort((a,b)=>b.qty-a.qty).slice(0,6)})();
  const closedReconciliations=cashSessions.filter(s=>s.status==="closed").map(session=>({session,reconciliation:reconcileCashSession(db,session)})).sort((a,b)=>(b.session.closedAt??b.session.openedAt).localeCompare(a.session.closedAt??a.session.openedAt)),cashDifferenceTotal=closedReconciliations.reduce((sum,row)=>sum+(row.reconciliation.difference??0),0);
  const branches=db.branches.filter(b=>b.tenantId===ctx.tenantId&&b.active),branchSummary=branches.map(branch=>{const branchSales=db.sales.filter(s=>s.tenantId===ctx.tenantId&&s.branchId===branch.id&&saleVisibleAfterHistoryReset(s,settings)&&inPeriod(s.createdAt)&&saleLifecycle(s)==="completed"),branchPurchases=db.purchases.filter(p=>p.tenantId===ctx.tenantId&&p.branchId===branch.id&&p.status!=="cancelled"&&inPeriod(p.createdAt)),branchCredits=db.credits.filter(c=>c.tenantId===ctx.tenantId&&c.branchId===branch.id&&c.status==="open"),salesTotal=branchSales.reduce((n,s)=>n+s.total,0);return{branch,sales:branchSales.length,revenue:salesTotal,purchases:branchPurchases.reduce((n,p)=>n+p.total,0),payable:branchPurchases.reduce((n,p)=>n+Math.max(0,p.total-(p.paidAmount??0)),0),receivable:branchCredits.reduce((n,c)=>n+c.balance,0)}});

  const setPreset=(kind:"today"|"week"|"month"|"all")=>{const today=new Date();if(kind==="all"){setFrom("");setTo("");return}setTo(localDate(today));if(kind==="today")setFrom(localDate(today));if(kind==="week"){const start=new Date(today);start.setDate(start.getDate()-6);setFrom(localDate(start))}if(kind==="month")setFrom(localDate(new Date(today.getFullYear(),today.getMonth(),1)))};
  const confirmVoid=()=>{if(!voidSaleId)return;const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),sale=next.sales.find(s=>s.id===voidSaleId&&s.tenantId===workspace.tenantId);if(!sale){setActionMessage("La venta ya no está disponible en este dispositivo");setVoidSaleId("");return}const result=reverseSaleLocally(next,sale.id,voidReason);setActionMessage(result.message);if(!result.ok)return;saveLocalDatabase(next,{trackChanges:false});refresh();setVoidSaleId("");setVoidReason("")};

  return <div className={styles.page}>
    <section className={styles.context}><div><span>NEGOCIO</span><strong>{ctx.tenant?.name}</strong></div><div><span>VISTA</span><strong>{effectiveScope==="tenant"?"Consolidado":"Sucursal actual"}</strong></div><div><span>PERÍODO</span><strong>{from||to?`${from||"Inicio"} → ${to||"Hoy"}`:"Todo el historial"}</strong></div></section>
    <section className={styles.filters}><div className={styles.presets}><button onClick={()=>setPreset("today")}>Hoy</button><button onClick={()=>setPreset("week")}>7 días</button><button onClick={()=>setPreset("month")}>Este mes</button><button onClick={()=>setPreset("all")}>Todo</button></div><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{canConsolidate&&<label>Alcance<select value={scope} onChange={e=>setScope(e.target.value as "branch"|"tenant")}><option value="branch">Sucursal actual</option><option value="tenant">Todo el negocio</option></select></label>}</section>
    {actionMessage&&<div className={styles.notice}>{actionMessage}</div>}
    <section className={styles.metrics}><article><span>Ventas</span><strong>{money(revenue)}</strong><small>{sales.length} ventas válidas</small></article><article><span>Ticket promedio</span><strong>{money(avg)}</strong><small>Promedio por venta</small></article><article className={!grossReliable?styles.metricWarn:""}><span>Utilidad bruta</span><strong>{grossReliable?money(gross):"—"}</strong><small>{grossReliable?"Venta menos costo histórico":`${missingCostLines} líneas sin costo · completa costos para estimar`}</small></article><article><span>Por cobrar</span><strong>{money(receivable)}</strong><small>Fiados abiertos</small></article></section>
    <section className={styles.mainGrid}><article className={styles.panel}><header><div><span>PRODUCTOS</span><h2>Más vendidos</h2></div><b>{sales.length} ventas</b></header><div className={styles.topList}>{topProducts.length?topProducts.map((item,index)=><div key={`${item.name}-${index}`}><span className={styles.rank}>{index+1}</span><div><strong>{item.name}</strong><small>{item.qty} unidades · {money(item.revenue)}</small></div><div className={styles.bar}><i style={{width:`${Math.max(8,(item.qty/(topProducts[0]?.qty||1))*100)}%`}}/></div></div>):<div className={styles.empty}>No hay ventas en este período.</div>}</div></article><article className={styles.panel}><header><div><span>MEDIOS DE PAGO</span><h2>Cómo pagaron</h2></div></header><div className={styles.paymentList}>{paymentTotals.map(item=><div key={item.method}><span>{label[item.method]}</span><strong>{money(item.total)}</strong></div>)}</div></article></section>
    <section className={styles.opsGrid}><article className={styles.panel}><header><div><span>CAJA</span><h2>Control operativo</h2></div></header><div className={styles.paymentList}><div><span>Sesiones</span><strong>{cashSessions.length}</strong></div><div><span>Cajas cerradas</span><strong>{closedCash}</strong></div><div><span>Movimientos netos</span><strong>{money(cashNet)}</strong></div><div><span>Diferencia de cierres</span><strong>{money(cashDifferenceTotal)}</strong></div></div></article><article className={styles.panel}><header><div><span>COMPRAS</span><h2>Compromisos</h2></div></header><div className={styles.paymentList}><div><span>Comprado</span><strong>{money(purchased)}</strong></div><div><span>Por pagar</span><strong>{money(payable)}</strong></div><div><span>Pagado a proveedores</span><strong>{money(supplierPaid)}</strong></div><div><span>Fiados por cobrar</span><strong>{money(receivable)}</strong></div></div></article></section>
    {canConsolidate&&effectiveScope==="tenant"&&<section className={styles.panel}><header><div><span>SUCURSALES</span><h2>Comparativo</h2></div></header><div className={styles.branchTable}><div className={styles.branchHead}><span>Sucursal</span><span>Ventas</span><span>Ingresos</span><span>Compras</span><span>Por cobrar</span></div>{branchSummary.map(row=><div className={styles.branchRow} key={row.branch.id}><strong>{row.branch.code} · {row.branch.name}</strong><span>{row.sales}</span><span>{money(row.revenue)}</span><span>{money(row.purchases)}</span><span>{money(row.receivable)}</span></div>)}</div></section>}
    <section className={styles.panel}><header><div><span>HISTORIAL</span><h2>Ventas recientes</h2></div><b>{saleHistory.length}</b></header>{voidSaleId&&<div className={styles.voidBox}><strong>Anular venta</strong><p>La venta seguirá visible para auditoría. Si corresponde, KIUBO restaura stock y registra la devolución.</p><input value={voidReason} onChange={e=>setVoidReason(e.target.value)} placeholder="Motivo de anulación" maxLength={240}/><div><button onClick={confirmVoid}>Confirmar anulación</button><button onClick={()=>{setVoidSaleId("");setVoidReason("")}}>Cancelar</button></div></div>}<div className={styles.salesList}>{saleHistory.length===0?<div className={styles.empty}>No hay ventas para este filtro.</div>:saleHistory.slice(0,80).map(s=>{const lifecycle=saleLifecycle(s),details=s as SaleWithLifecycle,payment=salePaymentSummary(db,s),reversible=canReverse&&lifecycle==="completed"&&(s.payment==="cash"||s.payment==="transfer")&&(Date.now()-Date.parse(s.createdAt)<=24*60*60*1000);return <article className={styles.saleRow} key={s.id}><div className={styles.saleMain}><strong>{money(s.total)}</strong><span>{new Date(s.createdAt).toLocaleString("es-EC")}</span></div><span className={lifecycle==="voided"?styles.voided:styles.payBadge}>{lifecycle==="voided"?"ANULADA":payment.label}</span><div className={styles.saleDetails}><small>{s.items.map(i=>`${i.qty}× ${i.name}`).join(" · ")}</small>{lifecycle!=="voided"&&<div className={styles.paymentFacts}><span>Pagado <b>{money(payment.paid)}</b></span>{payment.cash>0&&<span>Efectivo <b>{money(payment.cash)}</b></span>}{payment.transfer>0&&<span>Transferencia <b>{money(payment.transfer)}</b></span>}{payment.balance>0&&<span className={styles.pendingFact}>Pendiente <b>{money(payment.balance)}</b></span>}</div>}{details.voidReason&&<small>Motivo: {details.voidReason}</small>}</div><div className={styles.saleActions}>{lifecycle!=="voided"&&<a href={`/receipt?sale=${encodeURIComponent(s.id)}`} target="_blank" rel="noreferrer">Ver / imprimir</a>}{reversible&&<button onClick={()=>{setVoidSaleId(s.id);setVoidReason("");setActionMessage("")}}>Anular</button>}</div></article>})}</div></section>
  </div>;
}