import { getTenantSettings,getWorkspaceContext,loadLocalDatabase,makeId } from "./local-store";
import type { SriEnvironment,SriTaxKind } from "./sri-engine";

export type SriConfig={tenantId:string;branchId:string;environment:SriEnvironment;ruc:string;legalName:string;tradeName:string;matrixAddress:string;establishmentAddress:string;establishmentCode:string;emissionPointCode:string;invoiceVersion:"2.1.0";pricesIncludeTax:true;accountingRequired:boolean;rimpe:"none"|"entrepreneur"|"popular";nextSequential:number;certificateLabel:string;certificateExpiresAt:string;certificateStatus:"unconfigured"|"metadata_only"|"server_ready";updatedAt:string};
export type SriProductTaxRecord={id:string;tenantId:string;productKey:string;kind:SriTaxKind;rate:number;percentageCode:string;label:string;verified:boolean;updatedAt:string};
export type SriInvoiceStatus="draft"|"ready_to_sign"|"signed"|"sent"|"authorized"|"rejected"|"error";
export type SriInvoiceRecord={id:string;tenantId:string;branchId:string;saleId:string;customerId?:string;environment:SriEnvironment;invoiceVersion:"2.1.0";establishmentCode:string;emissionPointCode:string;sequential:string;accessKey:string;numericCode:string;status:SriInvoiceStatus;buyer:{typeCode:string;identification:string;name:string;email?:string;address?:string};issuer:{ruc:string;legalName:string;tradeName:string;matrixAddress:string;establishmentAddress:string;accountingRequired:boolean;rimpe:SriConfig["rimpe"]};items:Array<{productId:string;productKey:string;name:string;qty:number;gross:number;taxKind:SriTaxKind;taxRate:number;percentageCode:string}>;taxes:Array<{kind:SriTaxKind;rate:number;percentageCode:string;base:number;tax:number}>;totalWithoutTax:number;taxAmount:number;total:number;payment:string;preflightVersion:string;createdAt:string;updatedAt:string;lastError?:string;authorizationDate?:string};
export type SriTransmissionAttempt={id:string;tenantId:string;invoiceId:string;stage:"sign"|"receive"|"authorize"|"notify";status:"pending"|"ok"|"error";attempt:number;message:string;createdAt:string};
type SriLocalStore={configs:SriConfig[];productTaxes:SriProductTaxRecord[];invoices:SriInvoiceRecord[];attempts:SriTransmissionAttempt[]};
const KEY="kiubo.sri.foundation.v2";
const LEGACY_KEY="kiubo.sri.foundation.v1";
const empty=():SriLocalStore=>({configs:[],productTaxes:[],invoices:[],attempts:[]});
function resolveBranch(tenantId:string,branchId?:string){if(branchId)return branchId;const db=loadLocalDatabase(),ctx=getWorkspaceContext(db);if(ctx.tenantId===tenantId&&ctx.branchId)return ctx.branchId;return db.branches.find(b=>b.tenantId===tenantId&&b.active)?.id??db.branches.find(b=>b.tenantId===tenantId)?.id??""}
function defaultConfig(tenantId:string,branchId:string):SriConfig{const db=loadLocalDatabase(),settings=getTenantSettings(db,tenantId),branch=db.branches.find(b=>b.id===branchId&&b.tenantId===tenantId),branchCode=branch?.code&&/^\d{3}$/.test(branch.code)?branch.code:settings.establishment||"001";return{tenantId,branchId,environment:"test",ruc:settings.ruc||"",legalName:settings.legalName||"",tradeName:settings.tradeName||db.tenants.find(t=>t.id===tenantId)?.name||"",matrixAddress:"",establishmentAddress:"",establishmentCode:branchCode,emissionPointCode:settings.emissionPoint||"001",invoiceVersion:"2.1.0",pricesIncludeTax:true,accountingRequired:false,rimpe:"none",nextSequential:1,certificateLabel:"",certificateExpiresAt:"",certificateStatus:"unconfigured",updatedAt:new Date(0).toISOString()}}
function normalizeStore(parsed:Partial<SriLocalStore>):SriLocalStore{return{configs:Array.isArray(parsed.configs)?parsed.configs.filter(c=>Boolean(c.tenantId&&c.branchId)):[],productTaxes:Array.isArray(parsed.productTaxes)?parsed.productTaxes:[],invoices:Array.isArray(parsed.invoices)?parsed.invoices:[],attempts:Array.isArray(parsed.attempts)?parsed.attempts:[]}}
export function loadSriStore():SriLocalStore{if(typeof window==="undefined")return empty();try{const raw=window.localStorage.getItem(KEY);if(raw)return normalizeStore(JSON.parse(raw) as Partial<SriLocalStore>);const legacy=window.localStorage.getItem(LEGACY_KEY);if(legacy){const parsed=JSON.parse(legacy) as Partial<SriLocalStore>,store=normalizeStore(parsed);window.localStorage.setItem(KEY,JSON.stringify(store));return store}return empty()}catch{return empty()}}
export function saveSriStore(store:SriLocalStore){if(typeof window!=="undefined")window.localStorage.setItem(KEY,JSON.stringify(store))}
export function getSriConfig(tenantId:string,branchId?:string){const resolved=resolveBranch(tenantId,branchId),store=loadSriStore();return store.configs.find(c=>c.tenantId===tenantId&&c.branchId===resolved)??defaultConfig(tenantId,resolved)}
export function saveSriConfig(config:SriConfig){const store=loadSriStore(),next={...config,updatedAt:new Date().toISOString()};store.configs=store.configs.filter(c=>!(c.tenantId===config.tenantId&&c.branchId===config.branchId));store.configs.push(next);saveSriStore(store);return next}
export function saveProductTax(input:Omit<SriProductTaxRecord,"id"|"updatedAt">){const store=loadSriStore(),existing=store.productTaxes.find(t=>t.tenantId===input.tenantId&&t.productKey===input.productKey),record:SriProductTaxRecord={...input,id:existing?.id??makeId("tax"),updatedAt:new Date().toISOString()};store.productTaxes=store.productTaxes.filter(t=>!(t.tenantId===input.tenantId&&t.productKey===input.productKey));store.productTaxes.push(record);saveSriStore(store);return record}
export function persistInvoice(invoice:SriInvoiceRecord,nextSequential:number){const store=loadSriStore();if(store.invoices.some(i=>i.tenantId===invoice.tenantId&&i.saleId===invoice.saleId))throw new Error("Esta venta ya tiene un borrador fiscal");const config=store.configs.find(c=>c.tenantId===invoice.tenantId&&c.branchId===invoice.branchId)??defaultConfig(invoice.tenantId,invoice.branchId);if(config.nextSequential!==nextSequential-1)throw new Error("El secuencial cambió; vuelve a generar el borrador");store.invoices.unshift(invoice);store.configs=store.configs.filter(c=>!(c.tenantId===invoice.tenantId&&c.branchId===invoice.branchId));store.configs.push({...config,nextSequential,updatedAt:new Date().toISOString()});saveSriStore(store);return invoice}
export function sriSnapshot(tenantId:string,branchId:string){const store=loadSriStore();return{config:store.configs.find(c=>c.tenantId===tenantId&&c.branchId===branchId)??defaultConfig(tenantId,branchId),taxes:store.productTaxes.filter(t=>t.tenantId===tenantId),invoices:store.invoices.filter(i=>i.tenantId===tenantId&&i.branchId===branchId),attempts:store.attempts.filter(a=>a.tenantId===tenantId)}}
