(() => {
  const config=window.KIUBO_CATALOG_CONFIG;if(!config?.apiUrl)return;
  const isPanel=/^\/(panel|master)(?:\/|$)/.test(location.pathname);
  const slug=(new URLSearchParams(location.search).get("slug")||location.pathname.match(/^\/c\/([^/]+)/)?.[1]||config.defaultSlug||"hakuna-matata").toLowerCase().replace(/[^a-z0-9-]/g,"");
  const nativeFetch=window.fetch.bind(window);const state={products:[],categories:[],activeBrand:"all",mode:"category",frame:0};
  const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const visible=()=>state.products.filter(p=>p.visible!==false&&!p.archived_at);const productById=id=>state.products.find(p=>String(p.id)===String(id));
  const categoryName=p=>state.categories.find(c=>String(c.id)===String(p?.category_id))?.name||p?.category_name||"Otros";
  const brands=()=>{const m=new Map();visible().forEach(p=>{const name=String(p.brand||"").trim();if(!name)return;const key=norm(name);if(!m.has(key))m.set(key,{key,name,count:0});m.get(key).count++});return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,"es",{sensitivity:"base"}))};
  function capture(action,payload){if(!payload||!["catalog_bootstrap","provider_bootstrap","master_bootstrap"].includes(action))return;if(Array.isArray(payload.products))state.products=payload.products;if(Array.isArray(payload.categories))state.categories=payload.categories;schedule()}
  window.fetch=async(input,init={})=>{const url=typeof input==="string"?input:input?.url||"";let action="";if(url===config.apiUrl&&typeof init?.body==="string")try{action=JSON.parse(init.body)?.action||""}catch{}const r=await nativeFetch(input,init);if(url===config.apiUrl&&action)try{capture(action,await r.clone().json())}catch{}return r};
  async function hydrate(){if(state.products.length)return;try{const action=isPanel?"provider_bootstrap":"catalog_bootstrap",headers={"Content-Type":"application/json","x-client-version":config.version||"4.7.0"};if(isPanel){const t=sessionStorage.getItem(`kiubo-provider-session:${slug}`);if(!t)return;headers["x-provider-session"]=t}const r=await nativeFetch(config.apiUrl,{method:"POST",headers,body:JSON.stringify({action,slug})});if(r.ok)capture(action,await r.json())}catch{}}
  function ensureControls(){if(isPanel)return;const cats=document.querySelector("#categoryScroller");if(!cats||document.querySelector("#catalogBrowseModes"))return;const wrap=document.createElement("div");wrap.id="catalogBrowseModes";wrap.className="catalog-browse-modes";wrap.innerHTML=`<div><strong>Explorar catálogo</strong><small>Ordenado por secciones</small></div><div class="catalog-browse-modes__switch" role="tablist"><button type="button" class="active" data-mode="category" aria-selected="true">Categorías</button><button type="button" data-mode="brand" aria-selected="false">Marcas</button></div>`;const brand=document.createElement("div");brand.id="brandScroller";brand.className="category-scroller brand-scroller";brand.hidden=true;cats.parentNode.insertBefore(wrap,cats);cats.parentNode.insertBefore(brand,cats.nextSibling);wrap.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>setMode(b.dataset.mode))}
  function renderBrands(){if(isPanel)return;const host=document.querySelector("#brandScroller");if(!host)return;const items=brands(),sig=state.activeBrand+"|"+items.map(x=>`${x.key}:${x.count}`).join("|");if(host.dataset.sig===sig)return;host.dataset.sig=sig;host.innerHTML=`<button class="category-chip ${state.activeBrand==="all"?"active":""}" data-brand="all">Todas</button>`+items.map(x=>`<button class="category-chip ${state.activeBrand===x.key?"active":""}" data-brand="${esc(x.key)}">${esc(x.name)} <small>${x.count}</small></button>`).join("");host.querySelectorAll("[data-brand]").forEach(b=>b.onclick=()=>{state.activeBrand=b.dataset.brand;renderBrands();applyBrandFilter()})}
  function setMode(mode){state.mode=mode;const cats=document.querySelector("#categoryScroller"),brand=document.querySelector("#brandScroller"),controls=document.querySelector("#catalogBrowseModes");if(!cats||!brand||!controls)return;controls.querySelectorAll("[data-mode]").forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle("active",on);b.setAttribute("aria-selected",String(on))});if(mode==="brand"){const all=cats.querySelector('[data-category="all"]');if(all&&!all.classList.contains("active"))all.click();cats.hidden=true;brand.hidden=false;renderBrands();applyBrandFilter()}else{state.activeBrand="all";cats.hidden=false;brand.hidden=true;restoreCards();groupByCategory()}}
  function restoreCards(){document.querySelectorAll("#productGrid .brand-filter-hidden").forEach(x=>{x.classList.remove("brand-filter-hidden");x.removeAttribute("aria-hidden")})}
  function ungroup(){const grid=document.querySelector("#productGrid");if(!grid)return;grid.querySelectorAll(":scope > .catalog-category-section").forEach(s=>{[...s.querySelectorAll(":scope > .catalog-category-products > [data-product-card]")].forEach(card=>grid.insertBefore(card,s));s.remove()});grid.classList.remove("category-sections")}
  function applyBrandFilter(){if(isPanel||state.mode!=="brand")return;ungroup();let count=0;document.querySelectorAll("#productGrid [data-product-card]").forEach(card=>{const p=productById(card.dataset.productCard),show=state.activeBrand==="all"||norm(p?.brand)===state.activeBrand;card.classList.toggle("brand-filter-hidden",!show);card.setAttribute("aria-hidden",String(!show));if(show)count++});const label=document.querySelector("#resultCount");if(label&&state.activeBrand!=="all"){const name=brands().find(x=>x.key===state.activeBrand)?.name||"Marca";label.textContent=`${count} producto${count===1?"":"s"} · ${name}`}}
  function groupByCategory(){if(isPanel||state.mode!=="category")return;const grid=document.querySelector("#productGrid");if(!grid||grid.getAttribute("aria-busy")==="true"||grid.querySelector(":scope > .catalog-category-section"))return;const cards=[...grid.querySelectorAll(":scope > [data-product-card]")];if(!cards.length)return;const groups=new Map();cards.forEach(card=>{const p=productById(card.dataset.productCard),name=categoryName(p),key=String(p?.category_id||name);if(!groups.has(key))groups.set(key,{name,cards:[]});groups.get(key).cards.push(card)});grid.classList.add("category-sections");groups.forEach(g=>{const s=document.createElement("section");s.className="catalog-category-section";s.innerHTML=`<header class="catalog-category-title"><div><span>SECCIÓN</span><h3>${esc(g.name)}</h3></div><small>${g.cards.length} producto${g.cards.length===1?"":"s"}</small></header><div class="catalog-category-products"></div>`;const host=s.querySelector(".catalog-category-products");g.cards.forEach(card=>host.append(card));grid.append(s)})}
  function decorateCards(){if(isPanel)return;document.querySelectorAll("#productGrid [data-product-card]").forEach(card=>{const p=productById(card.dataset.productCard),brand=String(p?.brand||"").trim(),cat=card.querySelector(".product-category");if(!cat)return;let mark=card.querySelector(".product-brand-mark");if(!brand){mark?.remove();return}if(!mark){mark=document.createElement("span");mark.className="product-brand-mark";cat.insertAdjacentElement("afterend",mark)}if(mark.textContent!==brand)mark.textContent=brand})}
  function panelTools(){if(!isPanel)return;const input=document.querySelector("#productBrand");if(!input)return;let list=document.querySelector("#productBrandSuggestions");if(!list){list=document.createElement("datalist");list.id="productBrandSuggestions";document.body.append(list);input.setAttribute("list",list.id);input.placeholder="Ej. Toni, Nestlé, Coca-Cola"}const items=brands(),sig=items.map(x=>`${x.key}:${x.count}`).join("|");if(list.dataset.sig!==sig){list.dataset.sig=sig;list.innerHTML=items.map(x=>`<option value="${esc(x.name)}"></option>`).join("")}const field=input.closest(".field")||input.parentElement;if(field&&!field.querySelector(".brand-field-help")){const h=document.createElement("small");h.className="brand-field-help";h.textContent="La marca ayuda a encontrar y organizar productos más rápido.";field.append(h)}}
  function enhance(){state.frame=0;if(isPanel){panelTools();return}ensureControls();renderBrands();decorateCards();if(state.mode==="category"){restoreCards();groupByCategory()}else applyBrandFilter()}
  function schedule(){if(!state.frame)state.frame=requestAnimationFrame(enhance)}const observer=new MutationObserver(schedule);const start=()=>{observer.observe(document.body,{childList:true,subtree:true});hydrate();schedule()};if(document.body)start();else document.addEventListener("DOMContentLoaded",start,{once:true});
})();
