(()=>{
'use strict';
if(window.__hakunaCatalog771)return;window.__hakunaCatalog771=true;
const C=window.KIUBO_CATALOG_CONFIG;if(!C?.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=n=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(n||0));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let data=null,dataPromise=null,batching=false,activeOverlay=null;
async function boot(force=false){if(data&&!force)return data;if(dataPromise&&!force)return dataPromise;dataPromise=fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version},body:JSON.stringify({action:'catalog_bootstrap',slug})}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b?.error||'bootstrap_failed');data=b;return b}).finally(()=>dataPromise=null);return dataPromise}
function product(id){return data?.products?.find(x=>String(x.id)===String(id))||null}
function presentations(id){return(data?.presentations||[]).filter(x=>String(x.product_id)===String(id)&&x.visible!==false).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0))}
function brands(){return[...new Set((data?.products||[]).filter(x=>x.visible!==false&&!x.archived_at).map(x=>String(x.brand||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function toast(msg,type=''){const e=document.createElement('div');e.className=`v77-toast ${type}`;e.textContent=msg;document.body.append(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),160)},1700)}
function lock(){document.documentElement.classList.add('v77-modal-open');document.body.classList.add('v77-modal-open')}
function unlock(){document.documentElement.classList.remove('v77-modal-open');document.body.classList.remove('v77-modal-open')}
function closeOverlay(){activeOverlay?.remove();activeOverlay=null;unlock()}

function decorateHome(){const home=$('#homeView .v7-home');if(!home)return;const hero=$('.v7-hero',home);if(hero&&!hero.dataset.v771){hero.dataset.v771='1';hero.classList.add('v77-hero');const art=$('.v7-hero-art',hero),copy=$('.v7-hero-copy',hero);if(art)art.innerHTML='<div class="v77-hero-visual"><span><b>1</b><small>Elige</small></span><i></i><span><b>2</b><small>Combina</small></span><i></i><span><b>3</b><small>Pide</small></span></div>';if(copy){const badge=$('span',copy),h=$('h1',copy),p=$('p',copy),btn=$('button',copy);if(badge)badge.textContent='CATÁLOGO MAYORISTA';if(h)h.textContent='Tu pedido, a tu manera.';if(p)p.textContent='Compra por unidad, caja, pack o jaba y arma todo en un solo carrito.';if(btn)btn.innerHTML='Explorar productos <svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>'}}const s=$('.v7-home-search span',home);if(s&&s.textContent!=='Buscar productos, marcas o categorías')s.textContent='Buscar productos, marcas o categorías'}
function tone(b){const n=norm(b);if(n.includes('coca-cola'))return'coke';if(n.includes('sprite'))return'sprite';if(n.includes('fanta'))return'fanta';if(n.includes('power'))return'power';if(n.includes('dasani'))return'dasani';if(n.includes('gatorade'))return'gatorade';if(n.includes('oreo'))return'oreo';if(n.includes('doritos'))return'doritos';return''}
function decorateCatalog(){const rail=$('#categoryRail');if(!rail||!data)return;const filter=$('#filterBtn');if(filter){const sp=$('span',filter);if(sp&&sp.textContent!=='Marcas')sp.textContent='Marcas';filter.setAttribute('aria-label','Filtrar por marca')}let box=$('#v77BrandRail');if(!box){box=document.createElement('section');box.id='v77BrandRail';box.className='v77-brand-section';rail.insertAdjacentElement('afterend',box)}const list=brands();const html=list.length?`<div class="v77-brand-head"><span>Marcas</span><small>Desliza para explorar</small></div><div class="v77-brand-rail"><button class="v77-brand-chip all" data-v771-brand=""><b>Todas</b></button>${list.map(b=>`<button class="v77-brand-chip ${tone(b)}" data-v771-brand="${esc(b)}"><span>${esc(b.slice(0,1).toUpperCase())}</span><b>${esc(b)}</b></button>`).join('')}</div>`:'';if(box.dataset.html!==html){box.dataset.html=html;box.innerHTML=html}$$('.v7-product[data-product]').forEach(card=>{const id=card.dataset.product,ps=presentations(id);card.classList.toggle('v77-multi',ps.length>1);let pill=$('.v77-options-pill',card);if(ps.length>1){if(!pill){pill=document.createElement('span');pill.className='v77-options-pill';pill.dataset.v771Choose=id;pill.setAttribute('role','button');pill.tabIndex=0;$('.v7-product-title',card)?.insertAdjacentElement('afterend',pill)}const label=ps.slice(0,2).map(x=>x.name).join(' + ')||`${ps.length} opciones`;if(pill.textContent!==label)pill.textContent=label;const add=$('[data-add]',card),sp=add&&$('span',add);if(sp&&sp.textContent!=='Elegir')sp.textContent='Elegir'}else pill?.remove()})}
function decorateDetail(){const sheet=$('.v7-sheet');if(!sheet||!data)return;const title=$('.v7-detail-body h2',sheet)?.textContent||'',p=(data.products||[]).find(x=>norm(x.name)===norm(title));if(!p)return;const ps=presentations(p.id);$$('[data-presentation]',sheet).forEach(btn=>{const pr=ps.find(x=>String(x.id)===String(btn.dataset.presentation));if(!pr||$('.v77-presentation-thumb',btn))return;const t=document.createElement('span');t.className='v77-presentation-thumb';const src=pr.image_url||p.image_url||'';t.innerHTML=src?`<img src="${esc(src)}" alt="">`:`<b>${esc((pr.name||'?').slice(0,1))}</b>`;btn.prepend(t)});$('.v75-presentation-help',sheet)?.remove();$('#noteToggle',sheet)?.remove();$('#noteBox',sheet)?.remove()}

function showChooser(id){const p=product(id),ps=presentations(id);if(!p||ps.length<2)return;closeOverlay();const o=document.createElement('div');o.className='v77-chooser';o.innerHTML=`<div class="v77-chooser-backdrop" data-v771-close></div><section><div class="v77-grab"></div><header><div><small>ELIGE CÓMO COMPRAR</small><h2>${esc(p.name)}</h2><p>Puedes combinar varias presentaciones en el mismo pedido.</p></div><button type="button" data-v771-close>×</button></header><div class="v77-choice-list">${ps.map(pr=>{const src=pr.image_url||p.image_url||'';return`<article><div class="v77-choice-photo">${src?`<img src="${esc(src)}" alt="${esc(pr.name)}">`:`<span>${esc((pr.name||'?').slice(0,1))}</span>`}</div><div class="v77-choice-copy"><b>${esc(pr.name)}</b><small>${Number(pr.units_per_presentation||1)} ${esc(p.base_unit||pr.unit_label||'unidad')}${Number(pr.units_per_presentation||1)===1?'':'es'}</small><strong>${money(pr.price)}</strong></div><div class="v77-choice-step"><button data-v771-dec="${esc(pr.id)}">−</button><b data-v771-qty="${esc(pr.id)}">0</b><button data-v771-inc="${esc(pr.id)}">+</button></div></article>`}).join('')}</div><footer><div><small>Total a agregar</small><strong id="v771Total">$0,00</strong></div><button id="v771Add" disabled>Agregar al carrito</button></footer></section>`;document.body.append(o);activeOverlay=o;lock();requestAnimationFrame(()=>o.classList.add('show'));const q=new Map(ps.map(x=>[String(x.id),0]));const refresh=()=>{let total=0,count=0;ps.forEach(pr=>{const n=q.get(String(pr.id))||0;count+=n;total+=n*Number(pr.price||0);const el=$(`[data-v771-qty="${CSS.escape(String(pr.id))}"]`,o);if(el)el.textContent=n});$('#v771Total',o).textContent=money(total);const b=$('#v771Add',o);b.disabled=!count;b.textContent=count?`Agregar ${count} ${count===1?'selección':'selecciones'}`:'Agregar al carrito'};o.addEventListener('click',e=>{if(e.target.closest?.('[data-v771-close]'))return closeOverlay();const inc=e.target.closest?.('[data-v771-inc]'),dec=e.target.closest?.('[data-v771-dec]');if(inc){const k=inc.dataset.v771Inc;q.set(k,(q.get(k)||0)+1);refresh()}if(dec){const k=dec.dataset.v771Dec;q.set(k,Math.max(0,(q.get(k)||0)-1));refresh()}});$('#v771Add',o).onclick=async()=>{const sel=ps.map(pr=>({id:String(pr.id),qty:q.get(String(pr.id))||0})).filter(x=>x.qty>0);if(!sel.length)return;closeOverlay();await batchAdd(id,sel)};refresh()}
async function waitSheet(ms=1400){const st=Date.now();while(Date.now()-st<ms){const s=$('.v7-sheet');if(s&&$('[data-presentation]',s))return s;await sleep(20)}return null}
async function addViaBase(id,pid,qty){const card=$(`[data-product="${CSS.escape(String(id))}"]`),open=card&&$('[data-open]',card);if(!open)return false;open.click();const sheet=await waitSheet();if(!sheet)return false;const pb=$(`[data-presentation="${CSS.escape(String(pid))}"]`,sheet);pb?.click();const plus=$('#detailPlus',sheet),add=$('#detailAdd',sheet);for(let i=1;i<qty;i++)plus?.click();add?.click();await sleep(210);return true}
async function batchAdd(id,sel){if(batching)return;batching=true;document.documentElement.classList.add('v77-batching');let n=0;try{for(const s of sel)if(await addViaBase(id,s.id,s.qty))n+=s.qty}finally{document.documentElement.classList.remove('v77-batching');batching=false}if(n)toast(`${n} ${n===1?'selección agregada':'selecciones agregadas'}`)}
async function chooseBrand(name){$('#filterBtn')?.click();await sleep(45);const sheet=$('.v7-sheet');if(!sheet)return;const b=$$('[data-brand-option]',sheet).find(x=>norm(x.dataset.brandOption||'')===norm(name));b?.click()}

const historyKey=()=>`kiubo-v7-orders:${slug}`;
function history(){try{return JSON.parse(localStorage.getItem(historyKey())||'[]')}catch{return[]}}
function orderByNumber(n){return history().find(o=>String(o.order_number)===String(n))}
function decorateOrders(){$$('.v7-order').forEach(card=>{if(card.dataset.v771)return;card.dataset.v771='1';const o=orderByNumber($('h3',card)?.textContent?.trim());if(!o)return;const a=document.createElement('div');a.className='v77-order-actions';a.innerHTML=`<button data-v771-repeat="${esc(o.public_token)}">↻ Repetir</button>${['new','confirmed'].includes(String(o.status))?`<button class="danger" data-v771-cancel="${esc(o.public_token)}">Cancelar</button>`:''}`;card.append(a)})}
async function api(action,payload={}){const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version},body:JSON.stringify({action,slug,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(b.message||b.error||'request_failed');e.code=b.error;throw e}return b}
function cancelOrder(token){closeOverlay();const o=document.createElement('div');o.className='v77-cancel';o.innerHTML='<div class="v77-chooser-backdrop" data-v771-close></div><section><button class="v77-cancel-x" data-v771-close>×</button><span>¿CANCELAR PEDIDO?</span><h2>Cuéntanos por qué</h2><p>Podrás volver a pedir estos productos cuando quieras.</p><div class="v77-reasons"><button data-reason="Me equivoqué en el pedido">Me equivoqué</button><button data-reason="Quiero cambiar productos">Quiero cambiar productos</button><button data-reason="Ya no necesito el pedido">Ya no lo necesito</button><button data-reason="Otro motivo">Otro</button></div><button id="v771ConfirmCancel" disabled>Confirmar cancelación</button></section>';document.body.append(o);activeOverlay=o;lock();requestAnimationFrame(()=>o.classList.add('show'));let reason='';o.addEventListener('click',e=>{if(e.target.closest?.('[data-v771-close]'))return closeOverlay();const b=e.target.closest?.('[data-reason]');if(b){reason=b.dataset.reason;$$('[data-reason]',o).forEach(x=>x.classList.toggle('active',x===b));$('#v771ConfirmCancel',o).disabled=false}});$('#v771ConfirmCancel',o).onclick=async()=>{const b=$('#v771ConfirmCancel',o);b.disabled=true;b.textContent='Cancelando…';try{await api('customer_cancel_order',{public_token:token,reason});const h=history().map(x=>String(x.public_token)===String(token)?{...x,status:'cancelled',updated_at:new Date().toISOString(),cancellation_reason:reason}:x);localStorage.setItem(historyKey(),JSON.stringify(h));closeOverlay();$('#refreshOrders')?.click();toast('Pedido cancelado')}catch(err){b.disabled=false;b.textContent='Confirmar cancelación';toast(err.code==='cannot_cancel_status'?'Este pedido ya no puede cancelarse desde aquí.':'No pudimos cancelar el pedido','error')}}}
async function allCatalog(){document.querySelector('[data-view="catalog"]')?.click();await sleep(90);$('#clearSearch')?.click();$('#clearBrand')?.click();await sleep(55);const all=$('[data-category="all"]');if(all&&!all.classList.contains('active')){all.click();await sleep(80)}}
async function repeatOrder(token){const cover=document.createElement('div');cover.className='v77-working';cover.innerHTML='<div><i></i><b>Preparando tu carrito…</b><span>Estamos recuperando los productos del pedido.</span></div>';document.body.append(cover);lock();try{const{order}=await api('order_status',{public_token:token});if(!order?.items?.length)throw 0;await boot(true);await allCatalog();document.documentElement.classList.add('v77-batching');let missing=0;for(const item of order.items){const p=(data.products||[]).find(x=>norm(x.name)===norm(item.product_name));if(!p){missing++;continue}const ps=presentations(p.id),pr=ps.find(x=>norm(x.name)===norm(item.presentation_name))||ps.find(x=>Number(x.units_per_presentation||1)===Number(item.units_per_presentation||1))||ps[0];if(!pr||!$(`[data-product="${CSS.escape(String(p.id))}"]`)){missing++;continue}if(!(await addViaBase(p.id,pr.id,Math.max(1,Number(item.quantity||1)))))missing++}document.documentElement.classList.remove('v77-batching');cover.remove();unlock();document.querySelector('[data-view="cart"]')?.click();toast(missing?`Pedido recuperado · ${missing} producto${missing===1?'':'s'} no disponible${missing===1?'':'s'}`:'Pedido agregado al carrito',missing?'warn':'')}catch{document.documentElement.classList.remove('v77-batching');cover.remove();unlock();toast('No pudimos repetir este pedido','error')}}
function suppress(node){if(node?.nodeType!==1)return;const arr=[node,...(node.querySelectorAll?.('.v7-toast')||[])];arr.forEach(e=>{if(e.matches?.('.v7-toast')&&/pedidos actualizados|agregado al carrito/i.test(e.textContent||''))e.remove()})}
function sync(){decorateHome();decorateCatalog();decorateDetail();decorateOrders()}
document.addEventListener('click',e=>{const add=e.target.closest?.('[data-add]');if(add&&!batching&&data&&presentations(add.dataset.add).length>1){e.preventDefault();e.stopImmediatePropagation();showChooser(add.dataset.add);return}const choose=e.target.closest?.('[data-v771-choose]');if(choose){e.preventDefault();e.stopPropagation();showChooser(choose.dataset.v771Choose);return}const brand=e.target.closest?.('[data-v771-brand]');if(brand){e.preventDefault();chooseBrand(brand.dataset.v771Brand||'');return}const rep=e.target.closest?.('[data-v771-repeat]');if(rep){e.preventDefault();repeatOrder(rep.dataset.v771Repeat);return}const can=e.target.closest?.('[data-v771-cancel]');if(can){e.preventDefault();cancelOrder(can.dataset.v771Cancel);return}},true);
const toastObs=new MutationObserver(rs=>{for(const r of rs)for(const n of r.addedNodes)suppress(n)});
function observe(sel){const el=$(sel);if(el)new MutationObserver(()=>requestAnimationFrame(sync)).observe(el,{childList:true})}
function start(){boot().then(sync).catch(()=>{});toastObs.observe(document.body,{childList:true});['#homeView','#catalogView','#ordersView','#sheetHost'].forEach(observe);sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();