/* Hakuna Matata Catalog 10.5.2 — delivery hardening, deterministic search routing and install guidance. */
(()=>{
'use strict';
if(window.__hakunaCatalog105)return;window.__hakunaCatalog105=true;
if(/^\/(?:panel|master|pedido)(?:\/|$)/.test(location.pathname))return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let installEvent=null,bootDone=false,searchTick=0,brandHinted=false,routingSearchBrand=false;
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
function toast(text){let el=$('.hm105-toast');if(!el){el=document.createElement('div');el.className='hm105-toast';document.body.append(el)}el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}
function finishBoot(){if(bootDone)return;const app=$('.v10-app');if(!app)return;bootDone=true;document.documentElement.classList.remove('hm105-boot');document.documentElement.classList.add('hm105-ready');}
function scheduleBoot(){requestAnimationFrame(()=>requestAnimationFrame(finishBoot))}
window.addEventListener('kiubo:brands-ready',scheduleBoot,{once:true});window.addEventListener('pageshow',scheduleBoot);setTimeout(scheduleBoot,420);setTimeout(scheduleBoot,900);

function brandNames(){const src=Array.isArray(window.KIUBO_BRAND_ORDERED)?window.KIUBO_BRAND_ORDERED:[];const seen=new Set(),out=[];for(const name of src){const n=norm(name);if(n&&!seen.has(n)){seen.add(n);out.push(name)}}return out}
function layoutSearchBox(){const box=$('#searchSuggestions'),input=$('#catalogSearch');if(!box||!input||box.hidden)return;const vv=window.visualViewport,rect=input.closest('.v102-search-wrap')?.getBoundingClientRect()||input.getBoundingClientRect(),vh=vv?.height||innerHeight,offset=vv?.offsetTop||0,top=Math.max(offset+8,Math.min(rect.bottom+8,offset+vh-120));box.style.setProperty('--hm-search-top',`${Math.round(top)}px`);box.style.setProperty('--hm-search-max',`${Math.max(120,Math.round(offset+vh-top-10))}px`)}
function enrichSearch(){searchTick=0;const view=$('#catalogView');if(!view?.classList.contains('active'))return;const input=$('#catalogSearch'),box=$('#searchSuggestions');if(!input||!box)return;const q=norm(input.value);view.classList.toggle('hm105-search-mode',!!q);if(!q){box.hidden=true;box.innerHTML='';box.classList.remove('hm105-results');box.style.removeProperty('--hm-search-top');box.style.removeProperty('--hm-search-max');return}
 const productButtons=$$('[data-search-product]',box).map(b=>b.outerHTML);const brands=brandNames().filter(b=>norm(b).includes(q)).slice(0,4);let html='';if(brands.length)html+=`<div class="hm105-search-label">MARCAS</div><div class="hm105-search-brands">${brands.map(b=>`<button type="button" data-brand-chip="${esc(b)}"><span>${esc(b)}</span><small>Ver toda la marca</small><b>›</b></button>`).join('')}</div>`;html+=`<div class="hm105-search-label">PRODUCTOS</div>`;html+=productButtons.length?`<div class="hm105-search-products">${productButtons.join('')}</div>`:`<div class="hm105-search-empty">No encontramos productos con “${esc(input.value.trim())}”.</div>`;box.innerHTML=html;box.hidden=false;box.classList.add('hm105-results');layoutSearchBox();}
function scheduleSearch(){if(searchTick)return;searchTick=requestAnimationFrame(()=>{searchTick=0;setTimeout(enrichSearch,0)})}
function hideSearchUi({clearInput=false}={}){const view=$('#catalogView'),input=$('#catalogSearch'),box=$('#searchSuggestions');view?.classList.remove('hm105-search-mode','hm1072-searching');if(clearInput&&input){input.value='';input.blur();input.dispatchEvent(new Event('input',{bubbles:true,composed:true}))}if(box){box.hidden=true;box.innerHTML='';box.classList.remove('hm105-results');box.style.removeProperty('--hm-search-top');box.style.removeProperty('--hm-search-max');box.dataset.hm1072Q=''}}
function selectBrandFromSearch(name){const wanted=norm(name);if(!wanted||routingSearchBrand)return;routingSearchBrand=true;document.documentElement.classList.add('hm105-brand-routing');hideSearchUi({clearInput:true});
 const finish=()=>{hideSearchUi();routingSearchBrand=false;document.documentElement.classList.remove('hm105-brand-routing');setTimeout(()=>{$('.v10-catalog-body')?.scrollIntoView({block:'start',behavior:'smooth'})},40)};
 const openBrandSheet=(attempt=0)=>{const filter=$('#filterBtn');if(!filter){if(attempt<12)return requestAnimationFrame(()=>openBrandSheet(attempt+1));finish();return}filter.click();let tries=0;const choose=()=>{const sheet=$('#sheetHost .v10-sheet'),option=sheet?$$('[data-brand-option]',sheet).find(b=>norm(b.dataset.brandOption||'')===wanted):null;if(option){if(typeof option.onclick==='function')option.onclick();else option.click();requestAnimationFrame(finish);return}if(tries++<12)return requestAnimationFrame(choose);$('#sheetHost .v10-sheet-close')?.click();finish()};requestAnimationFrame(choose)};
 const normalizeCategory=()=>{const all=$('#catalogView [data-category="all"]');if(all&&!all.classList.contains('active')){all.click();requestAnimationFrame(()=>requestAnimationFrame(()=>openBrandSheet()))}else openBrandSheet()};
 requestAnimationFrame(()=>requestAnimationFrame(normalizeCategory));}
document.addEventListener('input',e=>{if(e.target?.id==='catalogSearch')scheduleSearch()},true);
document.addEventListener('search',e=>{if(e.target?.id==='catalogSearch')scheduleSearch()},true);
document.addEventListener('focusin',e=>{if(e.target?.id==='catalogSearch')scheduleSearch()},true);
document.addEventListener('click',e=>{const brandResult=e.target.closest?.('#searchSuggestions [data-hm-search-brand],#searchSuggestions [data-brand-chip]');if(brandResult){const name=String(brandResult.dataset.hmSearchBrand??brandResult.dataset.brandChip??'').trim();if(name){e.preventDefault();e.stopImmediatePropagation();selectBrandFromSearch(name);return}}
 const result=e.target.closest?.('#searchSuggestions [data-search-product]');if(result){e.preventDefault();e.stopImmediatePropagation();const id=String(result.dataset.searchProduct||''),input=$('#catalogSearch');if(input){input.value='';input.dispatchEvent(new Event('input',{bubbles:true,composed:true}))}setTimeout(()=>{const target=$(`#catalogResults [data-open="${CSS.escape(id)}"]`);target?.click()},150);return}if($('#catalogSearch')?.value?.trim())setTimeout(enrichSearch,0)},true);
window.visualViewport?.addEventListener('resize',layoutSearchBox,{passive:true});window.visualViewport?.addEventListener('scroll',layoutSearchBox,{passive:true});

function polishHeroActions(){const hero=$('#homeView .hm-hero-carousel');if(!hero)return;$$('.hm-hero-copy button',hero).forEach(btn=>{if(btn.dataset.hm105)return;btn.dataset.hm105='1';const t=norm(btn.textContent);if(t.includes('marca')&&!btn.dataset.hmOpenBrands)btn.dataset.hmOpenBrands='1';if((t.includes('catalog')||t.includes('explorar'))&&!btn.dataset.view)btn.dataset.view='catalog'})}
function hintBrandsOnUse(){const rail=$('.hm-v104-catalog-brands'),btn=$('#filterBtn');if(!rail||!btn||rail.dataset.hm105HintBound)return;rail.dataset.hm105HintBound='1';rail.addEventListener('scroll',()=>{if(brandHinted||rail.scrollLeft<85)return;brandHinted=true;btn.classList.add('hm105-brand-hint');setTimeout(()=>btn.classList.remove('hm105-brand-hint'),1450)},{passive:true})}
function ensureInstallCoach(){if(standalone()){$('.hm105-install-card')?.remove();return}const home=$('#homeView .v10-home');if(!home||$('.hm105-install-card',home))return;const search=$('.v10-home-search',home);if(!search)return;const card=document.createElement('section');card.className='hm105-install-card';card.innerHTML='<div><span>📲</span><p><b>Ten Hakuna como app</b><small>Instálala para abrir el catálogo más rápido.</small></p></div><div><button type="button" data-hm105-install>Instalar</button><button type="button" class="hm105-install-close" aria-label="Ocultar">×</button></div>';search.insertAdjacentElement('afterend',card);$('.hm105-install-close',card).onclick=()=>{card.remove();sessionStorage.setItem('hm105-install-hidden','1')};if(sessionStorage.getItem('hm105-install-hidden')==='1')card.remove()}
async function installApp(){if(standalone())return;if(installEvent){try{installEvent.prompt();await installEvent.userChoice}catch{}installEvent=null;$('.hm105-install-card')?.remove();return}if(isIOS())toast('En Safari toca Compartir y luego “Agregar a inicio”.');else toast('En el menú del navegador elige “Instalar aplicación” o “Agregar a pantalla principal”.')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;setTimeout(ensureInstallCoach,40)});window.addEventListener('appinstalled',()=>{$('.hm105-install-card')?.remove();toast('Hakuna Matata ya está instalada ✨')});
document.addEventListener('click',e=>{if(e.target.closest?.('[data-hm105-install]')){e.preventDefault();installApp()}},true);

function enhance(){polishHeroActions();hintBrandsOnUse();ensureInstallCoach();if($('#catalogSearch')?.value?.trim())scheduleSearch();document.documentElement.dataset.hmCatalog='10.5.2'}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('kiubo:brands-ready',schedule);window.addEventListener('pageshow',schedule);document.addEventListener('click',schedule,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
