(()=>{
'use strict';
if(window.__kiuboCatalog80)return;window.__kiuboCatalog80=true;
const C=window.KIUBO_CATALOG_CONFIG||{};if(!C.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const META_RE=/\s*\[\[KIUBO_PI:([A-Za-z0-9_-]+)\]\]\s*$/;
let data=null,bootPromise=null,enhanceRaf=0;
function b64d(s){try{const v=String(s||''),raw=atob(v.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((v.length+3)%4)),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch{return{}}}
function parsedDescription(value=''){const src=String(value||''),m=src.match(META_RE);return{text:(m?src.slice(0,m.index):src).trim(),images:m?b64d(m[1]):{}}}
async function boot(force=false){if(data&&!force)return data;if(bootPromise&&!force)return bootPromise;bootPromise=fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version||'8.0.0'},body:JSON.stringify({action:'catalog_bootstrap',slug})}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'bootstrap_failed');data=b;return b}).finally(()=>bootPromise=null);return bootPromise}
function products(){return(data?.products||[]).filter(p=>p.visible!==false&&!p.archived_at)}
function product(id){return products().find(p=>String(p.id)===String(id))||null}
function productByName(name){return products().find(p=>norm(p.name)===norm(name))||null}
function presentations(pid){return(data?.presentations||[]).filter(p=>String(p.product_id)===String(pid)&&p.visible!==false).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0))}
function presentationByName(pid,name){return presentations(pid).find(p=>norm(p.name)===norm(name))||null}
function metaFor(p,pr){if(!p||!pr)return null;const map=parsedDescription(p.description||'').images||{},id=String(pr.id||'');if(id&&map[id])return map[id];return Object.values(map).find(x=>norm(x?.n)===norm(pr.name)&&Number(x?.c||1)===Number(pr.units_per_presentation||1))||null}
function imageFor(p,pr){return pr?.image_url||metaFor(p,pr)?.u||p?.image_url||''}
function brandAssets(){return window.KIUBO_BRAND_ASSETS||{}}
function brandAsset(name){const map=brandAssets();return map[name]||map[norm(name)]||''}
function brands(){return[...new Set(products().map(p=>String(p.brand||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function activeBrand(){return $('.v7-active-filter b')?.textContent?.trim()||''}
function currentView(){return $('.v7-nav [data-view].active')?.dataset.view||'home'}
function later(ms=0){return new Promise(r=>setTimeout(r,ms))}
function brandTile(name,home=false){const asset=brandAsset(name),active=norm(activeBrand())===norm(name);return `<button type="button" class="k8-brand ${home?'home':''} ${active?'active':''}" data-k8-brand="${esc(name)}" aria-label="Ver ${esc(name)}"><span class="k8-brand-art">${asset?`<img src="${esc(asset)}" alt="${esc(name)}">`:`<em>${esc(name)}</em>`}</span></button>`}
function brandRailMarkup(home=false){const list=brands();return `<section class="${home?'k8-home-brands':'k8-catalog-brands'}"><header><div><small>MARCAS</small><h2>${home?'Compra por marca':'Explora por marca'}</h2></div><button type="button" data-k8-all-brands>Ver todas</button></header><div class="${home?'k8-home-brand-rail':'k8-brand-rail'}" data-k8-horizontal><button type="button" class="k8-brand all ${!activeBrand()?'active':''}" data-k8-brand=""><span class="k8-brand-art"><em>Todas</em></span></button>${list.map(b=>brandTile(b,home)).join('')}</div></section>`}
function decorateCard(card){const p=product(card.dataset.product);if(!p)return;const ps=presentations(p.id),add=$('[data-add]',card),label=add&&$('span',add);if(ps.length>1){card.classList.add('k8-multi');if(label)label.textContent='Elegir';let pill=$('.k8-presentations-pill',card);if(!pill){pill=document.createElement('span');pill.className='k8-presentations-pill';$('.v7-product-title p',card)?.insertAdjacentElement('afterend',pill)}pill.textContent=ps.slice(0,2).map(x=>x.name).join(' · ')}else{card.classList.remove('k8-multi');$('.k8-presentations-pill',card)?.remove()}}
function enhanceHome(){const home=$('#homeView .v7-home');if(!home||!data)return;const hero=$('.v7-hero',home),search=$('.v7-home-search',home);if(hero){hero.classList.add('k8-hero');const copy=$('.v7-hero-copy',hero),art=$('.v7-hero-art',hero);if(copy&&!$('.k8-hero-tags',copy))copy.insertAdjacentHTML('beforeend','<div class="k8-hero-tags"><span>Unidad</span><span>Caja</span><span>Jaba</span><span>Pedido fácil</span></div>');if(art&&!$('.k8-orbit',art))art.insertAdjacentHTML('beforeend','<div class="k8-orbit" aria-hidden="true"><i></i><i></i><i></i></div>')}let sec=$('.k8-home-brands',home);if(!sec){const firstBlock=$('.v7-block',home);if(firstBlock)firstBlock.insertAdjacentHTML('beforebegin',brandRailMarkup(true));else search?.insertAdjacentHTML('afterend',brandRailMarkup(true));sec=$('.k8-home-brands',home)}$$('.v7-product[data-product]',home).forEach(decorateCard);const strip=$('.v7-product-strip',home);if(strip)setupCarousel(strip);$$('.v7-home-points',home).forEach(x=>x.remove())}
function enhanceCatalog(){const view=$('#catalogView');if(!view||!data)return;const filter=$('#filterBtn',view);if(filter){const s=$('span',filter);if(s)s.textContent='Marcas';filter.setAttribute('aria-label','Filtrar por marca')}const rail=$('#categoryRail',view);rail?.setAttribute('data-k8-horizontal','');const body=$('.v7-catalog-body',view);if(body&&!$('.k8-catalog-brands',body)){const grid=$('.v7-product-grid',body);if(grid)grid.insertAdjacentHTML('beforebegin',brandRailMarkup(false))}$$('.v7-product[data-product]',view).forEach(decorateCard)}
function enhanceDetail(){const sheet=$('.v7-sheet .v7-detail');if(!sheet||!data)return;const title=$('.v7-detail-body h2',sheet)?.textContent||'',p=productByName(title);if(!p)return;const parsed=parsedDescription(p.description||''),desc=$('.v7-detail-body>p',sheet);if(desc){if(parsed.text)desc.textContent=parsed.text;else desc.remove()}const buttons=$$('.v7-presentation-list [data-presentation]',sheet);buttons.forEach(btn=>{const pr=presentations(p.id).find(x=>String(x.id)===String(btn.dataset.presentation))||presentationByName(p.id,$('b',btn)?.textContent||''),src=imageFor(p,pr);let thumb=$('.k8-presentation-thumb',btn);if(!thumb){thumb=document.createElement('span');thumb.className='k8-presentation-thumb';btn.prepend(thumb)}thumb.innerHTML=src?`<img src="${esc(src)}" alt="">`:'<i>•</i>'});const active=$('.v7-presentation-list [data-presentation].active',sheet)||buttons[0],pr=active&&presentations(p.id).find(x=>String(x.id)===String(active.dataset.presentation)),src=imageFor(p,pr),hero=$('.v7-detail-media>img',sheet);if(hero&&src){hero.src=src;hero.classList.add('k8-contain')}}
function updateDetailImage(btn){const sheet=btn.closest('.v7-sheet'),title=$('.v7-detail-body h2',sheet)?.textContent||'',p=productByName(title);if(!p)return;const pr=presentations(p.id).find(x=>String(x.id)===String(btn.dataset.presentation)),src=imageFor(p,pr),hero=$('.v7-detail-media>img',sheet);if(hero&&src){hero.src=src;hero.classList.add('k8-contain')}}
function enhanceCart(){if(!data)return;$$('#cartView .v7-cart-line').forEach(line=>{const p=productByName($('h3',line)?.textContent||'');if(!p)return;const pr=presentationByName(p.id,$('p',line)?.textContent||''),src=imageFor(p,pr),box=$('.v7-cart-photo',line);if(!box||!src)return;let img=$('img',box);if(!img){box.innerHTML='<img alt="">';img=$('img',box)}if(img.getAttribute('src')!==src)img.setAttribute('src',src);img.classList.add('k8-contain')})}
async function chooseBrand(name){const catalogBtn=$('.v7-nav [data-view="catalog"]');if(currentView()!=='catalog'){catalogBtn?.click();await later(40)}const filter=$('#filterBtn');if(!filter)return;filter.click();let sheet=null;for(let i=0;i<20;i++){sheet=$('.v7-sheet .v7-brand-options');if(sheet)break;await later(15)}if(!sheet)return;const target=$$('[data-brand-option]',sheet).find(x=>norm(x.dataset.brandOption||'')===norm(name));(target||$('[data-brand-option=""]',sheet))?.click()}
function setupCarousel(strip){if(strip.dataset.k8Carousel==='1')return;const originals=[...strip.children].filter(el=>el.classList?.contains('v7-product'));if(originals.length<2)return;strip.dataset.k8Carousel='1';strip.classList.add('k8-carousel');const g1=document.createElement('div'),g2=document.createElement('div');g1.className='k8-carousel-group';g2.className='k8-carousel-group';originals.forEach(el=>g1.append(el));originals.forEach(el=>g2.append(el.cloneNode(true)));strip.innerHTML='';strip.append(g1,g2);let pointerId=null,sx=0,sy=0,mode='',resumeAt=0,last=performance.now();const width=()=>g1.getBoundingClientRect().width||0;const normalize=()=>{const w=width();if(!w)return;if(strip.scrollLeft>=w)strip.scrollLeft-=w;else if(strip.scrollLeft<0)strip.scrollLeft+=w};const tick=now=>{if(!strip.isConnected)return;const dt=Math.min(40,Math.max(0,now-last));last=now;if(document.visibilityState==='visible'&&currentView()==='home'&&mode!=='horizontal'&&now>=resumeAt){strip.scrollLeft+=dt*.022;normalize()}requestAnimationFrame(tick)};requestAnimationFrame(tick);strip.addEventListener('pointerdown',e=>{if(!e.isPrimary)return;pointerId=e.pointerId;sx=e.clientX;sy=e.clientY;mode=''}, {passive:true});strip.addEventListener('pointermove',e=>{if(e.pointerId!==pointerId||mode)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<7)return;mode=Math.abs(dx)>Math.abs(dy)*1.15?'horizontal':'vertical'}, {passive:true});const end=e=>{if(pointerId!==null&&e.pointerId!==undefined&&e.pointerId!==pointerId)return;if(mode==='horizontal'){normalize();resumeAt=performance.now()+110}pointerId=null;mode=''};strip.addEventListener('pointerup',end,{passive:true});strip.addEventListener('pointercancel',end,{passive:true});strip.addEventListener('wheel',e=>{if(Math.abs(e.deltaX)>Math.abs(e.deltaY)){resumeAt=performance.now()+450;setTimeout(normalize,80)}},{passive:true})}
function enhance(){enhanceRaf=0;if(!data)return;enhanceHome();enhanceCatalog();enhanceDetail();enhanceCart()}
function schedule(){if(enhanceRaf)return;enhanceRaf=requestAnimationFrame(enhance)}
function observe(id){const el=$(id);if(!el||el.dataset.k8Observed)return;el.dataset.k8Observed='1';new MutationObserver(schedule).observe(el,{childList:true,subtree:false})}
['touchstart','touchend','touchcancel'].forEach(type=>document.addEventListener(type,e=>{if(e.target.closest?.('[data-k8-horizontal],.k8-carousel'))e.stopPropagation()},{capture:true,passive:true}));
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-k8-brand]');if(b){e.preventDefault();e.stopPropagation();chooseBrand(b.dataset.k8Brand||'');return}const all=e.target.closest?.('[data-k8-all-brands]');if(all){e.preventDefault();e.stopPropagation();if(currentView()!=='catalog')$('.v7-nav [data-view="catalog"]')?.click();setTimeout(()=>$('#filterBtn')?.click(),35);return}},false);
document.addEventListener('click',e=>{const add=e.target.closest?.('[data-add]');if(!add||!data)return;const p=product(add.dataset.add);if(!p||presentations(p.id).length<2)return;e.preventDefault();e.stopImmediatePropagation();const card=add.closest('[data-product]'),open=card?.querySelector('[data-open]');open?.click()},true);
document.addEventListener('click',e=>{const p=e.target.closest?.('[data-presentation]');if(p)setTimeout(()=>updateDetailImage(p),0)},false);
function start(){const ready=()=>{if(!$('#homeView'))return setTimeout(ready,30);boot().then(()=>{['#homeView','#catalogView','#cartView','#sheetHost'].forEach(observe);schedule()}).catch(()=>{})};ready()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
