/* Hakuna Matata Catalog 10.4.3 — native motion, faithful hero state and stable brand UX. */
(()=>{
'use strict';
if(window.__hakunaCatalog1043)return;window.__hakunaCatalog1043=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const compact=v=>norm(v).replace(/[^a-z0-9]+/g,'');
const key=v=>norm(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const themes={'coca-cola':['#fff','#e31d2b'],'toni':['#3157a2','#fff'],'bubbaloo':['#fff','#144287'],'chiclets':['#ffd72d','#111'],'cheese-tris':['#ff7b1b','#174d93'],'club-social':['#0d4c8e','#fff'],'chiki':['#ef2937','#ffe21c']};
const assets=()=>window.KIUBO_BRAND_ASSETS||{};
function brandVisual(name){const k=key(name),url=assets()[k],t=themes[k]||['#f5f7f4','#294a37'];return url?`<span class="hm-brand-visual has-image"><img src="${esc(url)}" alt="${esc(name)}" loading="lazy" decoding="async"></span>`:`<span class="hm-brand-visual" style="--hm-brand-bg:${t[0]};--hm-brand-fg:${t[1]}"><b>${esc(name)}</b></span>`}
function selectedBrand(){return norm($('#activeFilterHost .v10-active-filter b')?.textContent||'')}
function homeBrandNames(){const out=[],seen=new Set();$$('#homeView .hm-brand-block [data-brand-chip]').forEach(b=>{const n=(b.dataset.brandChip||'').trim(),k=norm(n);if(n&&!seen.has(k)){seen.add(k);out.push(n)}});return out}
function allBrandNames(){const registry=Array.isArray(window.KIUBO_BRAND_ORDERED)?window.KIUBO_BRAND_ORDERED.filter(Boolean):[],source=registry.length?registry:homeBrandNames(),out=[],seen=new Set();for(const n of source){const k=norm(n);if(!k||seen.has(k))continue;seen.add(k);out.push(n)}return out}
let brandRailLeft=0,lastHint=0,hintTimer=0,railHintTimer=0;
function hintBrandButton(){const btn=$('#filterBtn'),now=Date.now();if(!btn||now-lastHint<9000)return;lastHint=now;btn.classList.remove('hm1043-brand-hint');void btn.offsetWidth;btn.classList.add('hm1043-brand-hint');clearTimeout(hintTimer);hintTimer=setTimeout(()=>btn.classList.remove('hm1043-brand-hint'),1200)}
function ensureCatalogBrands(){const shell=$('#catalogView .v10-catalog-head .v10-shell');if(!shell)return;const categories=$('.v10-category-rail',shell);if(!categories)return;let rail=$('.hm-v104-catalog-brands',shell);if(!rail){rail=document.createElement('div');rail.className='hm-v104-catalog-brands';rail.setAttribute('aria-label','Marcas del catálogo');categories.insertAdjacentElement('afterend',rail)}const names=allBrandNames();if(!names.length)return;const sig=names.map(norm).join('|'),expected=names.length+1,needsBuild=rail.dataset.hm1043Signature!==sig||$$('[data-brand-chip]',rail).length!==expected||!!$('.hm-v104-more',rail);if(needsBuild){const keep=brandRailLeft||rail.scrollLeft;rail.dataset.hm1043Signature=sig;rail.innerHTML=`<button type="button" class="hm1043-all" data-brand-chip="" aria-label="Ver todos los productos"><span>Todos</span></button>`+names.map(name=>`<button type="button" data-brand-chip="${esc(name)}" aria-label="Ver ${esc(name)}">${brandVisual(name)}</button>`).join('');requestAnimationFrame(()=>{rail.scrollLeft=keep})}if(!rail.dataset.hm1043Bound){rail.dataset.hm1043Bound='1';rail.addEventListener('scroll',()=>{brandRailLeft=rail.scrollLeft;if(rail.scrollLeft>42){clearTimeout(railHintTimer);railHintTimer=setTimeout(hintBrandButton,220)}},{passive:true})}const active=selectedBrand();$$('[data-brand-chip]',rail).forEach(btn=>btn.classList.toggle('active',active?norm(btn.dataset.brandChip)===active:btn.dataset.brandChip===''))}
function keepFeaturedInfinite(){const strip=$('#featuredStrip');if(strip)strip.classList.add('hm1043-marquee')}
function syncHeroDots(){const hero=$('#homeView .hm-hero-carousel'),track=hero&&$('.hm-hero-track',hero),dots=hero?$$('.hm-hero-dots button',hero):[];if(!track||dots.length<2||track.dataset.hm1043Dots==='1')return;track.dataset.hm1043Dots='1';let raf=0;const sync=()=>{raf=0;const w=Math.max(1,track.clientWidth),idx=Math.max(0,Math.min(dots.length-1,Math.round(track.scrollLeft/w)));dots.forEach((d,i)=>d.classList.toggle('active',i===idx))};track.addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(sync)},{passive:true});window.addEventListener('resize',sync,{passive:true});sync()}
function enhanceBrandSheet(){const input=$('#brandSearch');if(!input||input.dataset.hm1043Search==='1')return;input.dataset.hm1043Search='1';const sheet=input.closest('.v10-sheet')||document;const box=$('.v10-brand-options',sheet);if(!box)return;let empty=$('.hm1043-brand-empty',sheet);if(!empty){empty=document.createElement('div');empty.className='hm1043-brand-empty';empty.hidden=true;empty.textContent='No encontramos esa marca.';box.insertAdjacentElement('afterend',empty)}const filter=()=>{const q=compact(input.value),buttons=$$('[data-brand-option]',box);let visible=0;buttons.forEach((b,i)=>{const show=!q?(true):(i>0&&compact(b.textContent).includes(q));b.hidden=!show;if(show&&i>0)visible++});empty.hidden=!q||visible>0};input.addEventListener('input',filter,true);input.addEventListener('search',filter,true);filter()}
function decorateOrdersEmpty(){const empty=$('#ordersView .v10-empty.big');if(!empty)return;empty.classList.add('hm1043-orders-empty');let art=$('.hm-empty-art',empty);if(!art){const old=$('svg',empty);art=document.createElement('div');art.className='hm-empty-art';if(old)old.replaceWith(art);else empty.prepend(art)}art.classList.add('hm1043-order-art');if(art.dataset.hm1043!=='1'){art.dataset.hm1043='1';art.innerHTML='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M18 10h28a5 5 0 0 1 5 5v34a5 5 0 0 1-5 5H18a5 5 0 0 1-5-5V15a5 5 0 0 1 5-5Z"/><path d="M22 23h20M22 31h16M22 39h11"/><path d="m37 46 4 4 8-10"/></svg>'}const b=$('b',empty),span=$('span',empty),btn=$('button',empty);if(b)b.textContent='Tus pedidos aparecerán aquí';if(span)span.textContent='Cuando confirmes uno podrás revisar su estado y seguimiento.';if(btn)btn.textContent='Ver catálogo'}
function refineHome(){const home=$('#homeView .v10-home');if(!home)return;keepFeaturedInfinite();syncHeroDots();$('.hm-slide-main',home)?.classList.add('hm1043-reference-hero')}
function clearLegacyCatalogMotion(){const head=$('#catalogView .v10-catalog-head');head?.classList.remove('hm1042-catalog-hidden','hm-v1041-hidden')}
function enhance(){clearLegacyCatalogMotion();ensureCatalogBrands();refineHome();enhanceBrandSheet();decorateOrdersEmpty();document.documentElement.dataset.hmCatalog='10.4.3'}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};
window.addEventListener('kiubo:brands-ready',schedule);window.addEventListener('popstate',schedule);window.addEventListener('pageshow',schedule);document.addEventListener('click',schedule,true);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
