/* Hakuna Matata 10.7.1 — complete brand rail + keyboard-safe brand search. */
(()=>{
'use strict';
if(window.__hakunaCatalog1071)return;window.__hakunaCatalog1071=true;
if(/^\/(?:panel|master|pedido)(?:\/|$)/.test(location.pathname))return;
const C=window.KIUBO_CATALOG_CONFIG||{};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const key=v=>norm(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const preferred=['Coca-Cola','Toni','Bubbaloo','Chiclets','Cheese Tris','Cheetos','Chips Ahoy!','Dasani','Fanta','Sprite','Gatorade','Oreo','Doritos','Ruffles','Tostitos','Trident','Ritz'];
const themes={'coca-cola':['#fff','#e5202b'],'toni':['#3157a2','#fff'],'bubbaloo':['#fff','#173f86'],'chiclets':['#ffd728','#111'],'cheese-tris':['#ff7a18','#114e9c'],'nestle':['#fff','#d5272c'],'chips-ahoy':['#eef8ff','#0b54a0'],'club-social':['#0d4c8e','#fff'],'chiki':['#ef2937','#ffe21c']};
let fullBrands=[];
function visual(name){const k=key(name),url=(window.KIUBO_BRAND_ASSETS||{})[k],t=themes[k]||['#f4f6f2','#294a37'];return url?`<span class="hm-brand-visual has-image"><img src="${esc(url)}" alt="${esc(name)}" loading="lazy" decoding="async"></span>`:`<span class="hm-brand-visual" style="--hm-brand-bg:${t[0]};--hm-brand-fg:${t[1]}"><b>${esc(name)}</b></span>`}
function orderedFromProducts(products){const counts=new Map(),canonical=new Map();for(const p of Array.isArray(products)?products:[]){if(p?.visible===false||p?.archived_at)continue;const n=String(p?.brand||'').trim();if(!n)continue;const k=norm(n);canonical.set(k,canonical.get(k)||n);counts.set(k,(counts.get(k)||0)+1)}const first=preferred.map(x=>canonical.get(norm(x))).filter(Boolean),used=new Set(first.map(norm)),rest=[...canonical.values()].filter(x=>!used.has(norm(x))).sort((a,b)=>(counts.get(norm(b))||0)-(counts.get(norm(a))||0)||a.localeCompare(b,'es'));return [...first,...rest]}
function cachedProducts(){try{return JSON.parse(localStorage.getItem(`kiubo-v10-bootstrap:${slug}`)||'{}')?.products||[]}catch{return[]}}
function activeBrand(){const active=$('.hm-v104-catalog-brands [data-brand-chip].active');if(active)return active.dataset.brandChip||'';return $('#activeFilterHost .v10-active-filter b')?.textContent?.trim()||''}
function rebuildRail(){const rail=$('.hm-v104-catalog-brands');if(!rail||!fullBrands.length)return;const expected=fullBrands.length+1;if($$('[data-brand-chip]',rail).length===expected&&rail.dataset.hm1071==='1')return;const keep=rail.scrollLeft,active=norm(activeBrand());rail.innerHTML=`<button type="button" class="hm1043-all ${!active?'active':''}" data-brand-chip="" aria-label="Ver todos los productos"><span>Todos</span></button>`+fullBrands.map(name=>`<button type="button" data-brand-chip="${esc(name)}" class="${active&&norm(name)===active?'active':''}" aria-label="Ver ${esc(name)}">${visual(name)}</button>`).join('');rail.dataset.hm1071='1';rail.dataset.hm1071Count=String(fullBrands.length);requestAnimationFrame(()=>{rail.scrollLeft=Math.min(keep,Math.max(0,rail.scrollWidth-rail.clientWidth))})}
async function loadBrands(){const registry=Array.isArray(window.KIUBO_BRAND_ORDERED)?window.KIUBO_BRAND_ORDERED.filter(Boolean):[];const cached=orderedFromProducts(cachedProducts());fullBrands=cached.length>registry.length?cached:registry;if(fullBrands.length){window.KIUBO_BRAND_ORDERED=fullBrands.slice();rebuildRail()}if(!C.apiUrl)return;try{const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':'10.7.1'},body:JSON.stringify({action:'catalog_bootstrap',slug})});if(!r.ok)return;const p=await r.json();const live=orderedFromProducts(p?.products);if(live.length){fullBrands=live;window.KIUBO_BRAND_ORDERED=live.slice();window.dispatchEvent(new CustomEvent('kiubo:brands-ready',{detail:{brands:live.slice()}}));rebuildRail()}}catch{}}
function setKeyboardState(sheet,input){const vv=window.visualViewport;if(!vv||!sheet||!input)return;const focused=document.activeElement===input,keyboard=focused&&(window.innerHeight-vv.height>120||vv.height<window.innerHeight*.82);sheet.classList.toggle('hm1071-keyboard',keyboard);if(keyboard){const top=Math.max(8,Math.round(vv.offsetTop+8)),height=Math.max(280,Math.round(vv.height-16));sheet.style.setProperty('--hm1071-top',`${top}px`);sheet.style.setProperty('--hm1071-height',`${height}px`);const scroller=$('.v10-sheet-scroll',sheet),search=$('.v10-brand-search',sheet);if(scroller&&search){const target=Math.max(0,search.offsetTop-18);if(Math.abs(scroller.scrollTop-target)>8)scroller.scrollTop=target}}else{sheet.style.removeProperty('--hm1071-top');sheet.style.removeProperty('--hm1071-height')}}
function enhanceBrandSheet(){const input=$('#brandSearch');if(!input)return;const sheet=input.closest('.v10-sheet');if(!sheet)return;sheet.classList.add('hm1071-brand-sheet');if(input.dataset.hm1071==='1'){setKeyboardState(sheet,input);return}input.dataset.hm1071='1';const options=$('.v10-brand-options',sheet);const refresh=()=>{const q=norm(input.value);let first=null;$$('[data-brand-option]',options||sheet).forEach((b,i)=>{if(i===0){b.hidden=!!q;return}const show=!q||norm(b.textContent).includes(q);b.hidden=!show;if(show&&!first)first=b});requestAnimationFrame(()=>{setKeyboardState(sheet,input);if(q&&first)first.scrollIntoView({block:'nearest',behavior:'instant'})})};input.addEventListener('focus',()=>setTimeout(()=>setKeyboardState(sheet,input),60));input.addEventListener('input',refresh,true);input.addEventListener('search',refresh,true);window.visualViewport?.addEventListener('resize',()=>setKeyboardState(sheet,input),{passive:true});window.visualViewport?.addEventListener('scroll',()=>setKeyboardState(sheet,input),{passive:true});refresh()}
function enhance(){rebuildRail();enhanceBrandSheet();document.documentElement.dataset.hmCatalog='10.7.1'}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};
window.addEventListener('kiubo:brands-ready',()=>{const r=window.KIUBO_BRAND_ORDERED||[];if(r.length>fullBrands.length)fullBrands=r.slice();schedule()});
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('click',schedule,true);window.addEventListener('pageshow',schedule);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{loadBrands();schedule()},{once:true});else{loadBrands();schedule()}
})();
