(()=>{
'use strict';
if(window.__hakunaCatalog791)return;window.__hakunaCatalog791=true;
const C=window.KIUBO_CATALOG_CONFIG||{};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,promise=null,selectedBrand='',overlay=null,gesture=null,last=performance.now(),scheduled=false,raf=0;
async function boot(force=false){if(data&&!force)return data;if(promise&&!force)return promise;promise=fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version||'7.9.1'},body:JSON.stringify({action:'catalog_bootstrap',slug})}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'bootstrap_failed');data=b;return b}).finally(()=>promise=null);return promise}
function products(){return(data?.products||[]).filter(p=>p.visible!==false&&!p.archived_at)}
function presentations(id){return(data?.presentations||[]).filter(p=>String(p.product_id)===String(id)&&p.visible!==false).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0))}
function product(id){return products().find(p=>String(p.id)===String(id))||null}
function brands(){return[...new Set(products().map(p=>String(p.brand||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function topBrands(){const all=brands(),wanted=['Coca-Cola','Oreo','Doritos','Gatorade','Sprite','Fanta','Dasani','Trident','Bubbaloo'];const out=[];for(const w of wanted){const b=all.find(x=>norm(x)===norm(w)||norm(x).includes(norm(w)));if(b&&!out.includes(b))out.push(b)}for(const b of all){if(out.length>=6)break;if(!out.includes(b))out.push(b)}return out.slice(0,6)}
function imageForBrand(b){return products().find(p=>norm(p.brand)===norm(b)&&p.image_url)?.image_url||''}
function homeMarkup(){const picks=products().filter(p=>p.image_url),preferred=[];for(const key of ['coca-cola','oreo','doritos','gatorade','leche']){const p=picks.find(x=>norm([x.brand,x.name].join(' ')).includes(key));if(p&&!preferred.includes(p))preferred.push(p)}for(const p of picks){if(preferred.length>=4)break;if(!preferred.includes(p))preferred.push(p)}const imgs=preferred.slice(0,3);return `<div class="v78-home-showcase-copy"><small>HAKUNA MATATA · CATÁLOGO</small><h1>Abastece tu negocio sin complicarte.</h1><p>Encuentra lo que necesitas, combina jabas, cajas o unidades y arma tu pedido en minutos.</p><div><button type="button" data-k79-go-catalog>Ver catálogo</button><span>Pedido mayorista y por unidades</span></div></div><div class="v78-home-showcase-art">${imgs.map((p,i)=>`<figure class="p${i+1}"><img src="${esc(p.image_url)}" alt="${esc(p.name)}"><figcaption>${esc(p.brand||p.name)}</figcaption></figure>`).join('')}</div>`}
function homeBrandMarkup(){const list=topBrands().slice(0,4);return `<section class="v78-home-brands" data-k79-home-brands><header><div><small>ENCUENTRA RÁPIDO</small><h2>Compra por marca</h2></div><button type="button" data-k79-all-brands>Ver todas</button></header><div class="v78-home-brand-rail">${list.map(b=>`<button type="button" data-k79-home-brand="${esc(b)}"><span>${imageForBrand(b)?`<img src="${esc(imageForBrand(b))}" alt="">`:`<b>${esc(b.slice(0,1))}</b>`}</span><strong>${esc(b)}</strong></button>`).join('')}</div></section>`}
function decorateHome(){const home=$('#homeView .v7-home');if(!home||!data)return;const hero=$('.v7-hero',home),search=$('.v7-home-search',home);if(!hero||!search)return;hero.classList.add('v78-home-showcase');if(hero.dataset.k79!=='1'){hero.dataset.k79='1';hero.innerHTML=homeMarkup()}if(home.firstElementChild!==search)home.insertBefore(search,home.firstElementChild);let brandsBox=$('[data-k79-home-brands]',home);if(!brandsBox){hero.insertAdjacentHTML('beforebegin',homeBrandMarkup());brandsBox=$('[data-k79-home-brands]',home)}$$('.v7-home-points',home).forEach(x=>x.remove());const featured=$$('.v7-block',home).find(x=>/destacados|m[aá]s pedidos/i.test(x.textContent||''));if(featured)featured.classList.add('v78-featured-block')}
function brandCard(b){const img=imageForBrand(b);return `<button type="button" class="v78-brand-card ${selectedBrand&&norm(selectedBrand)===norm(b)?'active':''}" data-k79-brand="${esc(b)}"><span>${img?`<img src="${esc(img)}" alt="">`:`<b>${esc(b.slice(0,1).toUpperCase())}</b>`}</span><strong>${esc(b)}</strong></button>`}
function brandHubMarkup(){const list=topBrands().slice(0,5);return `<section class="v78-brand-hub" data-k79-brand-hub><header><div><small>FILTRA RÁPIDO</small><h3>Marcas</h3></div><button type="button" data-k79-all-brands>Ver todas</button></header><div class="v78-brand-hub-rail"><button type="button" class="v78-brand-card all ${!selectedBrand?'active':''}" data-k79-brand=""><span>✓</span><strong>Todas marcas</strong></button>${list.map(brandCard).join('')}</div>${selectedBrand?`<div class="v78-brand-current"><span>Viendo <b>${esc(selectedBrand)}</b></span><button type="button" data-k79-brand="">Quitar filtro</button></div>`:''}</section>`}
function disableBodyCategorySwipe(){const body=$('#catalogView .v7-catalog-body');if(!body||body.dataset.k79SwipeOff==='1')return body;const fresh=body.cloneNode(true);fresh.dataset.k79SwipeOff='1';body.replaceWith(fresh);return fresh}
function decorateProductCards(){$$('#catalogView .v7-product[data-product]').forEach(card=>{const p=product(card.dataset.product),ps=presentations(card.dataset.product);if(!p)return;card.dataset.k79Brand=norm(p.brand||'');if(ps.length>1){let pill=$('.v78-buytypes',card);if(!pill){pill=document.createElement('span');pill.className='v78-buytypes';$('.v7-product-title p',card)?.insertAdjacentElement('afterend',pill)}pill.textContent=ps.slice(0,2).map(x=>x.name).join(' + ');const add=$('[data-add]',card),s=add&&$('span',add);if(s)s.textContent='Elegir'}})}
function applyBrandFilter(){const grid=$('#catalogView .v7-product-grid');if(!grid)return;let shown=0;$$('.v7-product[data-product]',grid).forEach(card=>{const p=product(card.dataset.product),show=!selectedBrand||norm(p?.brand)===norm(selectedBrand);card.hidden=!show;if(show)shown++});const count=$('.v7-catalog-title>span');if(count)count.textContent=String(shown)}
function decorateCatalog(){const view=$('#catalogView');if(!view||!data)return;const body=disableBodyCategorySwipe();if(!body)return;const filter=$('#filterBtn',view);if(filter){const sp=$('span',filter);if(sp)sp.textContent='Marcas';filter.setAttribute('aria-label','Ver marcas')}const old=$('[data-k79-brand-hub]',body),html=brandHubMarkup();if(!old)body.insertAdjacentHTML('afterbegin',html);else if(old.dataset.state!==`${selectedBrand}|${brands().length}`)old.outerHTML=html;const hub=$('[data-k79-brand-hub]',body);if(hub)hub.dataset.state=`${selectedBrand}|${brands().length}`;decorateProductCards();applyBrandFilter()}
function closeBrandSheet(){overlay?.remove();overlay=null;document.documentElement.classList.remove('v78-modal-open');document.body.classList.remove('v78-modal-open')}
function openBrandSheet(){closeBrandSheet();const all=brands(),el=document.createElement('div');el.className='v78-brand-sheet';el.innerHTML=`<div class="v78-overlay-bg" data-k79-close></div><section><div class="v78-sheet-grab"></div><header><div><small>MARCAS</small><h2>Encuentra tu marca</h2><p>${all.length} marcas disponibles</p></div><button type="button" data-k79-close>×</button></header><label class="v78-brand-search"><span>⌕</span><input id="k79BrandSearch" autocomplete="off" placeholder="Buscar marca"></label><div class="v78-all-brands"><button type="button" data-k79-brand="" class="${!selectedBrand?'active':''}">Todas las marcas</button>${all.map(b=>`<button type="button" data-k79-brand="${esc(b)}" class="${norm(selectedBrand)===norm(b)?'active':''}">${esc(b)}</button>`).join('')}</div></section>`;document.body.append(el);overlay=el;document.documentElement.classList.add('v78-modal-open');document.body.classList.add('v78-modal-open');requestAnimationFrame(()=>el.classList.add('show'));$('#k79BrandSearch',el)?.focus({preventScroll:true})}
function setBrand(name){selectedBrand=name||'';closeBrandSheet();decorateCatalog()}
function filterBrandSheet(q){const n=norm(q);$$('.v78-all-brands [data-k79-brand]',overlay||document).forEach((b,i)=>{if(i===0)return;b.hidden=!!n&&!norm(b.textContent).includes(n)})}
function prepareCarousel(){const strip=$('#homeView .v7-product-strip');if(!strip||strip.dataset.k79Carousel==='1')return;const cards=[...strip.children].filter(x=>x.matches?.('.v7-product'));if(cards.length<2)return;strip.dataset.k79Carousel='1';strip.style.scrollBehavior='auto';const frag=document.createDocumentFragment();cards.forEach(card=>{const clone=card.cloneNode(true);clone.dataset.k79Clone='1';frag.append(clone)});strip.append(frag);strip.addEventListener('pointerdown',e=>{if(!e.isPrimary)return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY,mode:''}},{passive:true});strip.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.id||gesture.mode)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.max(Math.abs(dx),Math.abs(dy))<7)return;gesture.mode=Math.abs(dx)>Math.abs(dy)*1.16?'horizontal':'vertical'},{passive:true});const finish=e=>{if(!gesture||e.pointerId!==gesture.id)return;gesture=null;last=performance.now();normalizeCarousel(strip)};strip.addEventListener('pointerup',finish,{passive:true});strip.addEventListener('pointercancel',finish,{passive:true})}
function cycleWidth(strip){const first=strip.querySelector('.v7-product:not([data-k79-clone])'),clone=strip.querySelector('[data-k79-clone]');return first&&clone?clone.offsetLeft-first.offsetLeft:0}
function normalizeCarousel(strip){const w=cycleWidth(strip);if(w&&strip.scrollLeft>=w)strip.scrollLeft-=w}
function tick(now){raf=requestAnimationFrame(tick);const strip=$('#homeView .v7-product-strip[data-k79-carousel="1"]');if(!strip||!strip.isConnected||!$('#homeView')?.classList.contains('active')){last=now;return}const dt=Math.min(42,Math.max(0,now-last));last=now;if(document.visibilityState!=='visible'||gesture?.mode==='horizontal')return;strip.scrollLeft+=dt*.022;normalizeCarousel(strip)}
document.addEventListener('click',e=>{const filter=e.target.closest?.('#filterBtn');if(filter){e.preventDefault();e.stopImmediatePropagation();openBrandSheet();return}const close=e.target.closest?.('[data-k79-close]');if(close){e.preventDefault();e.stopImmediatePropagation();closeBrandSheet();return}const brand=e.target.closest?.('[data-k79-brand]');if(brand){e.preventDefault();e.stopImmediatePropagation();setBrand(brand.dataset.k79Brand||'');return}const all=e.target.closest?.('[data-k79-all-brands]');if(all){e.preventDefault();e.stopImmediatePropagation();openBrandSheet();return}const hb=e.target.closest?.('[data-k79-home-brand]');if(hb){e.preventDefault();e.stopImmediatePropagation();$('.v7-nav [data-view="catalog"]')?.click();selectedBrand=hb.dataset.k79HomeBrand||'';requestAnimationFrame(decorateCatalog);return}const go=e.target.closest?.('[data-k79-go-catalog]');if(go){e.preventDefault();e.stopImmediatePropagation();$('.v7-nav [data-view="catalog"]')?.click();return}const add=e.target.closest?.('[data-add]');if(add&&data&&presentations(add.dataset.add).length>1){e.preventDefault();e.stopImmediatePropagation();const open=add.closest('.v7-product')?.querySelector('[data-open]');if(open)requestAnimationFrame(()=>open.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true})));return}if(e.target.closest?.('[data-category]')){selectedBrand='';requestAnimationFrame(decorateCatalog)}},true)
document.addEventListener('input',e=>{if(e.target?.id==='k79BrandSearch')filterBrandSheet(e.target.value)},true)
document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('.v7-nav [data-view]');if(!b)return;const name=b.dataset.view;if(!name)return;$$('.v7-nav [data-view]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===name))},{passive:true,capture:true})
function enhance(){scheduled=false;if(!data)return;decorateHome();decorateCatalog();prepareCarousel();if($('.v78-home-showcase'))document.documentElement.classList.add('k79-ready')}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance)}
function observe(sel){const el=$(sel);if(el&&!el.dataset.k79Observed){el.dataset.k79Observed='1';new MutationObserver(schedule).observe(el,{childList:true,subtree:false})}}
function start(){boot().then(()=>enhance()).catch(()=>document.documentElement.classList.add('k79-ready'));['#homeView','#catalogView','#sheetHost','#cartView'].forEach(observe);schedule();last=performance.now();raf=requestAnimationFrame(tick);setTimeout(()=>document.documentElement.classList.add('k79-ready'),1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();