(()=>{
'use strict';
if(window.__hakunaCatalog78)return;window.__hakunaCatalog78=true;
const C=window.KIUBO_CATALOG_CONFIG||{};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,promise=null,selectedBrand='',brandSwitch=false,overlay=null,sheetHistoryArmed=false,legacyHistoryArmed=false,suppressSheetArmUntil=0,suppressLegacyArmUntil=0,compact=false,carouselTimer=0,carouselPauseUntil=0;
async function boot(force=false){if(data&&!force)return data;if(promise&&!force)return promise;promise=fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version||'7.8.0'},body:JSON.stringify({action:'catalog_bootstrap',slug})}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b?.error||'bootstrap_failed');data=b;return b}).finally(()=>promise=null);return promise}
function products(){return(data?.products||[]).filter(p=>p.visible!==false&&!p.archived_at)}
function product(id){return products().find(p=>String(p.id)===String(id))||null}
function presentations(id){return(data?.presentations||[]).filter(p=>String(p.product_id)===String(id)&&p.visible!==false).sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0))}
function presentationByName(pid,name){return presentations(pid).find(p=>norm(p.name)===norm(name))||null}
function isRestrictedName(s=''){const n=norm(s);return /\bclub\b.*(330|550)|cerveza|beer|vino|whisky|ron\b/.test(n)}
function brands(){return[...new Set(products().filter(p=>!isRestrictedName(p.name)).map(p=>String(p.brand||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function topBrands(){const all=brands(),wanted=['Coca-Cola','Oreo','Doritos','Gatorade','Sprite','Fanta','Dasani','Trident','Bubbaloo','Apetitas'];const out=[];for(const w of wanted){const b=all.find(x=>norm(x)===norm(w)||norm(x).includes(norm(w)));if(b&&!out.includes(b))out.push(b)}for(const b of all){if(out.length>=6)break;if(!out.includes(b))out.push(b)}return out.slice(0,6)}
function imageForBrand(b){return products().find(p=>norm(p.brand)===norm(b)&&p.image_url&&!isRestrictedName(p.name))?.image_url||''}
function currentView(){return $('.v7-nav button.active[data-view]')?.dataset.view||'home'}
function pushOverlayState(kind){if(history.state?.v78Overlay)return;history.pushState({...history.state,v7View:currentView(),v78Overlay:kind},'',location.href)}
function lock(){document.documentElement.classList.add('v78-modal-open');document.body.classList.add('v78-modal-open')}
function unlock(){document.documentElement.classList.remove('v78-modal-open');document.body.classList.remove('v78-modal-open')}
function homeMarkup(){const picks=products().filter(p=>p.image_url&&!isRestrictedName(p.name));const preferred=[];for(const key of ['coca-cola','oreo','doritos','gatorade','leche']){const p=picks.find(x=>norm([x.brand,x.name].join(' ')).includes(key));if(p&&!preferred.includes(p))preferred.push(p)}for(const p of picks){if(preferred.length>=4)break;if(!preferred.includes(p))preferred.push(p)}const imgs=preferred.slice(0,3);return `<div class="v78-home-showcase-copy"><small>HAKUNA MATATA · CATÁLOGO</small><h1>Abastece tu negocio sin complicarte.</h1><p>Encuentra lo que necesitas, combina jabas, cajas o unidades y arma tu pedido en minutos.</p><div><button type="button" data-v78-go-catalog>Ver catálogo</button><span>Pedido mayorista y por unidades</span></div></div><div class="v78-home-showcase-art">${imgs.map((p,i)=>`<figure class="p${i+1}"><img src="${esc(p.image_url)}" alt="${esc(p.name)}"><figcaption>${esc(p.brand||p.name)}</figcaption></figure>`).join('')}</div>`}
function homeBrandMarkup(){const list=topBrands().slice(0,4);return `<section class="v78-home-brands"><header><div><small>ENCUENTRA RÁPIDO</small><h2>Compra por marca</h2></div><button type="button" data-v78-all-brands>Ver todas</button></header><div class="v78-home-brand-rail">${list.map(b=>`<button type="button" data-v78-home-brand="${esc(b)}"><span>${imageForBrand(b)?`<img src="${esc(imageForBrand(b))}" alt="">`:`<b>${esc(b.slice(0,1))}</b>`}</span><strong>${esc(b)}</strong></button>`).join('')}</div></section>`}
function decorateHome(){const home=$('#homeView .v7-home');if(!home||!data)return;const hero=$('.v7-hero',home),search=$('.v7-home-search',home);if(!hero||!search)return;hero.classList.add('v78-home-showcase');if(hero.dataset.v78!=='1'){hero.dataset.v78='1';hero.innerHTML=homeMarkup()}if(home.firstElementChild!==search)home.insertBefore(search,home.firstElementChild);let brandsBox=$('.v78-home-brands',home);if(!brandsBox){hero.insertAdjacentHTML('beforebegin',homeBrandMarkup());brandsBox=$('.v78-home-brands',home)}const categoryBlock=$$('.v7-block',home).find(x=>/categor[ií]as/i.test(x.textContent||''));if(categoryBlock&&!$('.v78-format-banner',home)){const multi=products().find(p=>p.image_url&&presentations(p.id).length>1&&!isRestrictedName(p.name));if(multi){categoryBlock.insertAdjacentHTML('afterend',`<article class="v78-format-banner"><div><small>COMPRA FLEXIBLE</small><h3>Jaba, caja o unidad. Tú eliges.</h3><p>Los productos con varias presentaciones te muestran todas las opciones antes de agregar.</p><button type="button" data-v78-go-catalog>Ver productos</button></div><figure><img src="${esc(multi.image_url)}" alt="${esc(multi.name)}"><span>${esc(multi.name)}</span></figure></article>`)}}$$('.v7-home-points',home).forEach(x=>x.remove());const featured=$$('.v7-block',home).find(x=>/destacados/i.test(x.textContent||''));if(featured)featured.classList.add('v78-featured-block');ensureCarousel()}
function brandCard(b){const img=imageForBrand(b);return `<button type="button" class="v78-brand-card ${selectedBrand&&norm(selectedBrand)===norm(b)?'active':''}" data-v78-brand="${esc(b)}"><span>${img?`<img src="${esc(img)}" alt="">`:`<b>${esc(b.slice(0,1).toUpperCase())}</b>`}</span><strong>${esc(b)}</strong></button>`}
function brandHubMarkup(){const list=topBrands().slice(0,5);return `<section class="v78-brand-hub"><header><div><small>FILTRA RÁPIDO</small><h3>Marcas</h3></div><button type="button" data-v78-all-brands>Ver todas</button></header><div class="v78-brand-hub-rail"><button type="button" class="v78-brand-card all ${!selectedBrand?'active':''}" data-v78-brand=""><span>✓</span><strong>Todas</strong></button>${list.map(brandCard).join('')}</div>${selectedBrand?`<div class="v78-brand-current"><span>Viendo <b>${esc(selectedBrand)}</b></span><button type="button" data-v78-brand="">Quitar filtro</button></div>`:''}</section>`}
function decorateCatalog(){const view=$('#catalogView');if(!view||!data)return;$('#v77BrandRail',view)?.remove();const filter=$('#filterBtn',view);if(filter){const sp=$('span',filter);if(sp)sp.textContent='Marcas';filter.setAttribute('aria-label','Ver marcas')}const body=$('.v7-catalog-body',view);if(body){let hub=$('.v78-brand-hub',body);const html=brandHubMarkup();if(!hub){body.insertAdjacentHTML('afterbegin',html);hub=$('.v78-brand-hub',body)}else if(hub.dataset.state!==`${selectedBrand}|${brands().length}`){hub.outerHTML=html;hub=$('.v78-brand-hub',body)}if(hub)hub.dataset.state=`${selectedBrand}|${brands().length}`}applyBrandFilter();decorateProductCards()}
function decorateProductCards(){$$('#catalogView .v7-product[data-product]').forEach(card=>{const p=product(card.dataset.product),ps=presentations(card.dataset.product);if(!p)return;card.dataset.v78Brand=norm(p.brand||'');if(ps.length>1){let pill=$('.v78-buytypes',card);if(!pill){pill=document.createElement('span');pill.className='v78-buytypes';$('.v7-product-title p',card)?.insertAdjacentElement('afterend',pill)}pill.textContent=ps.slice(0,2).map(x=>x.name).join(' + ');const add=$('[data-add]',card),s=add&&$('span',add);if(s)s.textContent='Elegir'}})}
function applyBrandFilter(){const grid=$('#catalogView .v7-product-grid');if(!grid)return;const q=norm($('#catalogSearch')?.value||'');let shown=0;$$('.v7-product[data-product]',grid).forEach(card=>{const p=product(card.dataset.product);const brandOk=!selectedBrand||norm(p?.brand)===norm(selectedBrand);const searchOk=!q||norm([p?.name,p?.brand,p?.description,p?.sku,card.textContent].join(' ')).includes(q);const show=brandOk&&searchOk;card.hidden=!show;if(show)shown++});const count=$('.v7-catalog-title>span');if(count)count.textContent=String(shown);let empty=$('.v78-filter-empty',grid.parentElement);if(!shown&&(selectedBrand||q)){if(!empty){empty=document.createElement('div');empty.className='v78-filter-empty';grid.insertAdjacentElement('afterend',empty)}empty.innerHTML=`<b>No encontramos productos</b><span>${selectedBrand?'Prueba otra marca o categoría.':'Prueba otra búsqueda.'}</span>${selectedBrand?'<button type="button" data-v78-brand="">Ver todas las marcas</button>':''}`}else empty?.remove()}
function setBrand(name){selectedBrand=name||'';brandSwitch=true;const all=$('#categoryRail [data-category="all"]');if(all&&!all.classList.contains('active'))all.click();setTimeout(()=>{brandSwitch=false;decorateCatalog();window.scrollTo({top:Math.max(0,($('#catalogHead')?.offsetTop||0)-58),behavior:'smooth'})},40)}
function openBrandSheet(){closeOverlay(true);const all=brands();const el=document.createElement('div');el.className='v78-brand-sheet';el.innerHTML=`<div class="v78-overlay-bg" data-v78-overlay-close></div><section><div class="v78-sheet-grab"></div><header><div><small>MARCAS</small><h2>Encuentra tu marca</h2><p>${all.length} marcas disponibles</p></div><button type="button" data-v78-overlay-close>×</button></header><label class="v78-brand-search"><span>⌕</span><input id="v78BrandSearch" autocomplete="off" placeholder="Buscar marca"></label><div class="v78-all-brands"><button type="button" data-v78-brand="" class="${!selectedBrand?'active':''}">Todas las marcas</button>${all.map(b=>`<button type="button" data-v78-brand="${esc(b)}" class="${norm(selectedBrand)===norm(b)?'active':''}">${esc(b)}</button>`).join('')}</div></section>`;document.body.append(el);overlay=el;lock();pushOverlayState('brands');requestAnimationFrame(()=>el.classList.add('show'));$('#v78BrandSearch',el)?.focus({preventScroll:true})}
function closeOverlay(skipHistory=false){if(!overlay)return;const had=overlay;overlay=null;had.remove();unlock();if(!skipHistory&&history.state?.v78Overlay==='brands')history.back()}
function filterBrandSheet(q){const n=norm(q);$$('.v78-all-brands [data-v78-brand]',overlay||document).forEach((b,i)=>{if(i===0)return;const show=!n||norm(b.textContent).includes(n);b.hidden=!show})}
function decorateDetail(){const sheet=$('.v7-sheet');if(!sheet||!data)return;const cardTitle=$('.v7-detail-body h2',sheet)?.textContent||'';const p=products().find(x=>norm(x.name)===norm(cardTitle));if(!p)return;const active=$('[data-presentation].active',sheet);const pr=active?presentations(p.id).find(x=>String(x.id)===String(active.dataset.presentation)):presentations(p.id)[0];const img=$('.v7-detail-media>img',sheet);if(img){img.src=pr?.image_url||p.image_url||img.src;img.classList.add('v78-contain-image')}}
function updateDetailImage(btn){const sheet=btn.closest('.v7-sheet'),title=$('.v7-detail-body h2',sheet)?.textContent||'',p=products().find(x=>norm(x.name)===norm(title));if(!p)return;const pr=presentations(p.id).find(x=>String(x.id)===String(btn.dataset.presentation));const img=$('.v7-detail-media>img',sheet);if(img)img.src=pr?.image_url||p.image_url||img.src}
function decorateCart(){const view=$('#cartView');if(!view||!data)return;const head=$('.v7-cart-title',view);if(head&&$('[data-cart-minus]',view)&&!$('.v78-clear-cart',head)){const b=document.createElement('button');b.type='button';b.className='v78-clear-cart';b.textContent='Vaciar carrito';head.append(b)}$$('.v7-cart-line',view).forEach(line=>{const name=$('h3',line)?.textContent?.trim(),pres=$('p',line)?.textContent?.trim(),p=products().find(x=>norm(x.name)===norm(name));if(!p)return;const pr=presentationByName(p.id,pres),src=pr?.image_url||p.image_url||'';const box=$('.v7-cart-photo',line);if(box&&src){let img=$('img',box);if(!img){box.innerHTML='<img alt="">';img=$('img',box)}if(img.src!==src)img.src=src}})}
function clearCartDialog(){if(!$('#cartView [data-cart-minus]'))return;const el=document.createElement('div');el.className='v78-confirm';el.innerHTML='<div class="v78-overlay-bg" data-v78-confirm-close></div><section><small>CARRITO</small><h2>¿Vaciar todo el carrito?</h2><p>Se quitarán todos los productos que agregaste.</p><div><button data-v78-confirm-close>Cancelar</button><button class="danger" id="v78ClearNow">Vaciar carrito</button></div></section>';document.body.append(el);overlay=el;lock();pushOverlayState('brands');requestAnimationFrame(()=>el.classList.add('show'));$('#v78ClearNow',el).onclick=clearCartNow}
async function clearCartNow(){const el=overlay;overlay=null;el?.remove();unlock();let guard=0;while(guard++<500){const b=$('#cartView [data-cart-minus]');if(!b)break;b.click();await new Promise(r=>requestAnimationFrame(r))}if(history.state?.v78Overlay==='brands')history.back()}
function neutralizeNoisyToast(node){if(node?.nodeType!==1)return;const arr=[node,...(node.querySelectorAll?.('.v77-toast,.v7-toast')||[])];for(const e of arr){if((e.matches?.('.v77-toast,.v7-toast'))&&/(selecci[oó]n|selecciones|pedidos actualizados|agregado al carrito)/i.test(e.textContent||''))e.remove()}}
function compactHeader(){const head=$('#catalogHead');if(!head)return;const y=window.scrollY;if(!compact&&y>150)compact=true;else if(compact&&y<70)compact=false;head.classList.toggle('v78-compact',compact)}
function ensureCarousel(){if(carouselTimer)return;carouselTimer=setInterval(()=>{const strip=$('#homeView .v7-product-strip');if(!strip||!strip.isConnected||Date.now()<carouselPauseUntil)return;const view=$('#homeView');if(!view?.classList.contains('active'))return;const card=strip.querySelector('.v7-product'),step=(card?.getBoundingClientRect().width||190)+11,max=strip.scrollWidth-strip.clientWidth;if(max<20)return;if(strip.scrollLeft>=max-step*.7)strip.scrollTo({left:0,behavior:'smooth'});else strip.scrollBy({left:step,behavior:'smooth'})},2600)}
function armBaseSheetHistory(){const host=$('#sheetHost');if(!host||Date.now()<suppressSheetArmUntil)return;const has=!!$('.v7-sheet',host);if(has&&!sheetHistoryArmed){sheetHistoryArmed=true;pushOverlayState('sheet')}else if(!has&&sheetHistoryArmed){sheetHistoryArmed=false;if(history.state?.v78Overlay==='sheet')history.back()}}
function armLegacyOverlayHistory(){if(Date.now()<suppressLegacyArmUntil)return;const has=!!$('.v77-chooser,.v77-cancel');if(has&&!legacyHistoryArmed){legacyHistoryArmed=true;pushOverlayState('legacy')}else if(!has&&legacyHistoryArmed){legacyHistoryArmed=false;if(history.state?.v78Overlay==='legacy')history.back()}}
function sync(){decorateHome();decorateCatalog();decorateDetail();decorateCart();compactHeader();armBaseSheetHistory();armLegacyOverlayHistory()}
document.addEventListener('click',e=>{const filter=e.target.closest?.('#filterBtn');if(filter){e.preventDefault();e.stopImmediatePropagation();openBrandSheet();return}const b=e.target.closest?.('[data-v78-brand]');if(b){e.preventDefault();e.stopImmediatePropagation();const name=b.dataset.v78Brand||'';if(overlay){closeOverlay();setTimeout(()=>setBrand(name),10)}else setBrand(name);return}const all=e.target.closest?.('[data-v78-all-brands]');if(all){e.preventDefault();e.stopImmediatePropagation();openBrandSheet();return}const hb=e.target.closest?.('[data-v78-home-brand]');if(hb){e.preventDefault();e.stopImmediatePropagation();$('.v7-nav [data-view="catalog"]')?.click();setTimeout(()=>setBrand(hb.dataset.v78HomeBrand||''),70);return}const go=e.target.closest?.('[data-v78-go-catalog]');if(go){e.preventDefault();$('.v7-nav [data-view="catalog"]')?.click();return}if(e.target.closest?.('[data-category]')&&!brandSwitch){selectedBrand='';setTimeout(decorateCatalog,0)}if(e.target.closest?.('.v78-clear-cart')){e.preventDefault();e.stopImmediatePropagation();clearCartDialog();return}if(e.target.closest?.('[data-v78-overlay-close],[data-v78-confirm-close]')){e.preventDefault();e.stopImmediatePropagation();closeOverlay();return}},true);
document.addEventListener('click',e=>{const p=e.target.closest?.('[data-presentation]');if(p)setTimeout(()=>updateDetailImage(p),0)},false);
document.addEventListener('input',e=>{if(e.target?.id==='catalogSearch')setTimeout(applyBrandFilter,0);if(e.target?.id==='v78BrandSearch')filterBrandSheet(e.target.value)},true);
document.addEventListener('pointerdown',e=>{if(e.target.closest?.('.v7-product-strip'))carouselPauseUntil=Date.now()+5000},{passive:true});
window.addEventListener('scroll',()=>requestAnimationFrame(compactHeader),{passive:true});
window.addEventListener('popstate',()=>{if(overlay){const o=overlay;overlay=null;o.remove();unlock()}const v77=$('.v77-chooser,.v77-cancel');if(v77){suppressLegacyArmUntil=Date.now()+350;legacyHistoryArmed=false;$('[data-v771-close]',v77)?.click()}if($('.v7-sheet')){suppressSheetArmUntil=Date.now()+350;sheetHistoryArmed=false}setTimeout(()=>{armBaseSheetHistory();armLegacyOverlayHistory()},380)});
const bodyObs=new MutationObserver(rs=>{for(const r of rs)for(const n of r.addedNodes)neutralizeNoisyToast(n);requestAnimationFrame(sync)});
function observeHost(sel){const el=$(sel);if(el&&!el.dataset.v78Observed){el.dataset.v78Observed='1';new MutationObserver(()=>requestAnimationFrame(sync)).observe(el,{childList:true,subtree:false})}}
function start(){boot().then(()=>{sync();ensureCarousel()}).catch(()=>{});bodyObs.observe(document.body,{childList:true,subtree:false});['#homeView','#catalogView','#cartView','#sheetHost'].forEach(observeHost);sync();ensureCarousel()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();