(()=>{
'use strict';
if(window.__hakunaPanel77)return;window.__hakunaPanel77=true;
const C=window.KIUBO_CATALOG_CONFIG;if(!C?.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const token=()=>sessionStorage.getItem(`kiubo-provider-session:${slug}`)||'';
let cache=null,loading=null,raf=0,modalObs=null;
async function api(action,payload={}){const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version,'X-Provider-Session':token()},body:JSON.stringify({action,slug,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'request_failed');return b}
async function boot(force=false){if(cache&&!force)return cache;if(loading&&!force)return loading;loading=api('provider_bootstrap').then(p=>(cache=p,p)).finally(()=>loading=null);return loading}
async function optimize(f){if(!(f instanceof File)||f.size<280*1024||!/^image\/(jpeg|png|webp)$/i.test(f.type))return f;try{const b=await createImageBitmap(f,{imageOrientation:'from-image'}),m=960,s=Math.min(1,m/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.width*s));c.height=Math.max(1,Math.round(b.height*s));c.getContext('2d',{alpha:true}).drawImage(b,0,0,c.width,c.height);b.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.82));return blob&&blob.size<f.size?new File([blob],f.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):f}catch{return f}}
function toast(msg,type=''){const e=document.createElement('div');e.className=`v77-panel-toast ${type}`;e.textContent=msg;document.body.append(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),160)},1900)}
function presentation(id){return cache?.presentations?.find(p=>String(p.id)===String(id))||null}
function setPreview(row,p){const box=$('.v77-presentation-image',row);if(!box)return;const src=p?.image_url||'';const preview=$('.v77-presentation-preview',box);if(preview)preview.innerHTML=src?`<img src="${String(src).replace(/"/g,'&quot;')}" alt="">`:'<span>+</span>';const text=$('.v77-presentation-image-copy small',box);if(text)text.textContent=src?'Imagen propia · puedes cambiarla':'Opcional · usa la foto de esta unidad, caja, pack o jaba'}
async function upload(row,file){const id=row.dataset.id;if(!id)return toast('Guarda el producto primero para habilitar esta foto','error');const ui=$('.v77-presentation-image',row);ui?.classList.add('busy');try{const p=presentation(id)||{},f=await optimize(file),fd=new FormData();fd.set('action','upload_asset');fd.set('kind','product');fd.set('slug',slug);fd.set('old_path',p.image_path||'');fd.set('file',f,f.name);const r=await fetch(C.apiUrl,{method:'POST',headers:{'X-Client-Version':C.version,'X-Provider-Session':token()},body:fd});const up=await r.json().catch(()=>({}));if(!r.ok)throw new Error(up.error||'upload_failed');const saved=await api('save_presentation_image',{presentation_id:id,image_url:up.public_url||null,image_path:up.path||null});const next=saved.presentation||{id,image_url:up.public_url,image_path:up.path};if(cache?.presentations){const i=cache.presentations.findIndex(x=>String(x.id)===String(id));if(i>=0)cache.presentations[i]={...cache.presentations[i],...next};else cache.presentations.push(next)}setPreview(row,next);toast('Foto de presentación guardada')}catch(err){console.error(err);toast('No pudimos guardar esa imagen','error')}finally{ui?.classList.remove('busy')}}
function addControl(row){if($('.v77-presentation-image',row))return;const id=row.dataset.id||'';const p=id?presentation(id):null;const wrap=document.createElement('div');wrap.className='v77-presentation-image';wrap.innerHTML=`<div class="v77-presentation-preview">${p?.image_url?`<img src="${String(p.image_url).replace(/"/g,'&quot;')}" alt="">`:'<span>+</span>'}</div><div class="v77-presentation-image-copy"><b>Foto de esta presentación</b><small>${id?(p?.image_url?'Imagen propia · puedes cambiarla':'Opcional · foto específica para esta unidad, caja, pack o jaba'):'Guarda el producto primero para habilitarla'}</small></div>${id?'<label>Elegir imagen<input type="file" accept="image/png,image/jpeg,image/webp" hidden></label>':''}`;row.append(wrap);const input=$('input[type="file"]',wrap);if(input)input.onchange=()=>{const f=input.files?.[0];if(f)upload(row,f)}}
function decorateRows(){raf=0;const rows=$$('#v5PresentationRows .v5-presentation-row');if(!rows.length)return;rows.forEach(addControl);boot().then(()=>rows.forEach(row=>{const id=row.dataset.id||'';if(id)setPreview(row,presentation(id))})).catch(()=>{})}
function queueDecorate(){if(raf)return;raf=requestAnimationFrame(decorateRows)}
function observeModal(){const modal=$('#productModal');if(!modal||modalObs)return false;modalObs=new MutationObserver(queueDecorate);modalObs.observe(modal,{childList:true,subtree:true});return true}
function ensureObserver(){if(observeModal())return;let tries=0;const timer=setInterval(()=>{tries++;if(observeModal()||tries>30)clearInterval(timer)},250)}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-edit-product],#newProductBtn,#mobileCreateBtn,[data-quick="new-product"]')){setTimeout(queueDecorate,30);setTimeout(queueDecorate,120);setTimeout(queueDecorate,300)}},true);
document.addEventListener('focusin',e=>{if(e.target.closest?.('#productModal'))queueDecorate()},true);
const start=()=>{ensureObserver();queueDecorate();boot().then(queueDecorate).catch(()=>{})};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
