/* Hakuna Panel 10.6 — destructive-action safety, real filter counts and catalog cleanup controls. */
(()=>{
'use strict';
if(window.__hakunaPanel106)return;window.__hakunaPanel106=true;
if(!/^\/panel(?:\/|$)/.test(location.pathname))return;
const C=window.KIUBO_CATALOG_CONFIG||{};if(!C.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const token=()=>sessionStorage.getItem(`kiubo-provider-session:${slug}`)||'';
const snapshot={products:[],categories:[]};
let activeProductId='';
const parse=init=>{try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}};
const upstream=window.fetch.bind(window);
window.fetch=async(input,init={})=>{const res=await upstream(input,init),url=typeof input==='string'?input:input?.url||'',body=url===C.apiUrl?parse(init):null;if(res.ok&&body&&['provider_bootstrap','master_bootstrap'].includes(body.action)){res.clone().json().then(p=>{if(Array.isArray(p.products))snapshot.products=p.products;if(Array.isArray(p.categories))snapshot.categories=p.categories;schedule()}).catch(()=>{})}return res};
async function call(action,payload={}){const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version||'10.6.0','X-Provider-Session':token()},body:JSON.stringify({action,slug,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok||b?.ok===false)throw Object.assign(new Error(b?.error||`request_${r.status}`),{code:b?.error||''});return b}
function toast(text,type=''){let el=$('.hm106-panel-toast');if(!el){el=document.createElement('div');el.className='hm106-panel-toast';document.body.append(el)}el.textContent=text;el.className=`hm106-panel-toast ${type}`;requestAnimationFrame(()=>el.classList.add('show'));clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}

function countProducts(){const p=snapshot.products;return{all:p.filter(x=>!x.archived_at).length,available:p.filter(x=>!x.archived_at&&x.status==='available').length,low:p.filter(x=>!x.archived_at&&x.status==='low').length,out:p.filter(x=>!x.archived_at&&x.status==='out').length,hidden:p.filter(x=>!x.archived_at&&x.visible===false).length,archived:p.filter(x=>!!x.archived_at).length}}
function setCount(btn,n){if(!btn)return;let b=$('.hm106-filter-count',btn);if(!b){b=document.createElement('b');b.className='hm106-filter-count';btn.append(b)}b.textContent=String(n)}
function decorateCounts(){if(!snapshot.products.length)return;const counts=countProducts();$$('[data-product-filter]').forEach(btn=>{const key=btn.dataset.productFilter;if(key==='all'){const base=$('#countAll',btn);if(base)base.textContent=String(counts.all);else setCount(btn,counts.all)}else if(key in counts)setCount(btn,counts[key])});$$('[data-v75-category]').forEach(btn=>{const id=btn.dataset.v75Category;const n=id==='all'?counts.all:snapshot.products.filter(p=>!p.archived_at&&String(p.category_id)===String(id)).length;setCount(btn,n)})}

function ensureDeleteProduct(){const modal=$('#productModal');if(!modal||modal.hidden)return;const footer=$('footer',modal);if(!footer)return;let btn=$('#hm106DeleteProduct',footer);if(!btn){btn=document.createElement('button');btn.id='hm106DeleteProduct';btn.type='button';btn.className='button button--danger hm106-delete-product';btn.textContent='Eliminar del catálogo';const archive=$('#archiveProductBtn',footer);archive?.insertAdjacentElement('afterend',btn);btn.onclick=async()=>{if(!activeProductId)return;const name=$('#productName')?.value?.trim()||'este producto';if(!confirm(`¿Eliminar “${name}” del catálogo?\n\nSe ocultará de clientes y búsquedas, pero los pedidos históricos se conservarán.`))return;btn.disabled=true;btn.textContent='Eliminando…';try{await call('delete_product',{product_id:activeProductId});toast('Producto eliminado del catálogo','success');$('#productModal [data-close-modal]')?.click();setTimeout(()=>$('#refreshBtn')?.click(),120)}catch{toast('No pudimos eliminar el producto','error');btn.disabled=false;btn.textContent='Eliminar del catálogo'}}}btn.hidden=!activeProductId}

document.addEventListener('pointerdown',e=>{const edit=e.target.closest?.('[data-edit-product]');if(edit)activeProductId=String(edit.dataset.editProduct||'');if(e.target.closest?.('#newProductBtn,#mobileCreateBtn,[data-quick="new-product"]'))activeProductId=''},true);

function ensureResetOrders(){const panel=$('[data-settings-panel="security"] .panel-card')||$('.security-panel');if(!panel||$('#hm106ResetOrders'))return;const box=document.createElement('section');box.className='hm106-reset-zone';box.innerHTML='<div><small>SEGURIDAD</small><b>Restablecer historial de pedidos</b><span>Borra únicamente los pedidos. Productos, fotos, clientes y configuración no se eliminan.</span></div><button type="button" id="hm106ResetOrders"><i></i><span>Mantén presionado 5 s</span></button>';panel.append(box);const btn=$('#hm106ResetOrders',box),label=$('span',btn);let timer=0,start=0,raf=0,done=false;const stop=()=>{clearTimeout(timer);cancelAnimationFrame(raf);timer=0;start=0;if(!done){btn.style.removeProperty('--hold');label.textContent='Mantén presionado 5 s'}};const draw=()=>{if(!start)return;const p=Math.min(1,(performance.now()-start)/5000);btn.style.setProperty('--hold',`${p*100}%`);label.textContent=p<1?`Mantén… ${Math.ceil((1-p)*5)} s`:'Listo';if(p<1)raf=requestAnimationFrame(draw)};const run=async()=>{done=true;stop();if(!confirm('¿Seguro que quieres borrar TODO el historial de pedidos?\n\nEsta acción no borra productos, fotos ni configuración.')){done=false;label.textContent='Mantén presionado 5 s';btn.style.removeProperty('--hold');return}btn.disabled=true;label.textContent='Restableciendo…';try{const r=await call('reset_orders');toast(`${Number(r.deleted||0)} pedidos eliminados`,'success');setTimeout(()=>$('#refreshBtn')?.click(),150)}catch{toast('No pudimos restablecer los pedidos','error')}finally{btn.disabled=false;done=false;label.textContent='Mantén presionado 5 s';btn.style.removeProperty('--hold')}};btn.addEventListener('pointerdown',e=>{if(btn.disabled)return;e.preventDefault();done=false;start=performance.now();btn.setPointerCapture?.(e.pointerId);draw();timer=setTimeout(run,5000)});['pointerup','pointercancel','pointerleave'].forEach(t=>btn.addEventListener(t,stop));}

function enhance(){decorateCounts();ensureDeleteProduct();ensureResetOrders();document.documentElement.dataset.hmPanel='10.6'}
let raf=0;function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});document.addEventListener('click',schedule,true);window.addEventListener('pageshow',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
