(()=>{
'use strict';
if(window.__hakunaPanel75)return;window.__hakunaPanel75=true;
const C=window.KIUBO_CATALOG_CONFIG;if(!C?.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const logo=C.brandLogoUrl||'',nativeFetch=window.fetch.bind(window),CORE=C.apiUrl,V6=C.apiUrl,ROUTER=C.apiUrl;
const products=new Map();let categories=[],activeId='',activeCategory='all',queue=[],running=0,refreshTimer=0;
const token=()=>sessionStorage.getItem(`kiubo-provider-session:${slug}`)||'';
const headers=()=>({'Content-Type':'application/json','X-Client-Version':C.version,'X-Provider-Session':token()});
const parse=init=>{try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function cacheBootstrap(p){if(!p||!Array.isArray(p.products))return;products.clear();p.products.forEach(x=>products.set(String(x.id),x));categories=Array.isArray(p.categories)?p.categories:categories;setTimeout(refreshProductTools,30)}
window.fetch=async(input,init={})=>{const r=await nativeFetch(input,init);const b=(typeof input==='string'&&input===C.apiUrl)?parse(init):null;if(r.ok&&b&&['provider_bootstrap','master_bootstrap'].includes(b.action))r.clone().json().then(cacheBootstrap).catch(()=>{});return r};

function useLogo(){if(!logo)return;['#gateLogo img','.loading-logo img','#sideLogo img','#mobileLogo img','#logoPreview img'].forEach(s=>{const i=$(s);if(i&&i.src!==logo)i.src=logo});let a=document.querySelector('link[rel="apple-touch-icon"]');if(!a){a=document.createElement('link');a.rel='apple-touch-icon';document.head.append(a)}a.href=logo;const f=document.querySelector('link[rel="icon"]');if(f)f.href=logo}
function removeInstall(){ $('#v5InstallBtn')?.remove();const t=$('.v5-tools');if(t&&!t.children.length)t.remove() }
function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}
function setLabel(label,text){if(!label)return;const n=[...label.childNodes].find(x=>x.nodeType===Node.TEXT_NODE);if(n){if(n.nodeValue!==text)n.nodeValue=text}else label.prepend(document.createTextNode(text))}
function polishEditor(){
 const ed=$('#v5ProductEditor');if(!ed)return;$('#saveNextProductBtn')?.remove();if($('#archiveProductBtn'))$('#archiveProductBtn').hidden=true;
 const head=$('.v5-editor-head',ed);setText($('b',head),'Venta por presentaciones');setText($('small',head),'Configura cómo se vende: unidad, pack, caja, jaba o cualquier otra forma.');
 const note=$('#v5AllowNote')?.closest('label');setText($('b',note),'Permitir surtido o variedades');setText($('small',note),'Para sabores, colores, modelos o mezclas. Ej.: 3 Coca-Cola + 3 Sprite + 3 Fiora.');
 setText($('.v5-presentations-head h4',ed),'Formas de venta');setText($('#v5AddPresentation'),'+ Añadir forma de venta');
 const pbox=$('.v5-presentations',ed);if(pbox&&!$('.v75-presentation-intro',pbox)){const d=document.createElement('div');d.className='v75-presentation-intro';d.innerHTML='<b>Ejemplo rápido</b>Unidad base: botella. Crea <strong>Unidad = 1</strong> y <strong>Jaba x 9 = 9</strong>. Así el cliente puede pedir 2 jabas y además 5 botellas; todo descuenta del mismo stock.';pbox.insertBefore(d,$('#v5PresentationRows',pbox)||pbox.firstChild)}
 $$('.v5-presentation-row',ed).forEach(row=>{const l=$$(':scope>label',row);setLabel(l[0],'Cómo se vende');setLabel(l[1],'Unidades que contiene');setLabel(l[2],'Precio de venta');setLabel(l[3],'Nombre de la unidad');setText($('.v5-default span',row),'Predeterminada');setLabel($('.v6-cost-block label',row),'Costo de esta presentación')});
 setText($('.v5-presentation-note',ed),'El stock se controla en la unidad base. Puedes crear varias formas de venta sin duplicar el producto.');
}
function closeProduct(){const m=$('#productModal');if(!m)return;m.classList.remove('visible');m.hidden=true;const b=$('#modalBackdrop');if(b){b.classList.remove('visible');b.hidden=true}document.body.classList.remove('modal-open')}
function pill(error=''){let e=$('.v75-saving-pill');if(error){if(!e){e=document.createElement('div');document.body.append(e)}e.className='v75-saving-pill error';e.innerHTML=`<i></i><span>${esc(error)}</span>`;setTimeout(()=>e.remove(),5000);return}const n=queue.length+running;if(!n){e?.remove();return}if(!e){e=document.createElement('div');document.body.append(e)}e.className='v75-saving-pill';e.innerHTML=`<i></i><span>${n===1?'Guardando en segundo plano…':`Guardando ${n} productos…`}</span>`}
function presentations(){return $$('.v5-presentation-row').map((r,i)=>({id:r.dataset.id||null,name:$('[data-p-name]',r)?.value.trim()||'Unidad',unit_label:$('[data-p-unit]',r)?.value.trim()||'unidad',units_per_presentation:Math.max(1,Math.trunc(Number($('[data-p-units]',r)?.value||1))),price:Math.max(0,Number($('[data-p-price]',r)?.value||0)),compare_at_price:null,sku:null,visible:true,is_default:Boolean($('[data-p-default]',r)?.checked),sort_order:i,cost_total:(()=>{const v=$('[data-p-cost]',r)?.value;return v===''||v==null?null:Math.max(0,Number(v||0))})()})).filter(x=>x.name)}
function job(){const name=$('#productName')?.value.trim()||'',price=Number($('#productPrice')?.value);if(name.length<2||!Number.isFinite(price)||price<0)return null;const old=products.get(String(activeId))||{};return {file:$('#productImage')?.files?.[0]||null,old,product:{id:activeId||null,name,category_id:$('#productCategory')?.value||null,brand:$('#productBrand')?.value.trim()||null,price,compare_at_price:$('#productComparePrice')?.value?Number($('#productComparePrice').value):null,unit:$('#productUnit')?.value.trim()||null,sku:$('#productSku')?.value.trim()||null,description:$('#productDescription')?.value.trim()||null,status:$('#productStatus')?.value||'available',sort_order:Number($('#productSort')?.value||0),visible:$('#productVisible')?.checked!==false,featured:Boolean($('#productFeatured')?.checked),image_path:old.image_path||null,image_url:old.image_url||null},presentations:presentations(),stock:{stock_tracking:Boolean($('#v5StockTracking')?.checked),stock_quantity:Math.max(0,Math.trunc(Number($('#v5StockQuantity')?.value||0))),low_stock_threshold:Math.max(0,Math.trunc(Number($('#v5LowThreshold')?.value||5))),base_unit:$('#v5BaseUnit')?.value.trim()||'unidad',allow_item_note:$('#v5AllowNote')?.checked!==false}}}
async function optimize(f){if(!(f instanceof File)||f.size<300*1024||!/^image\/(jpeg|png|webp)$/i.test(f.type))return f;try{const b=await createImageBitmap(f,{imageOrientation:'from-image'}),max=1152,s=Math.min(1,max/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.width*s));c.height=Math.max(1,Math.round(b.height*s));c.getContext('2d',{alpha:true}).drawImage(b,0,0,c.width,c.height);b.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.8));return blob&&blob.size<f.size?new File([blob],f.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):f}catch{return f}}
async function save(j){if(j.file){const f=await optimize(j.file),fd=new FormData();fd.set('action','upload_asset');fd.set('kind','product');fd.set('slug',slug);fd.set('old_path',j.old.image_path||'');fd.set('file',f,f.name);const ur=await nativeFetch(CORE,{method:'POST',headers:{'X-Client-Version':C.version,'X-Provider-Session':token()},body:fd}),up=await ur.json().catch(()=>({}));if(!ur.ok)throw 0;j.product.image_path=up.path||null;j.product.image_url=up.public_url||null}
 const r=await nativeFetch(CORE,{method:'POST',headers:headers(),body:JSON.stringify({action:'save_product',slug,product:j.product})}),p=await r.json().catch(()=>({}));if(!r.ok)throw 0;const id=String(p.id||j.product.id||'');if(!id)throw 0;j.product.id=id;
 if(j.presentations.length){const pr=await nativeFetch(V6,{method:'POST',headers:headers(),body:JSON.stringify({action:'save_presentations',slug,product_id:id,presentations:j.presentations})});if(!pr.ok)throw 0}
 const sr=await nativeFetch(ROUTER,{method:'POST',headers:headers(),body:JSON.stringify({action:'save_stock',slug,product_id:id,...j.stock})});if(!sr.ok)throw 0;products.set(id,{...j.old,...j.product,...j.stock})}
function pump(){while(running<2&&queue.length){const j=queue.shift();running++;pill();save(j).then(()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>$('#refreshBtn')?.click(),700)}).catch(()=>pill('No terminó de guardarse un producto. Actualiza y revisa ese producto.')).finally(()=>{running--;pill();pump()})}}

function statusOf(p){if(p?.archived_at)return'archived';if(p?.visible===false)return'hidden';return p?.status||'available'}
function counts(){const c={all:0,available:0,low:0,out:0,hidden:0,archived:0};products.forEach(p=>{const s=statusOf(p);if(!p.archived_at)c.all++;if(c[s]!=null)c[s]++});$$('[data-product-filter]').forEach(b=>{const k=b.dataset.productFilter;let n=$('b',b);if(!n){n=document.createElement('b');b.append(n)}const v=String(c[k]||0);if(n.textContent!==v)n.textContent=v})}
function categoryRail(){const row=$('.filter-row');if(!row||!categories.length)return;let rail=$('#v75CategoryFilters');if(!rail){rail=document.createElement('div');rail.id='v75CategoryFilters';rail.className='v75-category-filters';row.insertAdjacentElement('afterend',rail)}const all=[...products.values()].filter(p=>!p.archived_at),num=id=>all.filter(p=>String(p.category_id)===String(id)).length,html=`<button data-v75-category="all" class="${activeCategory==='all'?'active':''}">Todas <b>${all.length}</b></button>${categories.filter(c=>c.visible!==false).map(c=>`<button data-v75-category="${esc(c.id)}" class="${String(activeCategory)===String(c.id)?'active':''}">${esc(c.name)} <b>${num(c.id)}</b></button>`).join('')}`;if(rail.dataset.html!==html){rail.dataset.html=html;rail.innerHTML=html}}
function applyFilters(){const list=$('#adminProductList');if(!list||!products.size)return;const q=($('#productSearch')?.value||'').trim().toLowerCase(),status=$('[data-product-filter].active')?.dataset.productFilter||'all';$$('.admin-product',list).forEach(row=>{const id=$('[data-edit-product]',row)?.dataset.editProduct||'',p=products.get(String(id));if(!p)return;const s=statusOf(p),text=[p.name,p.brand,p.sku,p.unit,categories.find(c=>String(c.id)===String(p.category_id))?.name].join(' ').toLowerCase(),show=(!q||text.includes(q))&&(status==='all'?!p.archived_at:s===status)&&(activeCategory==='all'||String(p.category_id)===String(activeCategory));row.hidden=!show})}
function refreshProductTools(){counts();categoryRail();applyFilters()}
function orderClose(){const m=$('#orderModal');if(!m||m.hidden||$('.v75-order-x',m))return;const b=document.createElement('button');b.className='v75-order-x';b.type='button';b.textContent='×';b.setAttribute('aria-label','Cerrar pedido');b.onclick=()=>($('[data-close-modal]',m)?.click());m.append(b)}
function polish(){useLogo();removeInstall();polishEditor();orderClose();$('#saveNextProductBtn')?.remove();if($('#archiveProductBtn'))$('#archiveProductBtn').hidden=true;refreshProductTools()}

document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-product]');if(edit){activeId=edit.dataset.editProduct||'';setTimeout(polishEditor,35)}if(e.target.closest?.('#newProductBtn,#mobileCreateBtn,[data-quick="new-product"]')){activeId='';setTimeout(polishEditor,35)}const cat=e.target.closest?.('[data-v75-category]');if(cat){e.preventDefault();activeCategory=cat.dataset.v75Category||'all';categoryRail();applyFilters();return}if(e.target.closest?.('[data-product-filter]'))setTimeout(applyFilters,0);if(e.target.closest?.('[data-open-order]'))setTimeout(orderClose,30)},true);
document.addEventListener('input',e=>{if(e.target?.id==='productSearch')setTimeout(applyFilters,0)},true);
window.addEventListener('beforeinstallprompt',()=>setTimeout(removeInstall,0));
const start=()=>{useLogo();setTimeout(()=>{removeInstall();polish()},20);const list=$('#adminProductList');if(list)new MutationObserver(()=>setTimeout(refreshProductTools,0)).observe(list,{childList:true});};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();