/* Hakuna Panel 10.4.2 — reliable presentation photos + simpler editor/search UX. */
(()=>{
'use strict';
if(window.__hakunaPanel1042)return;window.__hakunaPanel1042=true;
if(!/^\/panel(?:\/|$)/.test(location.pathname))return;
const C=window.KIUBO_CATALOG_CONFIG||{};if(!C.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const token=()=>sessionStorage.getItem(`kiubo-provider-session:${slug}`)||'';
const QUEUE_KEY=`kiubo-v1042-photo-queue:${slug}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const pathFromUrl=url=>{try{const u=new URL(url,location.href),m='/storage/v1/object/public/catalog-assets-v4/';const i=u.pathname.indexOf(m);return i>=0?decodeURIComponent(u.pathname.slice(i+m.length)):''}catch{return''}};
const readQueue=()=>{try{const q=JSON.parse(localStorage.getItem(QUEUE_KEY)||'{}');return q&&typeof q==='object'&&!Array.isArray(q)?q:{}}catch{return{}}};
const writeQueue=q=>{try{localStorage.setItem(QUEUE_KEY,JSON.stringify(q))}catch{}};
function setRowCopy(row,text,state=''){if(!row)return;row.dataset.hmPhotoState=state;const copy=$('.v77-presentation-image-copy small',row);if(copy)copy.textContent=text;state==='saving'?row.setAttribute('aria-busy','true'):row.removeAttribute('aria-busy')}
function toast(text,type=''){const old=$('.hm1042-panel-toast');old?.remove();const el=document.createElement('div');el.className=`hm1042-panel-toast ${type}`;el.textContent=text;document.body.append(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),180)},2500)}
async function json(action,payload={}){const s=token();if(!s)throw new Error('session_missing');const r=await fetch(C.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':C.version||'10.4.2','X-Provider-Session':s},body:JSON.stringify({action,slug,...payload})});const b=await r.json().catch(()=>({}));if(!r.ok||b?.ok===false)throw new Error(b?.error||`request_${r.status}`);return b}
async function bootstrap(){return json('provider_bootstrap')}
async function presentationById(id){const b=await bootstrap();return (b?.presentations||[]).find(p=>String(p.id)===String(id))||null}
async function optimize(file){if(!(file instanceof File)||file.size<260*1024||!/^image\/(jpeg|png|webp)$/i.test(file.type))return file;try{const bitmap=await createImageBitmap(file,{imageOrientation:'from-image'}),max=1080,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d',{alpha:true}).drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',.86));return blob&&blob.size<file.size?new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'}):file}catch{return file}}
function remember(item){if(!item?.id||!item.image_url||!item.image_path)return;const q=readQueue();q[item.id]={...item,attempts:Number(q[item.id]?.attempts||0),queued_at:q[item.id]?.queued_at||new Date().toISOString()};writeQueue(q)}
function forget(id){const q=readQueue();if(q[id]){delete q[id];writeQueue(q)}}
async function verify(item){const p=await presentationById(item.id);if(!p)return false;return Boolean((p.image_url||p.image_path)&&(String(p.image_url||'')===String(item.image_url)||String(p.image_path||'')===String(item.image_path)))}
async function persist(item,row=null){if(!item||!token()||!navigator.onLine)return false;const q=readQueue(),queued=q[item.id]||item,attempts=Number(queued.attempts||0);if(attempts>=10){setRowCopy(row,'Foto subida · pendiente de sincronizar. Se reintentará al abrir el panel.','pending');return false}q[item.id]={...queued,attempts:attempts+1,last_attempt:new Date().toISOString()};writeQueue(q);setRowCopy(row,'Guardando y verificando foto…','saving');try{const saved=await json('save_presentation_image',{presentation_id:item.id,image_url:item.image_url,image_path:item.image_path});if(!(await verify(item)))throw new Error('verification_failed');forget(item.id);if(row){row.dataset.v77PendingImage='0';row.dataset.v10ImageUrl=item.image_url;row.dataset.v10ImagePath=item.image_path}setRowCopy(row,'Foto guardada y verificada','saved');if(saved?.product_image_synced){const preview=$('#productImagePreview');if(preview)preview.innerHTML=`<img src="${String(item.image_url).replace(/"/g,'&quot;')}" alt="Portada actual">`}return true}catch(err){console.error('Hakuna photo persist',err);setRowCopy(row,'Foto subida · guardado pendiente. Reintentaremos automáticamente.','pending');return false}}
let flushing=false;async function flush(){if(flushing||!navigator.onLine||!token())return;flushing=true;try{for(const item of Object.values(readQueue())){const row=$(`#v5PresentationRows .v5-presentation-row[data-id="${CSS.escape(String(item.id))}"]`);await persist(item,row)}}finally{flushing=false}}
function localPreview(row,file){const preview=$('.v77-presentation-preview',row);if(!preview)return'';const url=URL.createObjectURL(file);preview.innerHTML=`<img src="${url}" alt="Vista previa">`;setTimeout(()=>URL.revokeObjectURL(url),30000);return url}
async function uploadPresentation(row,file){if(!row||!file)return;const id=String(row.dataset.id||'');if(!uuid(id)){toast('Guarda el producto una vez para crear esta presentación y luego sube la foto.','error');setRowCopy(row,'Primero guarda el producto para crear esta presentación','pending');return}if(!/^image\/(png|jpeg|webp)$/i.test(file.type)){toast('Usa una imagen PNG, JPG o WebP.','error');return}if(file.size>5*1024*1024){toast('La imagen supera 5 MB.','error');return}localPreview(row,file);setRowCopy(row,'Preparando foto…','saving');try{const current=await presentationById(id);const oldPath=String(current?.image_path||'');const optimized=await optimize(file),fd=new FormData();fd.set('action','upload_asset');fd.set('kind','product');fd.set('slug',slug);fd.set('old_path',oldPath);fd.set('file',optimized,optimized.name||file.name);const r=await fetch(C.apiUrl,{method:'POST',headers:{'X-Client-Version':C.version||'10.4.2','X-Provider-Session':token()},body:fd});const up=await r.json().catch(()=>({}));if(!r.ok||!up?.public_url||!up?.path)throw new Error(up?.error||'upload_failed');const item={id,image_url:up.public_url,image_path:up.path};row.dataset.v10ImageUrl=item.image_url;row.dataset.v10ImagePath=item.image_path;row.dataset.v77PendingImage='1';const preview=$('.v77-presentation-preview',row);if(preview)preview.innerHTML=`<img src="${String(item.image_url).replace(/"/g,'&quot;')}" alt="Foto de presentación">`;remember(item);const ok=await persist(item,row);toast(ok?'Foto guardada correctamente':'Foto subida; terminaremos de sincronizarla automáticamente',ok?'success':'')}catch(err){console.error('Hakuna presentation upload',err);setRowCopy(row,'No pudimos completar la subida · inténtalo otra vez','pending');toast('No pudimos guardar esa foto. Inténtalo otra vez.','error')}}
function interceptPhotoChange(event){const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=='file'||!input.closest('.v77-presentation-image'))return;event.stopImmediatePropagation();event.stopPropagation();const row=input.closest('.v5-presentation-row'),file=input.files?.[0];if(file&&row)uploadPresentation(row,file);input.value=''}
document.addEventListener('change',interceptPhotoChange,true);
function decorateEditor(){const modal=$('#productModal');if(!modal||modal.hidden)return;const general=$('.product-image-upload',modal);if(general&&!general.dataset.hm1042){general.dataset.hm1042='1';general.classList.add('hm1042-general-photo');const b=$('label b',general),small=$('label small',general);if(b)b.textContent='Portada general (opcional)';if(small)small.textContent='Solo como respaldo. Se guarda al tocar “Guardar producto”.';const guide=document.createElement('div');guide.className='hm1042-photo-guide';guide.innerHTML='<b>Una foto por presentación, sin duplicar</b><span>Sube la imagen en “Unidad”, “Caja”, “Jaba”, etc. La presentación predeterminada se usa automáticamente como portada del producto.</span>';general.insertAdjacentElement('beforebegin',guide)}$$('#v5PresentationRows .v5-presentation-row',modal).forEach(row=>{const def=$('[data-p-default]',row);const box=$('.v77-presentation-image',row);if(!box)return;let badge=$('.hm1042-default-badge',box);if(def?.checked){if(!badge){badge=document.createElement('span');badge.className='hm1042-default-badge';badge.textContent='Portada automática';box.append(badge)}}else badge?.remove()})}
function refreshOnClear(input){if(!input||input.value.trim())return;requestAnimationFrame(()=>{if(input.id==='productSearch'){const active=$('[data-product-filter].active');active?.click()}else if(input.id==='orderSearch'){const active=$('[data-order-filter].active');active?.click()}else if(input.id==='customerSearch'){const active=$('[data-nav="customers"].active');active?.click()}})}
function bindSearch(id){const input=$(`#${id}`);if(!input||input.dataset.hm1042Search)return;input.dataset.hm1042Search='1';let before=input.value||'';const check=()=>{const now=input.value||'';if(before!==now){before=now;if(!now.trim())refreshOnClear(input)}};input.addEventListener('input',check,true);input.addEventListener('search',()=>{before=input.value||'';if(!input.value.trim())refreshOnClear(input)},true);input.addEventListener('change',()=>{if(!input.value.trim())refreshOnClear(input)},true)}
function decorateGeneralPhotoState(){const input=$('#productImage');if(!input||input.dataset.hm1042General)return;input.dataset.hm1042General='1';input.addEventListener('change',()=>{if(input.files?.[0]){const small=$('.product-image-upload label small');if(small)small.textContent='Nueva portada lista · toca “Guardar producto” para aplicarla.'}},true)}
let scheduled=false;function enhance(){scheduled=false;decorateEditor();decorateGeneralPhotoState();['productSearch','orderSearch','customerSearch'].forEach(bindSearch)}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(enhance)}
const obs=new MutationObserver(schedule);obs.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','checked']});document.addEventListener('input',e=>{if(e.target?.matches?.('[data-p-default]'))schedule()},true);window.addEventListener('online',()=>setTimeout(flush,100));window.addEventListener('focus',()=>setTimeout(flush,180));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(flush,180)});setInterval(()=>{if(document.visibilityState==='visible')flush()},12000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{schedule();setTimeout(flush,400)},{once:true});else{schedule();setTimeout(flush,400)}
})();
