(()=>{
  'use strict';
  const config=window.KIUBO_CATALOG_CONFIG;if(!config?.apiUrl)return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const slug=(()=>{const q=new URLSearchParams(location.search).get('slug');return(q||config.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'')})();
  let activeProductId='',activeProductName='',decorating=false,decorateQueued=false,filterTimer=0,holdTimer=0;
  const token=()=>sessionStorage.getItem(`kiubo-provider-session:${slug}`)||'';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(msg,type=''){const el=document.createElement('div');el.className=`v7-panel-toast ${type}`;el.textContent=msg;document.body.append(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),180)},2400)}
  async function call(action,payload={}){const res=await fetch(config.apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Client-Version':config.version,'X-Provider-Session':token()},body:JSON.stringify({action,slug,...payload})});const body=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok){const e=new Error(body.message||body.error||'request_failed');e.code=body.error;throw e}return body}
  function closeProductModal(){const modal=$('#productModal');if(!modal)return;const close=$('[data-close-modal]',modal)||$('.modal-close',modal)||$('.admin-modal__close',modal);if(close)close.click();else{modal.classList.remove('visible');modal.hidden=true}}
  function confirmSheet({eyebrow,title,copy,confirm='Confirmar',danger=true,onConfirm}){document.querySelector('.v7-admin-confirm')?.remove();const overlay=document.createElement('div');overlay.className='v7-admin-confirm';overlay.innerHTML=`<div class="v7-admin-confirm__backdrop"></div><section><span>${esc(eyebrow)}</span><h3>${esc(title)}</h3><p>${esc(copy)}</p><div><button type="button" data-cancel>Cancelar</button><button type="button" data-confirm ${danger?'class="danger"':''}>${esc(confirm)}</button></div></section>`;document.body.append(overlay);requestAnimationFrame(()=>overlay.classList.add('show'));const close=()=>{overlay.classList.remove('show');setTimeout(()=>overlay.remove(),150)};overlay.querySelector('[data-cancel]').onclick=close;overlay.querySelector('.v7-admin-confirm__backdrop').onclick=close;overlay.querySelector('[data-confirm]').onclick=async e=>{const btn=e.currentTarget;btn.disabled=true;const old=btn.textContent;btn.textContent='Procesando…';try{await onConfirm();close()}catch(err){btn.disabled=false;btn.textContent=old;throw err}}}
  function confirmDelete(id,name){confirmSheet({eyebrow:'ELIMINAR PRODUCTO',title:`¿Eliminar “${name||'este producto'}”?`,copy:'Desaparecerá del catálogo, favoritos, búsquedas y panel activo. Los pedidos anteriores conservarán su historial.',confirm:'Eliminar producto',onConfirm:async()=>{try{await call('delete_product',{product_id:id});closeProductModal();$$(`[data-edit-product="${CSS.escape(String(id))}"]`).forEach(b=>b.closest('.admin-product')?.remove());toast('Producto eliminado');setTimeout(()=>$('#refreshBtn')?.click(),220)}catch(err){toast(err.code==='product_not_found'?'El producto ya no existe':'No pudimos eliminar el producto','error');throw err}}})}
  function injectDangerZone(){const modal=$('#productModal'),form=$('#productForm');if(!modal||modal.hidden||!form)return;let zone=$('#v7DeleteProductZone',form);if(!zone){zone=document.createElement('section');zone.id='v7DeleteProductZone';zone.className='v7-delete-zone';zone.innerHTML=`<div><b>Eliminar del catálogo</b><small>Úsalo para productos de prueba, duplicados o que ya no vas a manejar.</small></div><button type="button" id="v7DeleteProductBtn">Eliminar producto</button>`;form.append(zone);$('#v7DeleteProductBtn',zone).onclick=()=>{if(activeProductId)confirmDelete(activeProductId,activeProductName)}}zone.hidden=!activeProductId}
  function decorateProductRows(){if(decorating)return;decorating=true;requestAnimationFrame(()=>{decorating=false;$$('#adminProductList .admin-product').forEach(row=>{if(row.dataset.v7Done)return;const edit=$('[data-edit-product]',row);if(!edit)return;row.dataset.v7Done='1';const id=edit.dataset.editProduct||'';const name=$('.admin-product__copy h3',row)?.textContent?.trim()||'Producto';const actions=edit.parentElement;if(!actions)return;const del=document.createElement('button');del.type='button';del.className='v7-inline-delete';del.dataset.deleteProduct=id;del.setAttribute('aria-label',`Eliminar ${name}`);del.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M8 10v8M12 10v8M16 10v8M6 7l1 14h10l1-14"/></svg>';actions.append(del)});applyProductFilters()})}
  function polishFeaturedSwitch(){const input=$('#productFeatured'),row=input?.closest('.switch-row');if(!row)return;row.classList.add('v71-featured-switch');const title=$('b',row),copy=$('small',row);if(title)title.textContent='Mostrar en Productos destacados';if(copy)copy.textContent='Aparece en el carrusel infinito de la pantalla Inicio. Puedes activar o quitar cualquier producto cuando quieras.'}
  function nativeSurface(){const meta=document.querySelector('meta[name="viewport"]');if(meta)meta.setAttribute('content','width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover');document.documentElement.classList.add('v71-native-surface');document.addEventListener('contextmenu',e=>{if(!e.target.closest?.('input,textarea,select'))e.preventDefault()});document.addEventListener('dragstart',e=>{if(e.target.closest?.('img,.admin-product,.side-nav,.panel-card'))e.preventDefault()})}
  function polishStatic(){document.documentElement.classList.add('kiubo-panel-v7');const search=$('#productSearch');if(search&&search.placeholder!=='Buscar producto, marca o código')search.placeholder='Buscar producto, marca o código';const title=$('#viewTitle');if(title&&$('[data-nav="products"]')?.classList.contains('active')&&title.textContent!=='Productos')title.textContent='Productos';polishFeaturedSwitch();ensureModalClose();ensureResetOrders()}
  function queueDecorate(){if(decorateQueued)return;decorateQueued=true;requestAnimationFrame(()=>{decorateQueued=false;polishStatic();decorateProductRows()})}
  function observeProducts(){const list=$('#adminProductList');if(!list||list.dataset.v7Observed)return;list.dataset.v7Observed='1';new MutationObserver(queueDecorate).observe(list,{childList:true})}

  function rowFilterState(row){if(/Archivado/i.test(row.textContent||''))return'archived';if(/Oculto/i.test(row.textContent||''))return'hidden';return $('.stock-selector [data-status].active',row)?.dataset.status||'available'}
  function applyProductFilters(){const list=$('#adminProductList');if(!list)return;const q=($('#productSearch')?.value||'').trim().toLowerCase(),active=$('[data-product-filter].active'),filter=active?.dataset.productFilter||'all';let visible=0;$$('.admin-product',list).forEach(row=>{const hay=(row.textContent||'').toLowerCase();const state=rowFilterState(row);const matchText=!q||hay.includes(q);let matchFilter=filter==='all'?state!=='archived':state===filter;if(filter==='all'&&state==='hidden')matchFilter=true;const show=matchText&&matchFilter;row.hidden=!show;row.classList.toggle('v72-filtered-out',!show);if(show)visible++});list.dataset.visibleCount=String(visible)}
  function smoothFilterClick(button){$$('[data-product-filter]').forEach(x=>x.classList.toggle('active',x===button));const list=$('#adminProductList');list?.classList.add('v72-filtering');requestAnimationFrame(()=>{applyProductFilters();requestAnimationFrame(()=>list?.classList.remove('v72-filtering'))})}

  function ensureModalClose(){const modal=$('#productModal');if(!modal||$('.v72-modal-x',modal))return;const b=document.createElement('button');b.type='button';b.className='v72-modal-x';b.setAttribute('aria-label','Cerrar producto');b.innerHTML='<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6 6 18"/></svg>';b.onclick=closeProductModal;modal.append(b)}
  function resetModalScroll(){const modal=$('#productModal');if(!modal||modal.hidden)return;modal.scrollTop=0;const form=$('#productForm');if(form)form.scrollTop=0;const mform=$('.modal-form',modal);if(mform)mform.scrollTop=0;ensureModalClose()}

  function ensureResetOrders(){const security=$('[data-settings-panel="security"]');if(!security||$('#v72ResetOrders'))return;const section=document.createElement('div');section.className='panel-card v72-reset-card';section.innerHTML=`<header><div><span class="section-kicker">MANTENIMIENTO</span><h3>Historial de pedidos</h3><p>Úsalo solo cuando quieras limpiar pedidos de prueba y empezar el historial desde cero. Productos, stock, categorías y configuración no se tocan.</p></div></header><div class="v72-reset-body"><div><b>Restablecer únicamente pedidos</b><small>Mantén presionado el botón durante 5 segundos para desbloquear la confirmación.</small></div><button id="v72ResetOrders" type="button"><i></i><span>Mantén 5 s para restablecer</span></button></div>`;security.append(section);const btn=$('#v72ResetOrders',section);const cancel=()=>{clearTimeout(holdTimer);holdTimer=0;btn.classList.remove('holding');btn.style.removeProperty('--hold')};const startHold=e=>{if(e.button!=null&&e.button!==0)return;cancel();btn.classList.add('holding');btn.style.setProperty('--hold','1');holdTimer=setTimeout(()=>{cancel();confirmResetOrders()},5000)};btn.addEventListener('pointerdown',startHold);['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,cancel));btn.addEventListener('contextmenu',e=>e.preventDefault())}
  function confirmResetOrders(){confirmSheet({eyebrow:'RESTABLECER PEDIDOS',title:'¿Borrar todo el historial de pedidos?',copy:'Esta acción elimina únicamente los pedidos de este catálogo. No elimina productos, stock, categorías, pagos ni configuración.',confirm:'Sí, borrar pedidos',onConfirm:async()=>{try{const r=await call('reset_orders');toast(`${Number(r.deleted||0)} pedidos eliminados`);setTimeout(()=>$('#refreshBtn')?.click(),180)}catch{toast('No pudimos restablecer los pedidos','error');throw new Error('reset_failed')}}})}

  function suppressNewOrderPopups(){new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes){if(node.nodeType!==1||!node.classList?.contains('v5-notification-toast'))continue;if(/pedido/i.test(node.textContent||''))node.remove()}}).observe(document.body,{childList:true})}

  document.addEventListener('input',e=>{if(e.target?.id!=='productSearch')return;e.stopImmediatePropagation();clearTimeout(filterTimer);filterTimer=setTimeout(applyProductFilters,45)},{capture:true});
  document.addEventListener('click',e=>{
    const filter=e.target.closest?.('[data-product-filter]');if(filter){e.preventDefault();e.stopImmediatePropagation();smoothFilterClick(filter);return}
    const nav=e.target.closest?.('[data-nav="products"]');if(nav)setTimeout(()=>{polishStatic();observeProducts();decorateProductRows();applyProductFilters()},0);
    const edit=e.target.closest?.('[data-edit-product]');if(edit){activeProductId=edit.dataset.editProduct||'';activeProductName=edit.closest('.admin-product')?.querySelector('.admin-product__copy h3')?.textContent?.trim()||'';setTimeout(()=>{injectDangerZone();polishFeaturedSwitch();resetModalScroll()},35)}
    const fresh=e.target.closest?.('#newProductBtn,#mobileCreateBtn,[data-quick="new-product"]');if(fresh){activeProductId='';activeProductName='';setTimeout(()=>{injectDangerZone();polishFeaturedSwitch();resetModalScroll()},35)}
    const del=e.target.closest?.('[data-delete-product]');if(del){e.preventDefault();e.stopPropagation();const row=del.closest('.admin-product');confirmDelete(del.dataset.deleteProduct,row?.querySelector('.admin-product__copy h3')?.textContent?.trim()||'Producto')}
    if(e.target.closest?.('[data-settings="security"]'))setTimeout(ensureResetOrders,20)
  },true);
  const start=()=>{nativeSurface();polishStatic();observeProducts();decorateProductRows();suppressNewOrderPopups();ensureResetOrders()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();