(() => {
  'use strict';
  const config=window.KIUBO_CATALOG_CONFIG;if(!config?.apiUrl)return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const slug=(()=>{const q=new URLSearchParams(location.search).get('slug');const m=location.pathname.match(/^\/c\/([^/]+)/);return(q||m?.[1]||config.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'')})();
  const state={products:[],presentations:[],orders:[],activeProductId:'',firstBootstrap:true,deferredInstall:null,editorReady:false};
  const nativeFetch=window.fetch.bind(window);
  const parse=init=>{try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}};
  const product=id=>state.products.find(p=>String(p.id)===String(id));
  const presentations=id=>state.presentations.filter(p=>String(p.product_id)===String(id)).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));
  const localPhone=v=>{const d=String(v||'').replace(/\D/g,'');return d.startsWith('593')?`0${d.slice(3,12)}`:d.length===9?`0${d}`:d.slice(0,10)};
  const phone593=v=>{const d=localPhone(v).replace(/\D/g,'');return d.startsWith('0')?`593${d.slice(1)}`:d};
  const statusLabel=s=>({new:'Recibido',confirmed:'Confirmado',preparing:'Preparando',dispatched:'Despachado',delivered:'Entregado',cancelled:'Cancelado'})[s]||'Actualizado';
  const statusMessage=(order,status)=>{const name=order.customer_business||order.customer_name||'cliente';const link=`${location.origin}/pedido?ref=${order.public_token||''}`;const map={new:`Hola ${name}. Ya recibimos tu pedido ${order.order_number}. Puedes seguirlo aquí: ${link}`,confirmed:`Hola ${name}. Tu pedido ${order.order_number} ya fue confirmado. Seguimiento: ${link}`,preparing:`Hola ${name}. Estamos preparando tu pedido ${order.order_number}. Seguimiento: ${link}`,dispatched:`Hola ${name}. Tu pedido ${order.order_number} ya salió para entrega. Seguimiento: ${link}`,delivered:`Hola ${name}. Tu pedido ${order.order_number} figura como entregado. ¡Gracias!`,cancelled:`Hola ${name}. El pedido ${order.order_number} fue cancelado. Si necesitas ayuda, escríbenos.`};return map[status]||`Tu pedido ${order.order_number} fue actualizado. ${link}`};
  function miniToast(title,copy=''){const old=$('.v5-notification-toast');old?.remove();const el=document.createElement('div');el.className='v5-notification-toast';el.innerHTML=`<span>🔔</span><div><b>${title}</b><small>${copy}</small></div>`;document.body.append(el);setTimeout(()=>el.remove(),4200)}
  function notifyNewOrders(next){
    const newOnes=next.filter(o=>o.status==='new');
    if(state.firstBootstrap){state.firstBootstrap=false;return}
    const previous=new Set(state.orders.filter(o=>o.status==='new').map(o=>o.id));const fresh=newOnes.filter(o=>!previous.has(o.id));if(!fresh.length)return;
    miniToast(`${fresh.length} pedido${fresh.length===1?' nuevo':'s nuevos'}`,fresh[0].customer_business||fresh[0].customer_name||'Revisa el panel');
    if('Notification'in window&&Notification.permission==='granted')try{const n=new Notification(`${fresh.length} pedido${fresh.length===1?' nuevo':'s nuevos'}`,{body:`${fresh[0].customer_business||fresh[0].customer_name||'Cliente'} · ${fresh[0].order_number}`,icon:'/assets/brand-mark.svg',tag:'kiubo-new-order'});n.onclick=()=>{window.focus();$('[data-nav="orders"]')?.click()}}catch{}
  }
  function readPresentationRows(){
    return $$('.v5-presentation-row').map((row,index)=>({id:row.dataset.id||null,name:$('[data-p-name]',row)?.value.trim()||'',unit_label:$('[data-p-unit]',row)?.value.trim()||'unidad',units_per_presentation:Math.max(1,Math.trunc(Number($('[data-p-units]',row)?.value||1))),price:Math.max(0,Number($('[data-p-price]',row)?.value||0)),compare_at_price:null,sku:null,visible:true,is_default:Boolean($('[data-p-default]',row)?.checked),sort_order:index})).filter(x=>x.name);
  }
  function readStock(){return {stock_tracking:Boolean($('#v5StockTracking')?.checked),stock_quantity:Math.max(0,Math.trunc(Number($('#v5StockQuantity')?.value||0))),low_stock_threshold:Math.max(0,Math.trunc(Number($('#v5LowThreshold')?.value||5))),base_unit:$('#v5BaseUnit')?.value.trim()||'unidad',allow_item_note:$('#v5AllowNote')?.checked!==false}}
  window.fetch=async(input,init={})=>{
    const url=typeof input==='string'?input:input?.url||'';let body=url===config.apiUrl?parse(init):null;let nextInit=init;let pendingStock=null;
    if(body?.action==='save_product'&&$('#productModal')&&!$('#productModal').hidden){const ps=readPresentationRows();pendingStock=readStock();body={...body,presentations:ps};nextInit={...init,body:JSON.stringify(body)}}
    const res=await nativeFetch(input,nextInit);
    if(url===config.apiUrl&&body){try{const payload=await res.clone().json();if(res.ok&&['provider_bootstrap','master_bootstrap'].includes(body.action)){notifyNewOrders(payload.orders||[]);state.products=payload.products||[];state.presentations=payload.presentations||[];state.orders=payload.orders||[];requestAnimationFrame(()=>{decorateProducts();ensureTools()})}if(res.ok&&body.action==='save_product'&&payload.id&&pendingStock){const headers=new Headers(nextInit.headers||{});headers.set('Content-Type','application/json');const stockRes=await nativeFetch(config.apiUrl,{method:'POST',headers,body:JSON.stringify({action:'save_stock',slug,product_id:payload.id,...pendingStock})});if(!stockRes.ok)miniToast('Producto guardado','Revisa el stock: no pudo actualizarse.')}}catch{}}
    return res;
  };
  function ensureEditor(){
    const form=$('#productForm');if(!form||$('#v5ProductEditor'))return;
    const box=document.createElement('section');box.id='v5ProductEditor';box.className='v5-product-editor';box.innerHTML=`<div class="v5-editor-head"><div><b>Venta e inventario</b><small>Configura cómo compra el cliente: unidad, pack, caja, jaba u otras presentaciones.</small></div><label class="v5-switch"><span style="font-size:10px;font-weight:800">Stock</span><input id="v5StockTracking" type="checkbox"></label></div><div class="v5-stock-grid"><label class="field"><span>Unidad base</span><input id="v5BaseUnit" maxlength="40" placeholder="botella, unidad, funda"></label><label class="field"><span>Stock disponible</span><input id="v5StockQuantity" type="number" min="0" step="1" inputmode="numeric" value="0"></label><label class="field"><span>Aviso de pocas</span><input id="v5LowThreshold" type="number" min="0" step="1" inputmode="numeric" value="5"></label></div><label class="v5-switch" style="justify-content:flex-start"><input id="v5AllowNote" type="checkbox" checked><span style="font-size:11px"><b>Permitir observación por producto</b><br><small style="color:#7b867e">Útil para sabor, color, modelo o surtido.</small></span></label><div class="v5-presentations"><div class="v5-presentations-head"><h4>Presentaciones de venta</h4><button type="button" class="v5-add-presentation" id="v5AddPresentation">+ Agregar presentación</button></div><div id="v5PresentationRows"></div><p class="v5-presentation-note">Ejemplo Coca-Cola: “Unidad” = 1 botella y “Jaba x 24” = 24 botellas. El stock se descuenta en unidades base.</p></div>`;
    const status=$('#productStatus')?.closest('.field');form.insertBefore(box,status||form.lastElementChild);$('#v5AddPresentation').onclick=()=>addPresentationRow();$('#v5StockTracking').onchange=syncStockDisabled;state.editorReady=true;
  }
  function rowTemplate(p={}){return `<div class="v5-presentation-row" data-id="${p.id||''}"><label>Nombre<input data-p-name maxlength="80" value="${esc(p.name||'')}" placeholder="Ej. Jaba x 24"></label><label>Unidades<input data-p-units type="number" min="1" step="1" inputmode="numeric" value="${Number(p.units_per_presentation||1)}"></label><label>Precio<input data-p-price type="number" min="0" step="0.01" inputmode="decimal" value="${Number(p.price??0)}"></label><label>Etiqueta<input data-p-unit maxlength="40" value="${esc(p.unit_label||'unidad')}" placeholder="unidad"></label><label class="v5-default"><input data-p-default type="radio" name="v5DefaultPresentation" ${p.is_default?'checked':''}><span style="font-size:9px;font-weight:800">Principal</span></label><button type="button" class="v5-remove-presentation" aria-label="Eliminar">×</button></div>`}
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function bindRows(){ $$('.v5-remove-presentation').forEach(b=>b.onclick=()=>{if($$('.v5-presentation-row').length<=1)return miniToast('Debe existir una presentación');b.closest('.v5-presentation-row').remove();if(!$('.v5-presentation-row [data-p-default]:checked'))$('.v5-presentation-row [data-p-default]').checked=true}) }
  function addPresentationRow(p={name:'Unidad',units_per_presentation:1,price:Number($('#productPrice')?.value||0),unit_label:$('#v5BaseUnit')?.value||'unidad'}){const rows=$('#v5PresentationRows');rows.insertAdjacentHTML('beforeend',rowTemplate(p));if($$('.v5-presentation-row').length===1)$('.v5-presentation-row [data-p-default]').checked=true;bindRows()}
  function syncStockDisabled(){const on=$('#v5StockTracking')?.checked;['#v5StockQuantity','#v5LowThreshold'].forEach(s=>{if($(s))$(s).disabled=!on});if($('#productStatus'))$('#productStatus').disabled=Boolean(on)}
  function hydrateEditor(id=''){
    ensureEditor();state.activeProductId=id||'';const p=product(id);const ps=p?presentations(p.id):[];$('#v5BaseUnit').value=p?.base_unit||'unidad';$('#v5StockTracking').checked=Boolean(p?.stock_tracking);$('#v5StockQuantity').value=String(Math.max(0,Number(p?.stock_quantity||0)));$('#v5LowThreshold').value=String(Math.max(0,Number(p?.low_stock_threshold??5)));$('#v5AllowNote').checked=p?.allow_item_note!==false;const rows=$('#v5PresentationRows');rows.innerHTML='';(ps.length?ps:[{name:p?.unit||'Unidad',units_per_presentation:1,price:Number(p?.price||0),unit_label:p?.base_unit||'unidad',is_default:true}]).forEach(addPresentationRow);syncStockDisabled();
  }
  function decorateProducts(){
    $$('#adminProductList .admin-product').forEach(row=>{if(row.dataset.v5Done)return;const name=$('.admin-product__copy h3',row)?.textContent?.trim();const p=state.products.find(x=>String(x.name).trim()===name);if(!p)return;row.dataset.v5Done='1';const copy=$('.admin-product__copy',row);const stock=document.createElement('span');stock.className=`v5-stock-badge ${p.stock_tracking?'':'manual'}`;stock.textContent=p.stock_tracking?`Stock: ${Number(p.stock_quantity||0)} ${p.base_unit||'unid.'}`:'Stock manual';copy?.append(stock);const count=presentations(p.id).length;if(count>1){const badge=document.createElement('span');badge.className='v5-presentation-badge';badge.textContent=`${count} presentaciones`;copy?.append(badge)}})
  }
  function ensureTools(){
    const actions=$('.topbar-actions');if(!actions||$('#v5NotifyBtn'))return;const wrap=document.createElement('div');wrap.className='v5-tools';wrap.innerHTML=`<button class="v5-tool-btn" id="v5NotifyBtn">Avisos</button><button class="v5-tool-btn" id="v5InstallBtn">Instalar</button>`;actions.prepend(wrap);$('#v5NotifyBtn').onclick=enableNotifications;$('#v5InstallBtn').onclick=installPanel;refreshToolState();
  }
  async function enableNotifications(){if(!('Notification'in window))return miniToast('Avisos no disponibles','Este navegador no admite notificaciones.');if(Notification.permission==='granted')return miniToast('Avisos activados','Te avisaremos si llega un pedido mientras el panel esté activo.');const p=await Notification.requestPermission();refreshToolState();miniToast(p==='granted'?'Avisos activados':'Permiso no concedido',p==='granted'?'Listo para nuevos pedidos.':'Puedes activarlo después desde el navegador.')}
  function refreshToolState(){const b=$('#v5NotifyBtn');if(b)b.classList.toggle('active','Notification'in window&&Notification.permission==='granted')}
  function installPanel(){if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone)return miniToast('Panel instalado','Ya estás usando la aplicación.');if(state.deferredInstall){state.deferredInstall.prompt();return}const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);miniToast('Instalar panel',ios?'En Safari: Compartir → Añadir a pantalla de inicio.':'Abre el menú del navegador y elige Instalar aplicación.')}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;ensureTools()});
  function enhanceOrderModal(){
    const title=$('#orderModalTitle')?.textContent?.trim(),content=$('#orderModalContent');if(!title||!content)return;const order=state.orders.find(o=>String(o.order_number)===title);if(!order)return;
    $$('.order-detail-item',content).forEach((row,i)=>{const item=order.items?.[i],copy=$('span',row);if(!item||!copy||copy.dataset.v5OrderInfo)return;copy.dataset.v5OrderInfo='1';const meta=document.createElement('small');meta.style.cssText='display:block;color:var(--muted);margin-top:4px;font-size:10px';meta.textContent=[item.presentation_name,item.item_note?`Obs.: ${item.item_note}`:''].filter(Boolean).join(' · ');if(meta.textContent)copy.append(meta)});
    const actions=$('.order-detail-actions',content);if(actions&&!$('#v5StatusWhatsapp',content)){const btn=document.createElement('button');btn.id='v5StatusWhatsapp';btn.className='button button--secondary';btn.type='button';btn.textContent='Avisar estado por WhatsApp';btn.onclick=()=>{const status=$('#modalOrderStatus',content)?.value||order.status;const phone=phone593(order.customer_phone);window.open(`https://wa.me/${phone}?text=${encodeURIComponent(statusMessage(order,status))}`,'_blank','noopener')};actions.append(btn)}
  }
  function trapBack(){if(history.state?.kiuboPanel)return;history.replaceState({kiuboRoot:true},'',location.href);history.pushState({kiuboPanel:true},'',location.href);window.addEventListener('popstate',()=>{const modal=$('.admin-modal.visible');if(modal)$('[data-close-modal]',modal)?.click();else{const home=$('[data-nav="home"]');if(home&&!home.classList.contains('active'))home.click();else{const tip=document.createElement('div');tip.className='v5-back-tip';tip.textContent='Panel protegido · usa “Cerrar sesión” para salir';document.body.append(tip);setTimeout(()=>tip.remove(),1800)}}history.pushState({kiuboPanel:true},'',location.href)})}
  document.addEventListener('click',e=>{const edit=e.target.closest?.('[data-edit-product]');const fresh=e.target.closest?.('#newProductBtn,#mobileCreateBtn');if(edit||fresh){state.activeProductId=edit?.dataset.editProduct||'';setTimeout(()=>hydrateEditor(state.activeProductId),20)}const order=e.target.closest?.('[data-open-order]');if(order)setTimeout(enhanceOrderModal,30)},true);
  const start=()=>{ensureEditor();ensureTools();trapBack();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});const observer=new MutationObserver(()=>{if(!$('#productModal')?.hidden&&state.editorReady&&$('#v5PresentationRows')?.children.length===0)hydrateEditor(state.activeProductId);if($('#orderModal')?.classList.contains('visible'))enhanceOrderModal()});observer.observe(document.body,{childList:true,subtree:true});};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();