/* Hakuna Panel 10.5.1 — contextual order alerts, richer customer detail and safer mobile operation. */
(()=>{
'use strict';
if(window.__hakunaPanel1051)return;window.__hakunaPanel1051=true;
if(!/^\/panel(?:\/|$)/.test(location.pathname))return;
const C=window.KIUBO_CATALOG_CONFIG||{};if(!C.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const SNAP=`hm1051-panel-orders:${slug}`;
const statusLabel=s=>({new:'nuevo',confirmed:'confirmado',preparing:'en preparación',dispatched:'despachado',delivered:'entregado',cancelled:'cancelado'})[s]||'actualizado';
const read=()=>{try{return JSON.parse(localStorage.getItem(SNAP)||'null')}catch{return null}};
const write=v=>{try{localStorage.setItem(SNAP,JSON.stringify(v))}catch{}};
const notifySupported=()=>('Notification'in window);
const notifyGranted=()=>notifySupported()&&Notification.permission==='granted';
function notify(title,body,tag){if(!notifyGranted())return;try{new Notification(title,{body,tag,icon:C.brandLogoUrl||undefined,badge:C.brandLogoUrl||undefined})}catch{}}
function compareOrders(next){const old=read();if(!old){write(next.map(o=>({id:o.id,status:o.status,order_number:o.order_number,customer:o.customer_business||o.customer_name,total:o.total})));return}const prev=new Map(old.map(o=>[String(o.id),o]));for(const o of next){const p=prev.get(String(o.id));if(!p){notify('Nuevo pedido en Hakuna',`${o.customer_business||o.customer_name||'Cliente'} · ${o.order_number||''}`,`hakuna-new-${o.id}`)}else if(p.status!==o.status){notify(`Pedido ${o.order_number||''}`,`Ahora está ${statusLabel(o.status)}.`,`hakuna-status-${o.id}`)}}write(next.map(o=>({id:o.id,status:o.status,order_number:o.order_number,customer:o.customer_business||o.customer_name,total:o.total})))}
const upstream=window.fetch.bind(window);
window.fetch=async(input,init={})=>{const res=await upstream(input,init),url=typeof input==='string'?input:input?.url||'';let body=null;if(url===C.apiUrl&&typeof init?.body==='string'){try{body=JSON.parse(init.body)}catch{}}if(res.ok&&body&&['provider_bootstrap','master_bootstrap'].includes(body.action))res.clone().json().then(p=>{if(Array.isArray(p.orders))compareOrders(p.orders)}).catch(()=>{});return res};
function notificationCard(){if(!notifySupported())return;const home=$('[data-view="home"].admin-view');if(!home||$('.hm1051-panel-notify',home))return;const welcome=$('.welcome-card',home);if(!welcome)return;const card=document.createElement('section');card.className='hm1051-panel-notify';const state=Notification.permission;card.innerHTML=state==='granted'?'<span>🔔</span><div><b>Avisos de pedidos activados</b><small>Mientras el panel esté abierto o activo, te avisaremos de pedidos nuevos y cambios.</small></div>':state==='denied'?'<span>🔕</span><div><b>Avisos bloqueados</b><small>Puedes habilitarlos desde los permisos del navegador.</small></div>':'<span>🔔</span><div><b>Activa avisos de pedidos</b><small>Mayra puede recibir alertas de pedidos nuevos mientras usa el panel.</small></div><button type="button" data-hm1051-panel-notify>Activar</button>';welcome.insertAdjacentElement('afterend',card)}
document.addEventListener('click',async e=>{if(e.target.closest?.('[data-hm1051-panel-notify]')){e.preventDefault();try{await Notification.requestPermission()}catch{}$('.hm1051-panel-notify')?.remove();notificationCard()}},true);
function enrichCustomerModal(){const modal=$('#hm105CustomerModal');if(!modal||modal.hidden||modal.dataset.hm1051)return;const body=$('#hm105CustomerBody',modal),title=$('#hm105CustomerTitle',modal)?.textContent?.trim();if(!body||!title)return;const cards=$$('#customerList .customer-card');const card=cards.find(c=>c.dataset.hm105Customer==='1'&&$('h3',c)?.textContent?.trim()===title);let phone='';if(card)phone=String($('p',card)?.textContent||'').replace(/\D/g,'').slice(-9);if(!phone)return;const rows=(read()?.length?[]:[]); /* keep render independent from internal app state */
 const cache=[];try{const raw=window.__hm1051LastOrders;if(Array.isArray(raw))cache.push(...raw)}catch{}
 const orders=cache.filter(o=>String(o.customer_phone||'').replace(/\D/g,'').endsWith(phone)).slice(0,4);if(!orders.length)return;modal.dataset.hm1051='1';const section=document.createElement('section');section.className='hm1051-customer-orders';section.innerHTML='<div><b>Últimos pedidos</b><small>Historial reciente de este cliente</small></div>'+orders.map(o=>`<button type="button" data-hm1051-order="${String(o.id).replace(/"/g,'')}"><span><b>${o.order_number||'Pedido'}</b><small>${statusLabel(o.status)}</small></span><strong>${new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(o.total||0))}</strong></button>`).join('');body.append(section)}
/* Keep a lightweight order snapshot for customer detail without coupling to legacy panel internals. */
const priorFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const res=await priorFetch(input,init),url=typeof input==='string'?input:input?.url||'';let b=null;if(url===C.apiUrl&&typeof init?.body==='string'){try{b=JSON.parse(init.body)}catch{}}if(res.ok&&b&&['provider_bootstrap','master_bootstrap'].includes(b.action))res.clone().json().then(p=>{if(Array.isArray(p.orders))window.__hm1051LastOrders=p.orders}).catch(()=>{});return res};
function removeNativeSearchCancel(){['productSearch','orderSearch','customerSearch'].forEach(id=>{const input=$(`#${id}`);if(input)input.setAttribute('autocomplete','off')})}
function enhance(){notificationCard();enrichCustomerModal();removeNativeSearchCancel();document.documentElement.dataset.hmPanel='10.5.1'}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});document.addEventListener('click',schedule,true);window.addEventListener('pageshow',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
