/* Hakuna Panel 10.5 — delivery hardening for Mayra: clear editor, reliable search, simpler orders/customers. */
(()=>{
'use strict';
if(window.__hakunaPanel105)return;window.__hakunaPanel105=true;
if(!/^\/panel(?:\/|$)/.test(location.pathname))return;
const C=window.KIUBO_CATALOG_CONFIG||{};if(!C.apiUrl)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const slug=(new URLSearchParams(location.search).get('slug')||C.defaultSlug||'hakuna-matata').toLowerCase().replace(/[^a-z0-9-]/g,'');
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const snapshot={customers:[],orders:[],account:null};
const upstream=window.fetch.bind(window);
const parse=init=>{try{return typeof init?.body==='string'?JSON.parse(init.body):null}catch{return null}};
window.fetch=async(input,init={})=>{const res=await upstream(input,init),url=typeof input==='string'?input:input?.url||'',body=url===C.apiUrl?parse(init):null;if(res.ok&&body&&['provider_bootstrap','master_bootstrap'].includes(body.action)){res.clone().json().then(p=>{if(Array.isArray(p.customers))snapshot.customers=p.customers;if(Array.isArray(p.orders))snapshot.orders=p.orders;if(p.account)snapshot.account=p.account}).catch(()=>{})}return res};
function fmtMoney(v){try{return new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(v||0))}catch{return`$${Number(v||0).toFixed(2)}`}}
function fmtDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('es-EC',{dateStyle:'medium'}).format(new Date(v))}catch{return String(v)}}
function hardResetSearch(id){const input=$(`#${id}`);if(!input||input.value.trim())return;input.dispatchEvent(new Event('input',{bubbles:true,composed:true}));input.dispatchEvent(new Event('change',{bubbles:true}));if(id==='productSearch')$('[data-product-filter].active')?.click();if(id==='orderSearch')$('[data-order-filter].active')?.click();if(id==='customerSearch')$('[data-nav="customers"].active')?.click();setTimeout(()=>{if(id==='productSearch'&&!input.value.trim()&&!$('#adminProductList .admin-product'))$('#refreshBtn')?.click()},420)}
['input','search','change'].forEach(type=>document.addEventListener(type,e=>{if(!['productSearch','orderSearch','customerSearch'].includes(e.target?.id))return;if(!e.target.value.trim())setTimeout(()=>hardResetSearch(e.target.id),0)},true));
document.addEventListener('click',e=>{const clear=e.target.closest?.('.v1033-search-clear');if(clear){const input=clear.closest('.admin-search')?.querySelector('input');if(input)setTimeout(()=>hardResetSearch(input.id),0)}},true);

function photoIntro(modal,rows){let intro=$('.hm105-photo-intro',modal);if(!intro){intro=document.createElement('div');intro.className='hm105-photo-intro';intro.innerHTML='<span>📷</span><div><b>Fotos por forma de venta</b><small>Sube una sola foto en Unidad, Caja, Jaba, etc. La presentación predeterminada será la portada.</small></div>';const rowsRoot=$('#v5PresentationRows',modal);rowsRoot?.insertAdjacentElement('beforebegin',intro)}const general=$('.product-image-upload',modal),saved=rows.some(r=>uuid(r.dataset.id));if(general){general.hidden=saved;general.classList.toggle('hm105-general-only',!saved);const b=$('label b',general),s=$('label small',general);if(!saved){if(b)b.textContent='Foto inicial del producto';if(s)s.textContent='Úsala solo al crear el producto. Después administra las fotos en cada forma de venta.'}}$('.hm1042-photo-guide',modal)?.setAttribute('hidden','');}
function decoratePhotoRows(modal,rows){rows.forEach(row=>{const box=$('.v77-presentation-image',row);if(!box)return;const name=$('[data-p-name]',row)?.value?.trim()||'Presentación',def=$('[data-p-default]',row)?.checked;const title=$('.v77-presentation-image-copy b',box),small=$('.v77-presentation-image-copy small',box);if(title)title.textContent=`Foto de ${name}`;if(small&&!row.matches('[data-hm-photo-state="saving"]'))small.textContent=def?'Esta foto también será la portada principal.':'Foto propia para esta forma de venta.'})}
function unlockEditor(){const modal=$('#productModal');if(!modal||modal.hidden)return;modal.style.pointerEvents='auto';const back=$('#modalBackdrop');if(back)back.style.pointerEvents='auto';$$('#productModal button,#productModal input,#productModal select,#productModal textarea,#productModal label').forEach(el=>{if(el.dataset.hm105Disabled==='1'){el.disabled=false;delete el.dataset.hm105Disabled}})}
function decorateEditor(){const modal=$('#productModal');if(!modal||modal.hidden)return;modal.classList.add('hm105-product-modal');const rows=$$('#v5PresentationRows .v5-presentation-row',modal);photoIntro(modal,rows);decoratePhotoRows(modal,rows);unlockEditor()}
document.addEventListener('change',e=>{if(e.target?.type==='file'&&e.target.closest?.('#productModal')){[250,700,1500,3000,5000].forEach(ms=>setTimeout(unlockEditor,ms))}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#productModal')?.hidden)$('#productModal [data-close-modal]')?.click()},true);

function simplifyOrder(){const modal=$('#orderModal');if(!modal||modal.hidden)return;const content=$('#orderModalContent',modal),select=$('#modalOrderStatus',content);if(!content)return;let guide=$('.hm105-order-guide',content);if(!guide){guide=document.createElement('div');guide.className='hm105-order-guide';guide.innerHTML='<b>Gestiona el pedido en 3 pasos</b><span>1. Revisa productos · 2. Elige el estado · 3. Guarda y avisa al cliente.</span>';content.prepend(guide)}if(select){const labels={new:'Recibido · por revisar',confirmed:'Confirmado',preparing:'Preparando pedido',dispatched:'Despachado / en camino',delivered:'Entregado',cancelled:'Cancelado'};[...select.options].forEach(o=>{if(labels[o.value])o.textContent=labels[o.value]});select.setAttribute('aria-label','Estado del pedido')}const actions=$('.order-detail-actions',content);if(actions&&!$('.hm105-order-actions-title',actions)){const t=document.createElement('div');t.className='hm105-order-actions-title';t.innerHTML='<b>¿Qué quieres hacer ahora?</b><small>Guardar estado mantiene el historial; WhatsApp abre el aviso listo para enviar.</small>';actions.prepend(t)}const wa=$('#v6OrderWhatsapp',content);if(wa){wa.classList.add('hm105-order-save');wa.setAttribute('title','Guarda el estado y abre WhatsApp con el mensaje preparado')}}

function ensureCustomerModal(){if($('#hm105CustomerModal'))return;const back=document.createElement('div');back.id='hm105CustomerBackdrop';back.className='hm105-customer-backdrop';back.hidden=true;const modal=document.createElement('section');modal.id='hm105CustomerModal';modal.className='hm105-customer-modal';modal.hidden=true;modal.innerHTML='<header><div><small>CLIENTE</small><h2 id="hm105CustomerTitle">Detalle</h2></div><button type="button" id="hm105CustomerClose" aria-label="Cerrar">×</button></header><div id="hm105CustomerBody"></div>';document.body.append(back,modal);const close=()=>{back.hidden=true;modal.hidden=true};back.onclick=close;$('#hm105CustomerClose',modal).onclick=close}
function openCustomer(c){ensureCustomerModal();const title=c.business||c.name||'Cliente',phone=String(c.phone||'').replace(/\D/g,''),body=$('#hm105CustomerBody');$('#hm105CustomerTitle').textContent=title;body.innerHTML=`<div class="hm105-customer-head"><span>${esc((title||'?').slice(0,2).toUpperCase())}</span><div><b>${esc(title)}</b><small>${esc(c.name||'Contacto')}</small></div></div><div class="hm105-customer-stats"><span><b>${Number(c.order_count||0)}</b><small>Pedidos válidos</small></span><span><b>${fmtMoney(c.total_spent)}</b><small>Total comprado</small></span></div><div class="hm105-customer-info"><p><b>WhatsApp</b><span>${phone?`+${esc(phone)}`:'Sin número'}</span></p><p><b>Primer pedido</b><span>${esc(fmtDate(c.first_order_at))}</span></p><p><b>Último pedido</b><span>${esc(fmtDate(c.last_order_at))}</span></p></div>${phone?`<a class="hm105-customer-wa" href="https://wa.me/${encodeURIComponent(phone)}" target="_blank" rel="noopener">Abrir WhatsApp</a>`:''}`;$('#hm105CustomerBackdrop').hidden=false;$('#hm105CustomerModal').hidden=false}
function decorateCustomers(){const cards=$$('#customerList .customer-card');if(!cards.length||!snapshot.customers.length)return;cards.forEach(card=>{if(card.dataset.hm105Customer)return;const title=norm($('h3',card)?.textContent),phone=String($('p',card)?.textContent||'').replace(/\D/g,'');const c=snapshot.customers.find(x=>norm(x.business||x.name)===title||phone.endsWith(String(x.phone||'').replace(/\D/g,'').slice(-8)));if(!c)return;card.dataset.hm105Customer='1';card.tabIndex=0;card.setAttribute('role','button');card.addEventListener('click',()=>openCustomer(c));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openCustomer(c)}})})}

function explainBusiness(){const wa=$('#businessWhatsapp');if(wa&&!wa.dataset.hm105){wa.dataset.hm105='1';wa.insertAdjacentHTML('afterend','<small class="hm105-field-help">Aquí llegará el contacto de los pedidos y puede cambiarse cuando lo necesites.</small>')}const pay=$('#v6PaymentsPanel .panel-card header p');if(pay)pay.textContent='Activa solo lo que Mayra realmente acepta. Transferencia mostrará los datos bancarios al cliente.'}
function pwaMeta(){let theme=$('meta[name="theme-color"]');if(theme)theme.content='#ffffff';else{theme=document.createElement('meta');theme.name='theme-color';theme.content='#ffffff';document.head.append(theme)}let status=$('meta[name="apple-mobile-web-app-status-bar-style"]');if(status)status.content='default';}
function enhance(){decorateEditor();simplifyOrder();decorateCustomers();explainBusiness();pwaMeta();document.documentElement.dataset.hmPanel='10.5'}
let raf=0;const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhance()})};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});document.addEventListener('click',schedule,true);document.addEventListener('input',schedule,true);window.addEventListener('pageshow',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
