from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]

def read(path): return (ROOT/path).read_text()
def write(path,text): (ROOT/path).write_text(text)
def rep(text,old,new,label):
    count=text.count(old)
    if count!=1: raise RuntimeError(f"{label}: expected 1 occurrence, found {count}")
    return text.replace(old,new,1)

# --- local-store types / normalization -------------------------------------------------
p=Path("lib/local-store.ts"); t=read(p)
t=rep(t,
'export type FoodOrderItem = { productId:string; name:string; qty:number; unitPrice:number; notes?:string };',
'export type FoodOrderItem = { productId:string; name:string; qty:number; unitPrice:number; notes?:string; courtesy?:boolean };',
'food item courtesy')
t=rep(t,
'export type FoodOrderRecord = { id:string; tenantId:string; branchId:string; number:number; serviceMode:ServiceMode; tableLabel?:string; customerId?:string; customerName?:string; phone?:string; address?:string; notes?:string; items:FoodOrderItem[]; total:number; status:FoodOrderStatus; paymentStatus:FoodOrderPaymentStatus; saleId?:string; createdBy?:string; createdAt:string; updatedAt:string };',
'export type FoodOrderRecord = { id:string; tenantId:string; branchId:string; number:number; serviceMode:ServiceMode; tableLabel?:string; customerId?:string; customerName?:string; phone?:string; address?:string; notes?:string; items:FoodOrderItem[]; total:number; status:FoodOrderStatus; paymentStatus:FoodOrderPaymentStatus; saleId?:string; createdBy?:string; discountPercent?:number; internalConsumption?:boolean; createdAt:string; updatedAt:string };',
'food order operational fields')
t=rep(t,
'export type TenantSettings = { tenantId:string; tradeName:string; legalName:string; ruc:string; establishment:string; emissionPoint:string; currency:"USD"; accent:string; receiptFooter:string; requireCashSession:boolean; allowCredit:boolean; address:string; phone:string; businessType:BusinessType; serviceModes:ServiceMode[]; tableCount:number; showProductImages:boolean; splashEnabled:boolean; receiptWidth:"58mm"|"80mm" };',
'export type TenantSettings = { tenantId:string; tradeName:string; legalName:string; ruc:string; establishment:string; emissionPoint:string; currency:"USD"; accent:string; receiptFooter:string; requireCashSession:boolean; allowCredit:boolean; address:string; phone:string; businessType:BusinessType; serviceModes:ServiceMode[]; tableCount:number; categoryOrder?:string[]; showProductImages:boolean; splashEnabled:boolean; receiptWidth:"58mm"|"80mm" };',
'settings category order')
t=rep(t,
'    tableCount:Math.max(0,Math.min(500,Math.floor(Number(item.tableCount)||0))),\n    showProductImages:item.showProductImages!==false,',
'    tableCount:Math.max(0,Math.min(500,Math.floor(Number(item.tableCount)||0))),\n    categoryOrder:Array.isArray(item.categoryOrder)?[...new Set(item.categoryOrder.map(value=>safeSingleLine(value,80)).filter(Boolean))].slice(0,100):undefined,\n    showProductImages:item.showProductImages!==false,',
'normalize category order')
t=rep(t,
'    notes:safeSingleLine(order.notes,500)||undefined,total:safeProductNumber(order.total),\n    items:Array.isArray(order.items)?order.items.map(item=>({productId:String(item.productId||""),name:safeSingleLine(item.name,160)||"Producto",qty:Math.max(1,Math.floor(Number(item.qty)||1)),unitPrice:safeProductNumber(item.unitPrice),notes:safeSingleLine(item.notes,240)||undefined})):[],\n    createdAt:String(order.createdAt||new Date().toISOString()),updatedAt:String(order.updatedAt||order.createdAt||new Date().toISOString())',
'    notes:safeSingleLine(order.notes,500)||undefined,total:safeProductNumber(order.total),\n    discountPercent:Math.max(0,Math.min(100,Number(order.discountPercent)||0))||undefined,internalConsumption:Boolean(order.internalConsumption)||undefined,\n    items:Array.isArray(order.items)?order.items.map(item=>({productId:String(item.productId||""),name:safeSingleLine(item.name,160)||"Producto",qty:Math.max(1,Math.floor(Number(item.qty)||1)),unitPrice:safeProductNumber(item.unitPrice),notes:safeSingleLine(item.notes,240)||undefined,courtesy:Boolean(item.courtesy)||undefined})):[],\n    createdAt:String(order.createdAt||new Date().toISOString()),updatedAt:String(order.updatedAt||order.createdAt||new Date().toISOString())',
'normalize operational order')
write(p,t)

# --- POS ------------------------------------------------------------------------------
p=Path("components/PosClientPro.tsx"); t=read(p)
t=rep(t,
'import { mixedCashMovementReason,normalizePaymentBreakdown,type SaleWithPaymentBreakdown } from "@/lib/mixed-payment";\nimport { tableLabelsFromSettings } from "@/lib/table-settings";',
'import { mixedCashMovementReason,normalizePaymentBreakdown,type SaleWithPaymentBreakdown } from "@/lib/mixed-payment";\nimport { clampDiscount,effectiveUnitPrice,encodeOperationalItemName,parseOperationalItemName } from "@/lib/sale-adjustments";\nimport { tableLabelsFromSettings } from "@/lib/table-settings";',
'pos sale adjustment import')
t=rep(t,
'type CartLine=TenantProduct&{qty:number;cartKey:string;optionLabel?:string;optionSelections?:string[]};\ntype Payment=SaleRecord["payment"];\ntype PosDraft={cart:Array<{productId:string;qty:number;optionLabel?:string;optionSelections?:string[]}>;query:string;payment:Payment;mixedCash:string;customerId:string;category:string;serviceMode:ServiceMode;tableLabel:string;customerName:string;phone:string;address:string;orderNotes:string;activeOrderId:string};\ntype SaleSuccess={amount:number;method:string;context:string};',
'type CartLine=TenantProduct&{qty:number;cartKey:string;optionLabel?:string;optionSelections?:string[];lineMode?:"sale"|"courtesy"};\ntype Payment=SaleRecord["payment"];\ntype PosDraft={cart:Array<{productId:string;qty:number;optionLabel?:string;optionSelections?:string[];lineMode?:"sale"|"courtesy"}>;query:string;payment:Payment;mixedCash:string;cashReceived:string;discountPercent:number;internalConsumption:boolean;customerId:string;category:string;serviceMode:ServiceMode;tableLabel:string;customerName:string;phone:string;address:string;orderNotes:string;activeOrderId:string};\ntype SaleSuccess={amount:number;method:string;context:string;change?:number};',
'pos types')
t=rep(t,
'  const[mixedCash,setMixedCash]=useState("");\n  const[customerId,setCustomerId]=useState("");',
'  const[mixedCash,setMixedCash]=useState("");\n  const[cashReceived,setCashReceived]=useState("");\n  const[discountPercent,setDiscountPercent]=useState(0);\n  const[customDiscount,setCustomDiscount]=useState("");\n  const[internalConsumption,setInternalConsumption]=useState(false);\n  const[dragCategory,setDragCategory]=useState("");\n  const[dragOverCategory,setDragOverCategory]=useState("");\n  const[customerId,setCustomerId]=useState("");',
'pos states')
t=rep(t,
'lines.push({...product,qty:product.trackStock===false?qty:Math.min(qty,Math.max(1,product.stock)),cartKey:cartKeyFor(product.id,saved.optionLabel),optionLabel:saved.optionLabel,optionSelections:selections})',
'lines.push({...product,qty:product.trackStock===false?qty:Math.min(qty,Math.max(1,product.stock)),cartKey:cartKeyFor(product.id,saved.optionLabel),optionLabel:saved.optionLabel,optionSelections:selections,lineMode:saved.lineMode==="courtesy"?"courtesy":"sale"})',
'restore courtesy')
t=rep(t,
'&&(draftMode==="table"?(order.serviceMode==="table"&&order.tableLabel===draftTable):order.serviceMode===draftMode)',
'&&((draftMode==="table"||draftMode==="delivery")?(order.serviceMode===draftMode&&order.tableLabel===draftTable):order.serviceMode===draftMode)',
'draft context isolation')
t=rep(t,
'setPayment(draft.payment);setMixedCash(typeof draft.mixedCash==="string"?draft.mixedCash:"");setCustomerId',
'setPayment(draft.payment);setMixedCash(typeof draft.mixedCash==="string"?draft.mixedCash:"");setCashReceived(typeof draft.cashReceived==="string"?draft.cashReceived:"");setDiscountPercent(clampDiscount(Number(draft.discountPercent)||0));setInternalConsumption(Boolean(draft.internalConsumption));setCustomerId',
'restore adjustment draft')
t=rep(t,
'if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes,optionSelections:parseProductOptionSelection(getProductOptionConfig(product),item.notes)})',
'if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes,optionSelections:parseProductOptionSelection(getProductOptionConfig(product),item.notes),lineMode:item.courtesy?"courtesy":"sale"})',
'checkout order courtesy restore')
t=rep(t,
'setOrderNotes(order.notes||"");setMixedCash("");setMessage',
'setOrderNotes(order.notes||"");setMixedCash("");setCashReceived("");setDiscountPercent(clampDiscount(Number(order.discountPercent)||0));setInternalConsumption(Boolean(order.internalConsumption));setMessage',
'checkout order adjustments restore')
t=rep(t,
'const empty=cart.length===0&&!query.trim()&&payment==="cash"&&!mixedCash&&!customerId&&category==="Todos"&&serviceMode==="counter"',
'const empty=cart.length===0&&!query.trim()&&payment==="cash"&&!mixedCash&&!cashReceived&&!discountPercent&&!internalConsumption&&!customerId&&category==="Todos"&&serviceMode==="counter"',
'draft empty state')
t=rep(t,
'const draft:PosDraft={cart:cart.map(line=>({productId:line.id,qty:line.qty,optionLabel:line.optionLabel,optionSelections:line.optionSelections})),query,payment,mixedCash,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId};window.localStorage.setItem(key,JSON.stringify(draft));',
'const draft:PosDraft={cart:cart.map(line=>({productId:line.id,qty:line.qty,optionLabel:line.optionLabel,optionSelections:line.optionSelections,lineMode:line.lineMode==="courtesy"?"courtesy":"sale"})),query,payment,mixedCash,cashReceived,discountPercent,internalConsumption,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId};window.localStorage.setItem(key,JSON.stringify(draft));',
'draft payload')
t=rep(t,
'},[db,draftReady,cart,query,payment,mixedCash,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId]);',
'},[db,draftReady,cart,query,payment,mixedCash,cashReceived,discountPercent,internalConsumption,customerId,category,serviceMode,tableLabel,customerName,phone,address,orderNotes,activeOrderId]);',
'draft dependencies')
t=rep(t,
'  const customers:CustomerRecord[]=db.customers.filter(c=>c.tenantId===ctx.tenantId),categories=["Todos",...Array.from(new Set(products.map(product=>product.category||"General"))).sort((a,b)=>a.localeCompare(b,"es"))],filtered=products.filter(p=>(category==="Todos"||(p.category||"General")===category)&&`${p.name} ${p.barcode} ${p.price}`.toLowerCase().includes(query.toLowerCase()));',
'  const customers:CustomerRecord[]=db.customers.filter(c=>c.tenantId===ctx.tenantId),rawCategories=Array.from(new Set(products.map(product=>product.category||"General"))),savedCategoryOrder=(settings.categoryOrder||[]).filter(item=>rawCategories.includes(item)),orderedCategories=[...savedCategoryOrder,...rawCategories.filter(item=>!savedCategoryOrder.includes(item)).sort((a,b)=>a.localeCompare(b,"es"))],categories=["Todos",...orderedCategories],filtered=products.filter(p=>(category==="Todos"||(p.category||"General")===category)&&`${p.name} ${p.barcode} ${p.price}`.toLowerCase().includes(query.toLowerCase()));',
'category order data')
t=rep(t,
'  const subtotal=cart.reduce((sum,line)=>sum+line.price*line.qty,0),packagingFee=foodService&&packagingProduct&&(activeServiceMode==="takeaway"||activeServiceMode==="delivery")?packagingProduct.price:0,total=subtotal+packagingFee,blocked=tenant?.status==="suspended",cartCount=cart.reduce((sum,line)=>sum+line.qty,0);\n  const mixedCashNumber=Number(mixedCash),mixedBreakdown=normalizePaymentBreakdown(total,Number.isFinite(mixedCashNumber)?mixedCashNumber:0),mixedIsValid=payment!=="mixed"||(mixedBreakdown.cash>0&&mixedBreakdown.transfer>0);',
'  const subtotal=cart.reduce((sum,line)=>sum+line.price*line.qty,0),courtesySubtotal=cart.filter(line=>line.lineMode==="courtesy").reduce((sum,line)=>sum+line.price*line.qty,0),packagingFee=foodService&&packagingProduct&&(activeServiceMode==="takeaway"||activeServiceMode==="delivery")?packagingProduct.price:0,appliedDiscount=internalConsumption?0:clampDiscount(discountPercent),billableNet=cart.reduce((sum,line)=>sum+(line.lineMode==="courtesy"?0:effectiveUnitPrice(line.price,"sale",appliedDiscount)*line.qty),0),packagingNet=internalConsumption?0:effectiveUnitPrice(packagingFee,"sale",appliedDiscount),total=internalConsumption?0:Number((billableNet+packagingNet).toFixed(2)),discountBase=Math.max(0,subtotal-courtesySubtotal+packagingFee),discountAmount=internalConsumption?0:Number(Math.max(0,discountBase-total).toFixed(2)),blocked=tenant?.status==="suspended",cartCount=cart.reduce((sum,line)=>sum+line.qty,0);\n  const mixedCashNumber=Number(mixedCash),mixedBreakdown=normalizePaymentBreakdown(total,Number.isFinite(mixedCashNumber)?mixedCashNumber:0),mixedIsValid=internalConsumption||total<=0||payment!=="mixed"||(mixedBreakdown.cash>0&&mixedBreakdown.transfer>0),receivedNumber=Number(cashReceived),changeDue=payment==="cash"&&!internalConsumption&&total>0&&Number.isFinite(receivedNumber)&&receivedNumber>=total?Number((receivedNumber-total).toFixed(2)):0;',
'operational totals')
t=rep(t,
'  const findOpenServiceOrder=(source:ReturnType<typeof loadLocalDatabase>,workspace:ReturnType<typeof getWorkspaceContext>,mode:Exclude<ServiceMode,"table">)=>source.orders.filter(order=>isOpenOrder(order,workspace)&&order.serviceMode===mode).sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt))[0];',
'  const findOpenServiceOrder=(source:ReturnType<typeof loadLocalDatabase>,workspace:ReturnType<typeof getWorkspaceContext>,mode:Exclude<ServiceMode,"table">)=>source.orders.filter(order=>isOpenOrder(order,workspace)&&order.serviceMode===mode).sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt))[0];\n  const findOpenDeliveryOrder=(source:ReturnType<typeof loadLocalDatabase>,workspace:ReturnType<typeof getWorkspaceContext>,label:string)=>source.orders.filter(order=>isOpenOrder(order,workspace)&&order.serviceMode==="delivery"&&order.tableLabel===label).sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt))[0];',
'delivery finder')
t=rep(t,
'  const openTableOrders=db.orders.filter(order=>isOpenOrder(order,ctx)&&order.serviceMode==="table").sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt)),tableNumbers=tableLabelsFromSettings(settings);',
'  const openTableOrders=db.orders.filter(order=>isOpenOrder(order,ctx)&&order.serviceMode==="table").sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt)),openDeliveryOrders=db.orders.filter(order=>isOpenOrder(order,ctx)&&order.serviceMode==="delivery").sort((a,b)=>Date.parse(b.updatedAt||b.createdAt)-Date.parse(a.updatedAt||a.createdAt)),deliveryMax=Math.max(3,...openDeliveryOrders.map(order=>Number(order.tableLabel)||0)),deliveryLabels=Array.from({length:deliveryMax},(_,index)=>String(index+1)),tableNumbers=tableLabelsFromSettings(settings);',
'delivery slots')
# build-order / order persistence
t=rep(t,
'  const validateOrderDetails=()=>{if(!foodService)return true;if(activeServiceMode==="table"&&!tableLabel.trim()){setMessage("Selecciona una mesa para continuar");return false}return true};',
'  const validateOrderDetails=()=>{if(!foodService)return true;if(activeServiceMode==="table"&&!tableLabel.trim()){setMessage("Selecciona una mesa para continuar");return false}if(activeServiceMode==="delivery"&&!tableLabel.trim()){setMessage("Selecciona o crea un domicilio para continuar");return false}return true};',
'validate delivery slot')
t=rep(t,
'  const orderItemsFor=(mode:ServiceMode)=>[...cart.map(line=>({productId:line.id,name:line.optionLabel?`${line.name} · ${line.optionLabel}`:line.name,qty:line.qty,unitPrice:line.price,notes:line.optionLabel})),...(packagingFeeFor(mode)&&packagingProduct?[{productId:packagingProduct.id,name:"Envase",qty:1,unitPrice:packagingFeeFor(mode)}]:[])];',
'  const orderItemsFor=(mode:ServiceMode)=>[...cart.map(line=>({productId:line.id,name:line.optionLabel?`${line.name} · ${line.optionLabel}`:line.name,qty:line.qty,unitPrice:line.price,notes:line.optionLabel,courtesy:line.lineMode==="courtesy"||undefined})),...(packagingFeeFor(mode)&&packagingProduct?[{productId:packagingProduct.id,name:"Envase",qty:1,unitPrice:packagingFeeFor(mode)}]:[])];',
'order courtesy persistence')
t=rep(t,
'    const activeExisting=findActiveOpenOrder(next,workspace),activeMatches=activeExisting&&(activeServiceMode==="table"?activeExisting.serviceMode==="table"&&activeExisting.tableLabel===tableLabel.trim():activeExisting.serviceMode===activeServiceMode);\n    const contextExisting=activeServiceMode==="table"&&tableLabel.trim()?findOpenTableOrder(next,workspace,tableLabel.trim()):activeServiceMode!=="table"?findOpenServiceOrder(next,workspace,activeServiceMode):undefined;',
'    const activeExisting=findActiveOpenOrder(next,workspace),activeMatches=activeExisting&&((activeServiceMode==="table"||activeServiceMode==="delivery")?activeExisting.serviceMode===activeServiceMode&&activeExisting.tableLabel===tableLabel.trim():activeExisting.serviceMode===activeServiceMode);\n    const contextExisting=activeServiceMode==="table"&&tableLabel.trim()?findOpenTableOrder(next,workspace,tableLabel.trim()):activeServiceMode==="delivery"&&tableLabel.trim()?findOpenDeliveryOrder(next,workspace,tableLabel.trim()):activeServiceMode!=="table"&&activeServiceMode!=="delivery"?findOpenServiceOrder(next,workspace,activeServiceMode):undefined;',
'build order context isolation')
t=rep(t,
'return{id:existing?.id||makeId("order"),tenantId:workspace.tenantId,branchId:workspace.branchId,number:existing?.number||nextOrderNumber(next,workspace.tenantId,workspace.branchId),serviceMode:activeServiceMode,tableLabel:activeServiceMode==="table"?tableLabel.trim()||undefined:undefined,customerId:customerId||undefined,customerName:customerName.trim()||customers.find(c=>c.id===customerId)?.name||undefined,phone:phone.trim()||undefined,address:address.trim()||undefined,notes:orderNotes.trim()||undefined,items:orderItems(),total:Number(total.toFixed(2)),status:existing?.status||"new",paymentStatus,saleId:saleId||existing?.saleId,createdBy:existing?.createdBy||workspace.user?.id,createdAt:existing?.createdAt||now,updatedAt:now};',
'return{id:existing?.id||makeId("order"),tenantId:workspace.tenantId,branchId:workspace.branchId,number:existing?.number||nextOrderNumber(next,workspace.tenantId,workspace.branchId),serviceMode:activeServiceMode,tableLabel:(activeServiceMode==="table"||activeServiceMode==="delivery")?tableLabel.trim()||undefined:undefined,customerId:customerId||undefined,customerName:customerName.trim()||customers.find(c=>c.id===customerId)?.name||undefined,phone:phone.trim()||undefined,address:address.trim()||undefined,notes:orderNotes.trim()||undefined,items:orderItems(),total:Number(total.toFixed(2)),status:existing?.status||"new",paymentStatus,saleId:saleId||existing?.saleId,createdBy:existing?.createdBy||workspace.user?.id,discountPercent:appliedDiscount||undefined,internalConsumption:internalConsumption||undefined,createdAt:existing?.createdAt||now,updatedAt:now};',
'build order operational fields')
t=rep(t,
'if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes,optionSelections:parseProductOptionSelection(optionConfigFor(product),item.notes)})',
'if(product)lines.push({...product,qty:item.qty,cartKey:cartKeyFor(product.id,item.notes),optionLabel:item.notes,optionSelections:parseProductOptionSelection(optionConfigFor(product),item.notes),lineMode:item.courtesy?"courtesy":"sale"})',
'order line courtesy load')
t=rep(t,
'const applyLoadedOrder=(order:FoodOrderRecord|undefined,mode:ServiceMode,label:string,source:ReturnType<typeof loadLocalDatabase>)=>{setServiceMode(mode);setTableLabel(mode==="table"?label:"");setQuery("");setCategory("Todos");setPayment("cash");setMixedCash("");setLastSaleId("");setClearArmed(false);',
'const applyLoadedOrder=(order:FoodOrderRecord|undefined,mode:ServiceMode,label:string,source:ReturnType<typeof loadLocalDatabase>)=>{setServiceMode(mode);setTableLabel((mode==="table"||mode==="delivery")?label:"");setQuery("");setCategory("Todos");setPayment("cash");setMixedCash("");setCashReceived("");setDiscountPercent(clampDiscount(Number(order?.discountPercent)||0));setInternalConsumption(Boolean(order?.internalConsumption));setLastSaleId("");setClearArmed(false);',
'loaded order operational state')
t=rep(t,
'setMessage(mode==="table"?`Mesa ${label} · libre, lista para nuevo pedido`:`${serviceLabel[mode]} · listo para nuevo pedido`);',
'setMessage(mode==="table"?`Mesa ${label} · libre, lista para nuevo pedido`:mode==="delivery"?`Domicilio ${label} · listo para nuevo pedido`:`${serviceLabel[mode]} · listo para nuevo pedido`);',
'empty delivery message')
t=rep(t,
'setMessage(mode==="table"?`Mesa ${label} recuperada · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`:`${serviceLabel[mode]} recuperado · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`)',
'setMessage(mode==="table"?`Mesa ${label} recuperada · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`:mode==="delivery"?`Domicilio ${label} recuperado · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`:`${serviceLabel[mode]} recuperado · ${lines.reduce((sum,line)=>sum+line.qty,0)} productos`)',
'loaded delivery message')
t=rep(t,
'  const loadTableOrder=(label:string,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source);applyLoadedOrder(findOpenTableOrder(source,workspace,label),"table",label,source)};\n  const loadServiceOrder=(mode:Exclude<ServiceMode,"table">,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source);applyLoadedOrder(findOpenServiceOrder(source,workspace,mode),mode,"",source)};',
'  const loadTableOrder=(label:string,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source);applyLoadedOrder(findOpenTableOrder(source,workspace,label),"table",label,source)};\n  const loadDeliveryOrder=(label:string,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source);applyLoadedOrder(findOpenDeliveryOrder(source,workspace,label),"delivery",label,source)};\n  const loadServiceOrder=(mode:Exclude<ServiceMode,"table"|"delivery">,source=loadLocalDatabase())=>{const workspace=getWorkspaceContext(source);applyLoadedOrder(findOpenServiceOrder(source,workspace,mode),mode,"",source)};',
'load delivery context')
t=rep(t,
'  const selectTable=(label:string)=>{if(activeServiceMode==="table"&&tableLabel===label)return;if(!persistCurrentContext())return;loadTableOrder(label,loadLocalDatabase())};\n  const changeServiceMode=(mode:ServiceMode)=>{if(mode===activeServiceMode)return;setClearArmed(false);if(!persistCurrentContext())return;const source=loadLocalDatabase();if(mode==="table"){setServiceMode("table");setTableLabel("");setCart([]);setActiveOrderId("");resetCustomer();setQuery("");setCategory("Todos");setPayment("cash");setMixedCash("");setDb(source);setMessage("Local / mesa · selecciona la mesa que vas a atender");return}loadServiceOrder(mode,source)};',
'  const selectTable=(label:string)=>{if(activeServiceMode==="table"&&tableLabel===label)return;if(!persistCurrentContext())return;loadTableOrder(label,loadLocalDatabase())};\n  const selectDelivery=(label:string)=>{if(activeServiceMode==="delivery"&&tableLabel===label)return;if(!persistCurrentContext())return;loadDeliveryOrder(label,loadLocalDatabase())};\n  const createDelivery=()=>{if(!persistCurrentContext())return;const source=loadLocalDatabase(),workspace=getWorkspaceContext(source),used=new Set(source.orders.filter(order=>isOpenOrder(order,workspace)&&order.serviceMode==="delivery").map(order=>Number(order.tableLabel)||0));let slot=1;while(used.has(slot))slot++;applyLoadedOrder(undefined,"delivery",String(slot),source)};\n  const changeServiceMode=(mode:ServiceMode)=>{if(mode===activeServiceMode)return;setClearArmed(false);if(!persistCurrentContext())return;const source=loadLocalDatabase();if(mode==="table"||mode==="delivery"){setServiceMode(mode);setTableLabel("");setCart([]);setActiveOrderId("");resetCustomer();setQuery("");setCategory("Todos");setPayment("cash");setMixedCash("");setCashReceived("");setDiscountPercent(0);setInternalConsumption(false);setDb(source);setMessage(mode==="table"?"Local / mesa · selecciona la mesa que vas a atender":"Domicilio · selecciona uno en espera o crea uno nuevo");return}loadServiceOrder(mode,source)};',
'select delivery and change mode')
# utility operations before clearCurrent
t=rep(t,
'  const clearCurrent=()=>{if(!cart.length)return;',
'  const toggleCourtesy=(cartKey:string)=>{if(internalConsumption)return;setCart(current=>current.map(line=>line.cartKey===cartKey?{...line,lineMode:line.lineMode==="courtesy"?"sale":"courtesy"}:line))};\n  const applyDiscount=(value:number)=>{const next=clampDiscount(value);setDiscountPercent(next);if(![5,10,12,15,20].includes(next))setCustomDiscount(next?String(next):"");else setCustomDiscount("")};\n  const toggleInternal=()=>{setInternalConsumption(value=>{const next=!value;if(next){setPayment("cash");setMixedCash("");setCashReceived("");setDiscountPercent(0);setCustomDiscount("");resetCustomer()}return next})};\n  const moveCategory=(source:string,target:string)=>{if(!source||!target||source===target||source==="Todos"||target==="Todos")return;const order=[...orderedCategories],from=order.indexOf(source),to=order.indexOf(target);if(from<0||to<0)return;order.splice(from,1);order.splice(to,0,source);const next=loadLocalDatabase(),workspace=getWorkspaceContext(next),current=getTenantSettings(next,workspace.tenantId),updated={...current,categoryOrder:order};next.settings=next.settings.filter(item=>item.tenantId!==workspace.tenantId);next.settings.push(updated);saveLocalDatabase(next);setDb(loadLocalDatabase());setDragCategory("");setDragOverCategory("");window.dispatchEvent(new CustomEvent(KIUBO_DATA_REFRESHED,{detail:{source:"category-order"}}))};\n  const clearCurrent=()=>{if(!cart.length)return;',
'cart operational utilities')
t=rep(t,
'setMixedCash("");setMessage(activeServiceMode',
'setMixedCash("");setCashReceived("");setDiscountPercent(0);setCustomDiscount("");setInternalConsumption(false);setMessage(activeServiceMode',
'clear operational state')
# checkout initial guards
needle='  const checkout=async()=>{\n    if(!cart.length){setMessage("Agrega al menos un producto");return}\n'
replacement='  const checkout=async()=>{\n    if(!cart.length){setMessage("Agrega al menos un producto");return}\n    if(payment==="cash"&&!internalConsumption&&total>0&&cashReceived.trim()&&(!Number.isFinite(receivedNumber)||receivedNumber<total)){setMessage(`Recibido insuficiente · faltan ${money(total-(Number.isFinite(receivedNumber)?receivedNumber:0))}`);return}\n'
t=rep(t,needle,replacement,'cash received guard')
t=t.replace('if(payment==="mixed"&&!mixedIsValid)', 'if(!internalConsumption&&payment==="mixed"&&!mixedIsValid)',1)
# cash session guards: only when money actually changes hands
t=t.replace('if(payment==="cash"&&settings.requireCashSession&&!cashSession)', 'if(payment==="cash"&&total>0&&settings.requireCashSession&&!cashSession)',1)
t=t.replace('if(payment==="mixed"&&!cashSession)', 'if(payment==="mixed"&&total>0&&!cashSession)',1)
# grouped sale construction wholesale
group_old='''    const grouped=new Map<string,{product:TenantProduct;qty:number;options:Map<string,number>}>();for(const line of cart){const current=next.tenantProducts.find(p=>p.id===line.id&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId);if(!current||(current.trackStock!==false&&!recipeInventoryActive&&current.stock<line.qty)){setMessage(`Revisa stock de ${line.name}`);refresh();return}const group=grouped.get(line.id)||{product:current,qty:0,options:new Map<string,number>()};group.qty+=line.qty;if(line.optionLabel)group.options.set(line.optionLabel,(group.options.get(line.optionLabel)||0)+line.qty);grouped.set(line.id,group)}if(packagingFee&&packagingProduct){const current=next.tenantProducts.find(p=>p.id===packagingProduct.id);if(current)grouped.set(current.id,{product:current,qty:1,options:new Map()})}
    const now=new Date().toISOString(),saleItems=[...grouped.values()].map(group=>{const optionText=[...group.options.entries()].map(([label,qty])=>`${label}${qty>1?` ×${qty}`:""}`).join(" / ");return{productId:group.product.id,name:optionText?`${group.product.name} · ${optionText}`:group.product.name,qty:group.qty,unitPrice:group.product.price,unitCost:group.product.cost,optionLabel:optionText||undefined}}),sale:SaleWithPaymentBreakdown={id:makeId("sale"),tenantId:workspace.tenantId,branchId:workspace.branchId,customerId:customerId||undefined,total:Number(total.toFixed(2)),payment,items:saleItems,createdAt:now,paymentBreakdown:payment==="mixed"?mixedBreakdown:undefined};sale.clientOperationId=sale.id;'''
group_new='''    const grouped=new Map<string,{product:TenantProduct;qty:number;options:Map<string,number>;lineMode:"sale"|"courtesy"}>(),stockGrouped=new Map<string,{product:TenantProduct;qty:number}>();for(const line of cart){const current=next.tenantProducts.find(p=>p.id===line.id&&p.tenantId===workspace.tenantId&&p.branchId===workspace.branchId);if(!current||(current.trackStock!==false&&!recipeInventoryActive&&current.stock<line.qty)){setMessage(`Revisa stock de ${line.name}`);refresh();return}const lineMode=line.lineMode==="courtesy"?"courtesy":"sale",groupKey=`${line.id}::${lineMode}`,group=grouped.get(groupKey)||{product:current,qty:0,options:new Map<string,number>(),lineMode};group.qty+=line.qty;if(line.optionLabel)group.options.set(line.optionLabel,(group.options.get(line.optionLabel)||0)+line.qty);grouped.set(groupKey,group);const stock=stockGrouped.get(line.id)||{product:current,qty:0};stock.qty+=line.qty;stockGrouped.set(line.id,stock)}if(packagingFee&&packagingProduct){const current=next.tenantProducts.find(p=>p.id===packagingProduct.id);if(current)stockGrouped.set(current.id,{product:current,qty:1})}
    const effectivePayment:Payment=internalConsumption||total<=0?"cash":payment,now=new Date().toISOString(),saleItems=[...grouped.values()].map(group=>{const optionText=[...group.options.entries()].map(([label,qty])=>`${label}${qty>1?` ×${qty}`:""}`).join(" / "),baseName=optionText?`${group.product.name} · ${optionText}`:group.product.name,lineMode=internalConsumption?"internal":group.lineMode;return{productId:group.product.id,name:encodeOperationalItemName(baseName,lineMode,appliedDiscount),qty:group.qty,unitPrice:effectiveUnitPrice(group.product.price,lineMode,appliedDiscount),unitCost:group.product.cost,optionLabel:optionText||undefined}});if(packagingFee&&packagingProduct)saleItems.push({productId:packagingProduct.id,name:encodeOperationalItemName("Envase",internalConsumption?"internal":"sale",appliedDiscount),qty:1,unitPrice:effectiveUnitPrice(packagingProduct.price,internalConsumption?"internal":"sale",appliedDiscount),unitCost:packagingProduct.cost,optionLabel:undefined});const sale:SaleWithPaymentBreakdown={id:makeId("sale"),tenantId:workspace.tenantId,branchId:workspace.branchId,customerId:customerId||undefined,total:Number(total.toFixed(2)),payment:effectivePayment,items:saleItems,createdAt:now,paymentBreakdown:effectivePayment==="mixed"?mixedBreakdown:undefined};sale.clientOperationId=sale.id;'''
t=rep(t,group_old,group_new,'sale grouping')
t=t.replace('if(payment==="credit"&&customerId)', 'if(effectivePayment==="credit"&&customerId)',1)
t=t.replace('if(payment==="mixed"&&cashSession)', 'if(effectivePayment==="mixed"&&cashSession)',1)
t=t.replace('const impacts=recipeInventoryActive?resolveInventoryImpact(cart.map(line=>({productId:line.id,qty:line.qty,optionSelections:line.optionSelections})),next.tenantProducts.filter(product=>product.tenantId===workspace.tenantId&&product.branchId===workspace.branchId&&product.active)):[...grouped.values()].map(group=>({productId:group.product.id,qty:group.qty,sources:[group.product.name]}));', 'const impacts=recipeInventoryActive?resolveInventoryImpact(cart.map(line=>({productId:line.id,qty:line.qty,optionSelections:line.optionSelections})),next.tenantProducts.filter(product=>product.tenantId===workspace.tenantId&&product.branchId===workspace.branchId&&product.active)):[...stockGrouped.values()].map(group=>({productId:group.product.id,qty:group.qty,sources:[group.product.name]}));',1)
t=rep(t,
'    const methodText=payment==="mixed"?`Mixto · ${money(mixedBreakdown.cash)} efectivo + ${money(mixedBreakdown.transfer)} transferencia`:paymentLabel[payment];\n    const saleContext=tableLabel?`Mesa ${tableLabel}`:activeServiceMode==="delivery"?"Domicilio":activeServiceMode==="takeaway"?"Para llevar":"Venta";setDb(next);setCart([]);setQuery("");setPayment("cash");setMixedCash("");resetCustomer();setActiveOrderId("");setLastSaleId(sale.id);setClearArmed(false);setSaleSuccess({amount:sale.total,method:methodText,context:saleContext});setMessage(`Venta guardada · ${methodText} · ${money(sale.total)}${tableLabel?` · Mesa ${tableLabel}`:""}`);',
'    const methodText=internalConsumption?"Consumo interno":sale.total<=0&&courtesySubtotal>0?"Cortesía":effectivePayment==="mixed"?`Mixto · ${money(mixedBreakdown.cash)} efectivo + ${money(mixedBreakdown.transfer)} transferencia`:paymentLabel[effectivePayment];\n    const saleContext=activeServiceMode==="table"&&tableLabel?`Mesa ${tableLabel}`:activeServiceMode==="delivery"&&tableLabel?`Domicilio ${tableLabel}`:activeServiceMode==="delivery"?"Domicilio":activeServiceMode==="takeaway"?"Para llevar":"Venta",successChange=effectivePayment==="cash"?changeDue:0;setDb(next);setCart([]);setQuery("");setPayment("cash");setMixedCash("");setCashReceived("");setDiscountPercent(0);setCustomDiscount("");setInternalConsumption(false);resetCustomer();setActiveOrderId("");setLastSaleId(sale.id);setClearArmed(false);setSaleSuccess({amount:sale.total,method:methodText,context:saleContext,change:successChange});setMessage(`${internalConsumption?"Consumo registrado":"Venta guardada"} · ${methodText} · ${money(sale.total)}${successChange>0?` · cambio ${money(successChange)}`:""}`);',
'checkout success state')
# save order messaging
t=t.replace('if(!silent)setMessage(activeServiceMode==="table"?`Mesa ${tableLabel} guardada · puedes atender otro pedido`:`${serviceLabel[activeServiceMode]} guardado · puedes atender otro pedido`);', 'if(!silent)setMessage(activeServiceMode==="table"?`Mesa ${tableLabel} guardada · puedes atender otro pedido`:activeServiceMode==="delivery"?`Domicilio ${tableLabel} guardado · puedes atender otro pedido`:`${serviceLabel[activeServiceMode]} guardado · puedes atender otro pedido`);',1)
# Render: delivery selector + draggable categories
old='<div className="category-strip">{categories.map(item=><button key={item} className={category===item?"selected":""} onClick={()=>setCategory(item)}>{item}</button>)}</div>'
new='{activeServiceMode==="delivery"&&<div className="delivery-selector"><div className="delivery-selector-head"><span>DOMICILIOS EN ESPERA</span><button type="button" onClick={createDelivery}>＋ Nuevo domicilio</button></div><div className="delivery-selector-grid">{deliveryLabels.map(label=>{const open=openDeliveryOrders.find(order=>order.tableLabel===label),active=tableLabel===label;return <button type="button" key={label} className={active?"active":""} onClick={()=>selectDelivery(label)}><strong>Domicilio {label}</strong><span>{active?(cartCount?`${cartCount} prod. · ${money(total)}`:"Pedido vacío"):open?`${open.items.reduce((sum,item)=>sum+item.qty,0)} prod. · ${money(open.total)}`:"Libre"}</span></button>})}</div></div>}<div className="category-strip">{categories.map(item=><button key={item} draggable={item!=="Todos"} className={`${category===item?"selected":""} ${dragCategory===item?"category-dragging":""} ${dragOverCategory===item?"category-drop-target":""}`} onClick={()=>setCategory(item)} onDragStart={()=>{if(item!=="Todos")setDragCategory(item)}} onDragOver={event=>{if(item!=="Todos"){event.preventDefault();setDragOverCategory(item)}}} onDrop={event=>{event.preventDefault();moveCategory(dragCategory,item)}} onDragEnd={()=>{setDragCategory("");setDragOverCategory("")}}>{item}</button>)}<span className="category-order-hint">Arrastra para ordenar</span></div>'
t=rep(t,old,new,'render delivery and category drag')
# header delivery label
t=rep(t,
'<span className="eyebrow">{activeServiceMode==="table"&&tableLabel?`MESA ${tableLabel}`:foodService?activeOrderId?"PEDIDO CARGADO":serviceLabel[activeServiceMode].toUpperCase():"VENTA ACTUAL"}</span>',
'<span className="eyebrow">{activeServiceMode==="table"&&tableLabel?`MESA ${tableLabel}`:activeServiceMode==="delivery"&&tableLabel?`DOMICILIO ${tableLabel}`:internalConsumption?"CONSUMO INTERNO":foodService?activeOrderId?"PEDIDO CARGADO":serviceLabel[activeServiceMode].toUpperCase():"VENTA ACTUAL"}</span>',
'checkout context heading')
# cart render line block
old='<div className="cart-lines pro-cart-lines">{cart.length===0?<div className="pro-empty-cart"><span>＋</span><strong>Pedido vacío</strong><small>Selecciona productos para comenzar.</small></div>:cart.map(line=><div className="cart-line interactive pro-cart-line" key={line.cartKey}><div className="cart-line-thumb">{line.imageUrl?<img src={line.imageUrl} alt=""/>:<span>{line.name.charAt(0)}</span>}</div><div className="cart-line-copy"><strong>{line.name}</strong>{line.optionLabel&&<em>{line.optionLabel}</em>}<span>{money(line.price)} c/u</span></div><div className="qty pro-qty"><button onClick={()=>changeQty(line.cartKey,-1)} aria-label={`Quitar uno de ${line.name}`}>−</button><b>{line.qty}</b><button onClick={()=>changeQty(line.cartKey,1)} aria-label={`Agregar uno de ${line.name}`}>＋</button></div><strong className="cart-line-total">{money(line.price*line.qty)}</strong><button className="cart-line-remove" onClick={()=>removeLine(line.cartKey)} aria-label={`Eliminar ${line.name} del pedido`}>×</button></div>)}</div>'
new='<div className="cart-lines pro-cart-lines">{cart.length===0?<div className="pro-empty-cart"><span>＋</span><strong>Pedido vacío</strong><small>Selecciona productos para comenzar.</small></div>:cart.map(line=><div className={`cart-line interactive pro-cart-line ${line.lineMode==="courtesy"?"courtesy-line":""}`} key={line.cartKey}><div className="cart-line-thumb">{line.imageUrl?<img src={line.imageUrl} alt=""/>:<span>{line.name.charAt(0)}</span>}</div><div className="cart-line-copy"><strong>{line.name}</strong>{line.optionLabel&&<em>{line.optionLabel}</em>}<span>{money(line.price)} c/u</span><div className="pos-line-actions">{!internalConsumption&&<button className={`pos-courtesy-toggle ${line.lineMode==="courtesy"?"active":""}`} type="button" onClick={()=>toggleCourtesy(line.cartKey)}>{line.lineMode==="courtesy"?"✓ Cortesía":"Cortesía"}</button>}</div></div><div className="qty pro-qty"><button onClick={()=>changeQty(line.cartKey,-1)} aria-label={`Quitar uno de ${line.name}`}>−</button><b>{line.qty}</b><button onClick={()=>changeQty(line.cartKey,1)} aria-label={`Agregar uno de ${line.name}`}>＋</button></div><strong className="cart-line-total">{internalConsumption||line.lineMode==="courtesy"?money(0):money(effectiveUnitPrice(line.price,"sale",appliedDiscount)*line.qty)}</strong><button className="cart-line-remove" onClick={()=>removeLine(line.cartKey)} aria-label={`Eliminar ${line.name} del pedido`}>×</button></div>)}</div>'
t=rep(t,old,new,'cart courtesy rendering')
# checkout summary + operational controls
old='<div className="checkout-summary pro-checkout-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div>{packagingFee>0&&<div className="packaging-row"><span>Envase</span><b>+ {money(packagingFee)}</b></div>}<div className="cart-total"><span>TOTAL</span><strong>{money(total)}</strong></div></div>\n      <div className="payment-grid pro-payment-grid">{paymentOptions.map(method=><button key={method} className={payment===method?"selected":""} onClick={()=>{setPayment(method);if(method==="mixed"&&payment!=="mixed")setMixedCash((total/2).toFixed(2));if(method!=="mixed")setMixedCash("");if(method!=="credit"){setCreditQuery("");setCreditCreateOpen(false)}}}>{paymentLabel[method]}</button>)}</div>'
new='<div className="pos-adjustments"><div className="pos-adjustments-head"><span>AJUSTES DEL PEDIDO</span><button className={`pos-internal-toggle ${internalConsumption?"active":""}`} type="button" onClick={toggleInternal}>{internalConsumption?"✓ Consumo interno":"Consumo interno"}</button></div>{!internalConsumption&&<><div className="pos-discount-row"><button type="button" className={appliedDiscount===0?"active":""} onClick={()=>applyDiscount(0)}>Sin desc.</button>{[5,10,12,15,20].map(value=><button type="button" key={value} className={appliedDiscount===value?"active":""} onClick={()=>applyDiscount(value)}>{value}%</button>)}<input className="pos-discount-custom" aria-label="Descuento personalizado" type="number" min="0" max="100" step="1" value={customDiscount} onChange={e=>{setCustomDiscount(e.target.value);setDiscountPercent(clampDiscount(Number(e.target.value)||0))}} placeholder="Otro %"/></div>{discountAmount>0&&<div className="pos-discount-summary"><span>Descuento {appliedDiscount}%</span><strong>- {money(discountAmount)}</strong></div>}</>}</div>{internalConsumption&&<div className="internal-sale-banner">Todo este pedido se registrará a $0 y sí descontará inventario.</div>}<div className="checkout-summary pro-checkout-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div>{courtesySubtotal>0&&<div className="courtesy-row"><span>Cortesía</span><b>- {money(courtesySubtotal)}</b></div>}{packagingFee>0&&<div className="packaging-row"><span>Envase</span><b>+ {money(packagingFee)}</b></div>}{discountAmount>0&&<div className="discount-row"><span>Descuento {appliedDiscount}%</span><b>- {money(discountAmount)}</b></div>}{internalConsumption&&<div className="internal-row"><span>Consumo interno</span><b>- {money(subtotal+packagingFee)}</b></div>}<div className="cart-total"><span>TOTAL</span><strong>{money(total)}</strong></div></div>\n      {!internalConsumption&&total>0&&<div className="payment-grid pro-payment-grid">{paymentOptions.map(method=><button key={method} className={payment===method?"selected":""} onClick={()=>{setPayment(method);setCashReceived("");if(method==="mixed"&&payment!=="mixed")setMixedCash((total/2).toFixed(2));if(method!=="mixed")setMixedCash("");if(method!=="credit"){setCreditQuery("");setCreditCreateOpen(false)}}}>{paymentLabel[method]}</button>)}</div>}'
t=rep(t,old,new,'checkout adjustments and summary')
# insert cash received after mixed box
mixed_end='</small></div>}\n      <button className={`button primary checkout ${payment==="credit"?"credit-charge":""}`}'
insert='</small></div>}{!internalConsumption&&payment==="cash"&&total>0&&<div className="pos-cash-received"><div><label>Total<input value={total.toFixed(2)} readOnly/></label><label>Recibido<input value={cashReceived} onChange={e=>setCashReceived(e.target.value)} type="number" min={total} step="0.01" inputMode="decimal" placeholder={total.toFixed(2)}/></label></div><div className="pos-cash-quick"><button type="button" onClick={()=>setCashReceived(total.toFixed(2))}>Exacto</button>{[5,10,20,50,100].filter(value=>value>=Math.ceil(total)).slice(0,4).map(value=><button type="button" key={value} onClick={()=>setCashReceived(String(value))}>${value}</button>)}</div><div className="pos-change"><span>Cambio</span><strong>{money(changeDue)}</strong></div></div>}\n      <div className="pos-checkout-footer"><button className={`button primary checkout ${payment==="credit"&&!internalConsumption&&total>0?"credit-charge":""}`}'
t=rep(t,mixed_end,insert,'cash received and sticky footer open')
# Replace button content/disabled and close footer after notes
old='onClick={()=>void checkout()} disabled={!cart.length||!mixedIsValid}>{payment==="credit"?`Fiar ${money(total)}`:payment==="mixed"?`Cobrar dividido ${money(total)}`:`Cobrar ${money(total)}`}</button>{foodService&&<button className="button secondary checkout hold-order" aria-label="Guardar pedido sin cobrar" onClick={()=>saveOrder(false)} disabled={!cart.length}>{activeServiceMode==="table"&&tableLabel?`Poner Mesa ${tableLabel} en espera`:activeServiceMode!=="table"?`Guardar ${serviceLabel[activeServiceMode]} en espera`:"Guardar pedido en espera"}</button>}{lastSaleId&&<a className="button secondary checkout customer-ticket-link" target="_blank" rel="noreferrer" href={`/receipt?sale=${encodeURIComponent(lastSaleId)}`}>Ticket para el cliente</a>}<p className="cart-note">Comanda para cocina y ticket del cliente se imprimen por separado.</p></aside>'
new='onClick={()=>void checkout()} disabled={!cart.length||!mixedIsValid}>{internalConsumption?"Registrar consumo interno":total<=0?"Registrar cortesía":payment==="credit"?`Fiar ${money(total)}`:payment==="mixed"?`Cobrar dividido ${money(total)}`:`Cobrar ${money(total)}`}</button>{foodService&&!internalConsumption&&<button className="button secondary checkout hold-order" aria-label="Guardar pedido sin cobrar" onClick={()=>saveOrder(false)} disabled={!cart.length}>{activeServiceMode==="table"&&tableLabel?`Poner Mesa ${tableLabel} en espera`:activeServiceMode==="delivery"&&tableLabel?`Guardar Domicilio ${tableLabel} en espera`:activeServiceMode!=="table"?`Guardar ${serviceLabel[activeServiceMode]} en espera`:"Guardar pedido en espera"}</button>}{lastSaleId&&<a className="button secondary checkout customer-ticket-link" target="_blank" rel="noreferrer" href={`/receipt?sale=${encodeURIComponent(lastSaleId)}`}>Ticket para el cliente</a>}<p className="cart-note">Comanda para cocina y ticket del cliente se imprimen por separado.</p></div></aside>'
t=rep(t,old,new,'checkout sticky footer close')
# Success change display
old='<span>{money(saleSuccess.amount)} · {saleSuccess.method} · {saleSuccess.context}</span>'
new='<span>{money(saleSuccess.amount)} · {saleSuccess.method} · {saleSuccess.context}{saleSuccess.change&&saleSuccess.change>0?<em className="change-note"> · Cambio {money(saleSuccess.change)}</em>:null}</span>'
t=rep(t,old,new,'sale success change')
write(p,t)

# --- Receipt --------------------------------------------------------------------------
p=Path("components/ReceiptClient.tsx"); t=read(p)
t=rep(t,
'import { paymentBreakdownForSale,type PaymentBreakdown } from "@/lib/mixed-payment";\nimport { KiuboWordmark } from "./KiuboWordmark";',
'import { paymentBreakdownForSale,type PaymentBreakdown } from "@/lib/mixed-payment";\nimport { operationalDiscountAmount,parseOperationalItemName } from "@/lib/sale-adjustments";\nimport { KiuboWordmark } from "./KiuboWordmark";',
'receipt sale parser import')
t=rep(t,
'  const {sale,order}=data,physicalWidth=data.width==="58mm"?"58mm":"76mm",pageWidth=data.width==="58mm"?"52mm":"70mm",subtotal=sale.items.reduce((sum,item)=>sum+item.qty*item.unitPrice,0),itemCount=sale.items.reduce((sum,item)=>sum+item.qty,0),created=new Date(sale.createdAt);',
'  const {sale,order}=data,physicalWidth=data.width==="58mm"?"58mm":"76mm",pageWidth=data.width==="58mm"?"52mm":"70mm",parsedItems=sale.items.map(item=>({...item,meta:parseOperationalItemName(item.name)})),subtotal=sale.items.reduce((sum,item)=>sum+item.qty*item.unitPrice,0),discountTotal=parsedItems.reduce((sum,item)=>sum+operationalDiscountAmount(item.unitPrice,item.qty,item.meta.discountPercent),0),courtesyUnits=parsedItems.filter(item=>item.meta.mode==="courtesy").reduce((sum,item)=>sum+item.qty,0),internalUnits=parsedItems.filter(item=>item.meta.mode==="internal").reduce((sum,item)=>sum+item.qty,0),itemCount=sale.items.reduce((sum,item)=>sum+item.qty,0),created=new Date(sale.createdAt);',
'receipt parsed totals')
t=rep(t,
'<div className="ticket-title">TICKET DE VENTA</div>',
'<div className="ticket-title">{internalUnits===itemCount&&itemCount>0?"CONSUMO INTERNO":"TICKET DE VENTA"}</div>',
'receipt internal title')
t=rep(t,
'{order&&<div className="service">{modeLabel[order.serviceMode]}{order.tableLabel?` · MESA ${order.tableLabel}`:""}</div>}',
'{order&&<div className="service">{modeLabel[order.serviceMode]}{order.tableLabel?(order.serviceMode==="delivery"?` · DOMICILIO ${order.tableLabel}`:` · MESA ${order.tableLabel}`):""}</div>}',
'receipt delivery slot')
t=rep(t,
'<div className="rule"/><section className="items">{sale.items.map((item,index)=><div className="item" key={`${item.productId}-${index}`}><span><b>{item.qty} × {item.name}</b><small>{money(item.unitPrice)} c/u</small></span><strong>{money(item.qty*item.unitPrice)}</strong></div>)}</section>',
'<div className="rule"/><section className="items">{parsedItems.map((item,index)=><div className="item" key={`${item.productId}-${index}`}><span><b>{item.qty} × {item.meta.displayName}</b><small>{item.meta.mode==="courtesy"?"Cortesía · $0.00":item.meta.mode==="internal"?"Consumo interno · $0.00":item.meta.discountPercent>0?`${money(item.unitPrice)} c/u · -${item.meta.discountPercent}%`:`${money(item.unitPrice)} c/u`}</small></span><strong>{money(item.qty*item.unitPrice)}</strong></div>)}</section>',
'receipt item labels')
t=rep(t,
'<div className="rule"/><section className="totals"><div className="row"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="row payment">',
'<div className="rule"/><section className="totals"><div className="row"><span>Subtotal</span><b>{money(subtotal+discountTotal)}</b></div>{courtesyUnits>0&&<div className="row"><span>Cortesías</span><b>{courtesyUnits} u. · $0.00</b></div>}{internalUnits>0&&<div className="row"><span>Consumo interno</span><b>{internalUnits} u. · $0.00</b></div>}{discountTotal>0&&<div className="row"><span>Descuento</span><b>- {money(discountTotal)}</b></div>}<div className="row payment">',
'receipt operational totals')
write(p,t)

print("YUKI client ops suite patch applied")
